_data/handles/Hexens_OGs.json
This auto-generated PR modifies the team Hexens_OGs
The request was made by tpiliposian
=> Edit team Hexens_OGs

_data/handles/ZanTool.json
Auto-generated PR to register the new warden ZanTool
=> Register warden ZanTool

_data/handles/poorevil.json
Auto-generated PR to register the new warden poorevil
@poorevil
=> Register warden poorevil

_data/handles/y403l.json
Auto-generated PR to register the new warden y403l
=> Register warden y403l

_data/handles/kevo_0.json
Auto-generated PR to register the new warden kevo_0
@fac3m4n
=> Register warden kevo_0

_data/handles/crunch.json
Auto-generated PR to register the new warden crunch
@0xcrunch
=> Register warden crunch

_data/handles/unsafesol.json
This auto-generated PR creates the team unsafesol
=> Create team unsafesol

_data/handles/Ukriyte.json
Auto-generated PR to register the new warden Ukriyte
@Ukriyte
=> Register warden Ukriyte

_data/handles/roland.json
Auto-generated PR to register the new warden roland
@rolandpo
=> Register warden roland

_data/handles/zabihullahazadzoi.json
Auto-generated PR to register the new warden zabihullahazadzoi
@zabihullah-azadzoi
=> Register warden zabihullahazadzoi

_data/handles/herniadlf.json
Auto-generated PR to register the new warden herniadlf
=> Register warden herniadlf

_data/handles/nenene.json
Auto-generated PR to register the new warden nenene
=> Register warden nenene

_data/handles/1913.json
Auto-generated PR to register the new warden 1913
=> Register warden 1913

_data/handles/62theories.json
Auto-generated PR to register the new warden 62theories
=> Register warden 62theories

_data/handles/121ajaya.json
Auto-generated PR to register the new warden 121ajaya
=> Register warden 121ajaya

_data/handles/cromewar.json
Auto-generated PR to register the new warden cromewar
@cromewar
=> Register warden cromewar

_data/handles/yeatsdai.json
Auto-generated PR to register the new warden yeatsdai
=> Register warden yeatsdai

_data/handles/zed.json
Auto-generated PR to register the new warden zed
=> Register warden zed

_data/handles/breakpo1nt.json
Auto-generated PR to register the new warden breakpo1nt
=> Register warden breakpo1nt

_data/handles/mbloog.json
Auto-generated PR to register the new warden mbloog
=> Register warden mbloog

_data/handles/MA1125.json
Auto-generated PR to register the new warden MA1125
=> Register warden MA1125

_data/handles/carlos_sf.json
Auto-generated PR to register the new warden carlos_sf
=> Register warden carlos_sf

_data/handles/speCode.json
Auto-generated PR to register the new warden speCode
@migangel93
=> Register warden speCode

_data/handles/epistkr.json
Auto-generated PR to register the new warden epistkr
=> Register warden epistkr

_data/handles/andrewch.json
Auto-generated PR to register the new warden andrewch
@lamagt
=> Register warden andrewch

_data/handles/anticl0ck.json
Auto-generated PR to register the new warden anticl0ck
@anticl0ck
=> Register warden anticl0ck

_data/handles/Sleepy.json
This auto-generated PR updates info for warden Sleepy
@0xsomnus
=> Update warden Sleepy

_data/handles/xeros.json
Auto-generated PR to register the new warden xeros
@xeroskim
=> Register warden xeros

_data/handles/sebitokazu.json
Auto-generated PR to register the new warden sebitokazu
@sebitokazu
=> Register warden sebitokazu

_data/handles/Night.json
Auto-generated PR to register the new warden Night
=> Register warden Night

_data/handles/Alan.json
Auto-generated PR to register the new warden Alan
=> Register warden Alan

_data/handles/fren.json
Auto-generated PR to register the new warden fren
@0lston
=> Register warden fren

_data/handles/oyendoJ.json
Auto-generated PR to register the new warden oyendoJ
=> Register warden oyendoJ

_data/handles/lechanselo.json
Auto-generated PR to register the new warden lechanselo
=> Register warden lechanselo

_data/handles/avoloder.json
Auto-generated PR to register the new warden avoloder
=> Register warden avoloder

_data/handles/root.json
Auto-generated PR to register the new warden root
=> Register warden root

_data/handles/qruz.json
Auto-generated PR to register the new warden qruz
@qruz-hq
=> Register warden qruz

_data/handles/Sny.json
Auto-generated PR to register the new warden Sny
=> Register warden Sny

_data/handles/deekcrypto.json
Auto-generated PR to register the new warden deekcrypto
@deekcrypto
=> Register warden deekcrypto

_data/handles/0xTabris.json
Auto-generated PR to register the new warden 0xTabris
=> Register warden 0xTabris

_data/handles/gtvdf.json
Auto-generated PR to register the new warden gtvdf
=> Register warden gtvdf

_data/handles/Endrawela.json
Auto-generated PR to register the new warden Endrawela
@ferdiakhmadirawan44@gmail.com
=> Register warden Endrawela

_data/handles/Mstyv3003.json
Auto-generated PR to register the new warden Mstyv3003
=> Register warden Mstyv3003

_data/handles/brakelessak.json
Auto-generated PR to register the new warden brakelessak
=> Register warden brakelessak

_data/handles/Bomal.json
Auto-generated PR to register the new warden Bomal
=> Register warden Bomal

_data/handles/v0ldemort.json
Auto-generated PR to register the new warden v0ldemort
=> Register warden v0ldemort

_data/handles/Bryan_Conquer.json
@code-423n4/app-wardens this PR can be processed for the warden. Thanks!
=> Create Bryan_Conquer.json Warden Registration

_data/handles/Amaxperera.json
Auto-generated PR to register the new warden Amaxperera
=> Register warden Amaxperera

_data/handles/joeldejo.json
Auto-generated PR to register the new warden joeldejo
=> Register warden joeldejo

_data/handles/ka14ar.json
Auto-generated PR to register the new warden ka14ar
=> Register warden ka14ar

_data/handles/kwisdoom.json
Auto-generated PR to register the new warden kwisdoom
=> Register warden kwisdoom

_data/handles/marcoagner.json
Auto-generated PR to register the new warden marcoagner
=> Register warden marcoagner

_data/handles/karls_team.json
This auto-generated PR creates the team karls_team
=> Create team karls_team

_data/handles/mandi.json
Auto-generated PR to register the new warden mandi
@augustogiles
=> Register warden mandi

_data/handles/K40D40FRTKR0.json
Auto-generated PR to register the new warden K40D40FRTKR0
=> Register warden K40D40FRTKR0

_data/handles/cuteteamm.json
This auto-generated PR creates the team cuteteamm
=> Create team cuteteamm

_data/handles/smartbugs.json
Auto-generated PR to register the new warden smartbugs
@smartbugs1
=> Register warden smartbugs

_data/handles/zmoneep.json
Auto-generated PR to register the new warden zmoneep
@https://github.com/ZiyadMoneep
=> Register warden zmoneep

_data/handles/Galacticur.json
Auto-generated PR to register the new warden Galacticur
@galacticur
=> Register warden Galacticur

_data/handles/Iliyan.json
Auto-generated PR to register the new warden Iliyan
@IliyanOstrovski
=> Register warden Iliyan

_data/handles/cats.json
Auto-generated PR to register the new warden cats
@0xcats
=> Register warden cats

_data/handles/Kamakura.json
Auto-generated PR to register the new warden Kamakura
@cjm00n
=> Register warden Kamakura

_data/handles/836541.json
Auto-generated PR to register the new warden 836541
@836541
=> Register warden 836541

_data/handles/chainsnake.json
Auto-generated PR to register the new warden chainsnake
@royalsalute
=> Register warden chainsnake

_data/handles/ex9.json
Auto-generated PR to register the new warden ex9
=> Register warden ex9

_data/handles/0xfatboy.json
Auto-generated PR to register the new warden 0xfatboy
=> Register warden 0xfatboy

_data/handles/hendrik.json
Auto-generated PR to register the new warden hendrik
=> Register warden hendrik

_data/handles/Ren.json
Auto-generated PR to register the new warden Ren
@RenKoya1
=> Register warden Ren

_data/handles/kkontheway.json
Auto-generated PR to register the new warden kkontheway
@kkontheway
=> Register warden kkontheway

_data/handles/Khoo.json
Auto-generated PR to register the new warden Khoo
=> Register warden Khoo

_data/handles/0xta.json
Auto-generated PR to register the new warden 0xta
=> Register warden 0xta

_data/handles/surya.json
Auto-generated PR to register the new warden surya
=> Register warden surya

_data/handles/agadzhalov.json
Auto-generated PR to register the new warden agadzhalov
@agadzhalov
=> Register warden agadzhalov

_data/handles/Art.json
Auto-generated PR to register the new warden Art
=> Register warden Art

_data/handles/Franklin.json
Auto-generated PR to register the new warden Franklin
@https://github.com/Frankozoalor
=> Register warden Franklin

_data/handles/0xhex.json
Auto-generated PR to register the new warden 0xhex
=> Register warden 0xhex

_data/handles/plainshift.json
This auto-generated PR creates the team plainshift
=> Create team plainshift

_data/handles/thank_you.json
This auto-generated PR updates info for warden thank_you
@mrthankyou
=> Update warden thank_you

_data/handles/uvle6890.json
Auto-generated PR to register the new warden uvle6890
=> Register warden uvle6890

_data/handles/Jiang.json
Auto-generated PR to register the new warden Jiang
=> Register warden Jiang

_data/handles/BigMike.json
Auto-generated PR to register the new warden BigMike
=> Register warden BigMike

_data/handles/gopfan.json
Auto-generated PR to register the new warden gopfan
@DmitryGr
=> Register warden gopfan

_data/handles/iroh.json
Auto-generated PR to register the new warden iroh
@0xiroh
=> Register warden iroh

_data/handles/0xDetermination.json
Auto-generated PR to register the new warden 0xDetermination
@0xDetermination
=> Register warden 0xDetermination

_data/handles/soloking.json
Auto-generated PR to register the new warden soloking
=> Register warden soloking

_data/handles/0xE1.json
Auto-generated PR to register the new warden 0xE1
=> Register warden 0xE1

_data/handles/taijusanagi.json
Auto-generated PR to register the new warden taijusanagi
@taijusanagi
=> Register warden taijusanagi

_data/handles/Beasley.json
Auto-generated PR to register the new warden Beasley
=> Register warden Beasley

_data/handles/fyang1024.json
Auto-generated PR to register the new warden fyang1024
@fyang1024
=> Register warden fyang1024

_data/handles/leath.json
Auto-generated PR to register the new warden leath
=> Register warden leath

_data/handles/0xmystery.json
Auto-generated PR to register the new warden 0xmystery
=> Register warden 0xmystery

_data/handles/MrLegend.json
Auto-generated PR to register the new warden MrLegend
=> Register warden MrLegend

_data/handles/Vladimir.json
Auto-generated PR to register the new warden Vladimir
@VladimirSavov
=> Register warden Vladimir

_data/handles/QingqingZhang.json
Auto-generated PR to register the new warden QingqingZhang
@20131001
=> Register warden QingqingZhang

_data/handles/mrjorystewartbaxter.json
Auto-generated PR to register the new warden mrjorystewartbaxter
@fvelazquez-X
=> Register warden mrjorystewartbaxter

_data/handles/denstr.json
Auto-generated PR to register the new warden denstr
=> Register warden denstr

_data/handles/Silverskrrrt.json
Auto-generated PR to register the new warden Silverskrrrt
@Silverskrrrt
=> Register warden Silverskrrrt

_data/handles/rektthecode.json
This auto-generated PR creates the team rektthecode
=> Create team rektthecode

_data/handles/datacirexyen.json
Auto-generated PR to register the new warden datacirexyen
@datacirexyen
=> Register warden datacirexyen

_data/handles/technicallyty0.json
Auto-generated PR to register the new warden technicallyty0
@technicallyty
=> Register warden technicallyty0

_data/handles/GREEN-GECKO-REACH.json
This auto-generated PR creates the team GREEN-GECKO-REACH
=> Create team GREEN-GECKO-REACH

_data/handles/ocean2018.json
Auto-generated PR to register the new warden ocean2018
@Lambda2023
=> Register warden ocean2018

_data/handles/sid32.json
Auto-generated PR to register the new warden sid32
=> Register warden sid32

_data/handles/AamirMK.json
Auto-generated PR to register the new warden AamirMK
=> Register warden AamirMK

_data/handles/Silverwind.json
Auto-generated PR to register the new warden Silverwind
@CagatayAkkas
=> Register warden Silverwind

_data/handles/catalyst.json
Auto-generated PR to register the new warden catalyst
=> Register warden catalyst

_data/handles/skyluker.json
Auto-generated PR to register the new warden skyluker
=> Register warden skyluker

_data/handles/apm555.json
Auto-generated PR to register the new warden apm555
=> Register warden apm555

_data/handles/anyways.json
This auto-generated PR creates the team anyways
=> Create team anyways

_data/handles/AlexeyVanilov.json
Auto-generated PR to register the new warden AlexeyVanilov
=> Register warden AlexeyVanilov

_data/handles/Ddyy.json
Auto-generated PR to register the new warden Ddyy
=> Register warden Ddyy

_data/handles/Powell.json
Auto-generated PR to register the new warden Powell
@matsham
=> Register warden Powell

_data/handles/dmitev.json
Auto-generated PR to register the new warden dmitev
=> Register warden dmitev

_data/handles/amolina.json
Auto-generated PR to register the new warden amolina
=> Register warden amolina

_data/handles/ares-dev05.json
Auto-generated PR to register the new warden ares-dev05
@ares-dev05
=> Register warden ares-dev05

_data/handles/davidfang.json
Auto-generated PR to register the new warden davidfang
=> Register warden davidfang

_data/handles/wulawula.json
Auto-generated PR to register the new warden wulawula
=> Register warden wulawula

_data/handles/BEGBIE.json
Auto-generated PR to register the new warden BEGBIE
@0xBEGBIE
=> Register warden BEGBIE

_data/handles/0xanjalit.json
Auto-generated PR to register the new warden 0xanjalit
=> Register warden 0xanjalit

_data/handles/llsforest.json
Auto-generated PR to register the new warden llsforest
@llsforset
=> Register warden llsforest

_data/handles/Bravo1B9.json
Auto-generated PR to register the new warden Bravo1B9
@Brendon Rofe
=> Register warden Bravo1B9

_data/handles/surajmoolya.json
Auto-generated PR to register the new warden surajmoolya
=> Register warden surajmoolya

_data/handles/BlockBurner420.json
Auto-generated PR to register the new warden BlockBurner420
=> Register warden BlockBurner420

_data/handles/sahlo_folina.json
Auto-generated PR to register the new warden sahlo_folina
@sahlo-folina
=> Register warden sahlo_folina

_data/handles/trongdth.json
Auto-generated PR to register the new warden trongdth
@trongdth
=> Register warden trongdth

_data/handles/lodelux.json
Auto-generated PR to register the new warden lodelux
@lodelux
=> Register warden lodelux

_data/handles/dos.json
Auto-generated PR to register the new warden dos
@datschill
=> Register warden dos

_data/handles/spidy730.json
Auto-generated PR to register the new warden spidy730
=> Register warden spidy730

_data/handles/Drinkler.json
Auto-generated PR to register the new warden Drinkler
@Drinkler
=> Register warden Drinkler

_data/handles/Robert29000.json
Auto-generated PR to register the new warden Robert29000
=> Register warden Robert29000

_data/handles/Efe_Eric.json
Auto-generated PR to register the new warden Efe_Eric
=> Register warden Efe_Eric

_data/handles/krishna117.json
Auto-generated PR to register the new warden krishna117
=> Register warden krishna117

_data/handles/doublezeroseven.json
Auto-generated PR to register the new warden doublezeroseven
=> Register warden doublezeroseven

_data/handles/Lasosj.json
Auto-generated PR to register the new warden Lasosj
=> Register warden Lasosj

_data/handles/joicygiore.json
Auto-generated PR to register the new warden joicygiore
=> Register warden joicygiore

_data/handles/DarkTower.json
This auto-generated PR modifies the team DarkTower
The request was made by Gelato_ST
=> Edit team DarkTower

_data/handles/hashval.json
Auto-generated PR to register the new warden hashval
=> Register warden hashval

_data/handles/0xSanyam21.json
Auto-generated PR to register the new warden 0xSanyam21
@Sanyam2103
=> Register warden 0xSanyam21

_data/handles/Kainan.json
Auto-generated PR to register the new warden Kainan
=> Register warden Kainan

_data/handles/davidmansion.json
Auto-generated PR to register the new warden davidmansion
@davidmansion
=> Register warden davidmansion

_data/handles/allwin199.json
Auto-generated PR to register the new warden allwin199
@allwin199
=> Register warden allwin199

_data/handles/DeFiSnipper.json
Auto-generated PR to register the new warden DeFiSnipper
=> Register warden DeFiSnipper

_data/handles/Skylice.json
Auto-generated PR to register the new warden Skylice
=> Register warden Skylice

_data/handles/billeldzz.json
Auto-generated PR to register the new warden billeldzz
=> Register warden billeldzz

_data/handles/kchow.json
Auto-generated PR to register the new warden kchow
@k--chow
=> Register warden kchow

_data/handles/melihdhs.json
Auto-generated PR to register the new warden melihdhs
@melihdhs
=> Register warden melihdhs

_data/handles/0xloscar01.json
Auto-generated PR to register the new warden 0xloscar01
@Loscar1
=> Register warden 0xloscar01

_data/handles/drKay.json
Auto-generated PR to register the new warden drKay
=> Register warden drKay

_data/handles/olegggatttor.json
Auto-generated PR to register the new warden olegggatttor
@olegggatttor
=> Register warden olegggatttor

_data/handles/pheonix_01.json
Auto-generated PR to register the new warden pheonix_01
=> Register warden pheonix_01

_data/handles/rubberduck0x01.json
Auto-generated PR to register the new warden rubberduck0x01
=> Register warden rubberduck0x01

_data/handles/tleuwu.json
Auto-generated PR to register the new warden tleuwu
=> Register warden tleuwu

_data/handles/bones.json
Auto-generated PR to register the new warden bones
@b0nesss
=> Register warden bones

_data/handles/Alekso.json
Auto-generated PR to register the new warden Alekso
@Alekso91
=> Register warden Alekso

_data/handles/passion.json
Auto-generated PR to register the new warden passion
=> Register warden passion

_data/handles/nisargsc.json
Auto-generated PR to register the new warden nisargsc
@nisargsc
=> Register warden nisargsc

_data/handles/mark0v.json
Auto-generated PR to register the new warden mark0v
@cmark0v
=> Register warden mark0v

_data/handles/Osiris.json
Auto-generated PR to register the new warden Osiris
@0xOsiris
=> Register warden Osiris

_data/handles/0x00face.json
Auto-generated PR to register the new warden 0x00face
=> Register warden 0x00face

_data/handles/0x7F2ADC.json
Auto-generated PR to register the new warden 0x7F2ADC
=> Register warden 0x7F2ADC

_data/handles/Zims.json
Auto-generated PR to register the new warden Zims
@Zims
=> Register warden Zims

_data/handles/elderberrylind.json
Auto-generated PR to register the new warden elderberrylind
@ElderberryLind
=> Register warden elderberrylind

_data/handles/ssi91.json
Auto-generated PR to register the new warden ssi91
@ssi91
=> Register warden ssi91

_data/handles/Chiadika99.json
Auto-generated PR to register the new warden Chiadika99
@codetemplar99
=> Register warden Chiadika99

_data/handles/brokenFang0.json
Auto-generated PR to register the new warden brokenFang0
@BrokenFang0
=> Register warden brokenFang0

_data/handles/hackit_bharat.json
Auto-generated PR to register the new warden hackit_bharat
=> Register warden hackit_bharat

_data/handles/FearlessLions.json
This auto-generated PR creates the team FearlessLions
=> Create team FearlessLions

_data/handles/0xSimeon.json
Auto-generated PR to register the new warden 0xSimeon
@0xSimeon
=> Register warden 0xSimeon

_data/handles/fr33rh.json
Auto-generated PR to register the new warden fr33rh
=> Register warden fr33rh

_data/handles/Jasmine95.json
Auto-generated PR to register the new warden Jasmine95
=> Register warden Jasmine95

_data/handles/chudastik.json
Auto-generated PR to register the new warden chudastik
=> Register warden chudastik

_data/handles/djangodg.json
Auto-generated PR to register the new warden djangodg
=> Register warden djangodg

_data/handles/asghaier.json
Auto-generated PR to register the new warden asghaier
@https://github.com/asghaier76
=> Register warden asghaier

_data/handles/0xklh.json
Auto-generated PR to register the new warden 0xklh
=> Register warden 0xklh

_data/handles/Gosho.json
Auto-generated PR to register the new warden Gosho
@grc02
=> Register warden Gosho

_data/handles/AKSLEGION.json
Auto-generated PR to register the new warden AKSLEGION
@AKSLEGION
=> Register warden AKSLEGION

_data/handles/kazan.json
Auto-generated PR to register the new warden kazan
@hoahamho
=> Register warden kazan

_data/handles/karanaroraeth.json
Auto-generated PR to register the new warden karanaroraeth
@karanaroraeth
=> Register warden karanaroraeth

_data/handles/GREY-HAWK-REACH.json
This auto-generated PR modifies the team GREY-HAWK-REACH
The request was made by escrow
=> Edit team GREY-HAWK-REACH

_data/handles/pibu.json
Auto-generated PR to register the new warden pibu
@pbuda
=> Register warden pibu

_data/handles/Chixx.json
Auto-generated PR to register the new warden Chixx
@Chinoiserie1
=> Register warden Chixx

_data/handles/0xStriker.json
Auto-generated PR to register the new warden 0xStriker
=> Register warden 0xStriker

_data/handles/muha66adbi9a9.json
Auto-generated PR to register the new warden muha66adbi9a9
=> Register warden muha66adbi9a9

_data/handles/Arcturus.json
Auto-generated PR to register the new warden Arcturus
=> Register warden Arcturus

_data/handles/tapir.json
Auto-generated PR to register the new warden tapir
@yvtapir
=> Register warden tapir

_data/handles/akhoronko.json
Auto-generated PR to register the new warden akhoronko
@akhoronko
=> Register warden akhoronko

_data/handles/Omik.json
This auto-generated PR updates info for warden Omik
@https://github.com/GibranAkbaromiL
=> Update warden Omik

_data/handles/supersizer0x.json
Auto-generated PR to register the new warden supersizer0x
=> Register warden supersizer0x

_data/handles/Kelvin_eth.json
Auto-generated PR to register the new warden Kelvin_eth
@Kel-vintech
=> Register warden Kelvin_eth

_data/handles/Pablo-Pz.json
Auto-generated PR to register the new warden Pablo-Pz
=> Register warden Pablo-Pz

_data/handles/gin.json
Auto-generated PR to register the new warden gin
=> Register warden gin

_data/handles/Ace.json
Auto-generated PR to register the new warden Ace
@AceVikings
=> Register warden Ace

_data/handles/rover.json
Auto-generated PR to register the new warden rover
=> Register warden rover

_data/handles/web3skid.json
Auto-generated PR to register the new warden web3skid
@web3skid
=> Register warden web3skid

_data/handles/chaosbolt.json
Auto-generated PR to register the new warden chaosbolt
=> Register warden chaosbolt

_data/handles/COSMIC-BEE-REACH.json
This auto-generated PR creates the team COSMIC-BEE-REACH
=> Create team COSMIC-BEE-REACH

_data/handles/J4X.json
Auto-generated PR to register the new warden J4X
@J4X-98
=> Register warden J4X

_data/handles/easylaneof.json
Auto-generated PR to register the new warden easylaneof
=> Register warden easylaneof

_data/handles/0xDemon.json
Auto-generated PR to register the new warden 0xDemon
@Emanueldlvg
=> Register warden 0xDemon

_data/handles/prott00nx.json
Auto-generated PR to register the new warden prott00nx
=> Register warden prott00nx

_data/handles/andanza.json
Auto-generated PR to register the new warden andanza
=> Register warden andanza

_data/handles/psb01.json
Auto-generated PR to register the new warden psb01
=> Register warden psb01

_data/handles/ge6a.json
Auto-generated PR to register the new warden ge6a
=> Register warden ge6a

_data/handles/AjrWum.json
Auto-generated PR to register the new warden AjrWum
@ajrwum
=> Register warden AjrWum

_data/handles/TriWei.json
Auto-generated PR to register the new warden TriWei
=> Register warden TriWei

_data/handles/GKBG.json
This auto-generated PR creates the team GKBG
=> Create team GKBG

_data/handles/bordercut.json
Auto-generated PR to register the new warden bordercut
@0xMitchy
=> Register warden bordercut

_data/handles/0xBlech.json
Auto-generated PR to register the new warden 0xBlech
=> Register warden 0xBlech

_data/handles/yotov721.json
Auto-generated PR to register the new warden yotov721
@Yoto-Yotov
=> Register warden yotov721

_data/handles/stakog.json
Auto-generated PR to register the new warden stakog
@stakog
=> Register warden stakog

_data/handles/ohm.json
This auto-generated PR creates the team ohm
=> Create team ohm

_data/handles/codebreaker.json
Auto-generated PR to register the new warden codebreaker
=> Register warden codebreaker

_data/handles/faingold.json
Auto-generated PR to register the new warden faingold
@maorfaingold
=> Register warden faingold

_data/handles/Black_Box.json
This auto-generated PR creates the team Black_Box
=> Create team Black_Box

_data/handles/taylorfromvncvr.json
Auto-generated PR to register the new warden taylorfromvncvr
@taylorfromvancouver
=> Register warden taylorfromvncvr

_data/handles/the_last_austin.json
Auto-generated PR to register the new warden the_last_austin
@https://github.com/austin-fleming
=> Register warden the_last_austin

_data/handles/carlos_sf_pw.json
Auto-generated PR to register the new warden carlos_sf_pw
=> Register warden carlos_sf_pw

_data/handles/inzinko.json
Auto-generated PR to register the new warden inzinko
=> Register warden inzinko

_data/handles/chainshield.json
Auto-generated PR to register the new warden chainshield
=> Register warden chainshield

_data/handles/0xkr4k3n.json
Auto-generated PR to register the new warden 0xkr4k3n
@joscacgom
=> Register warden 0xkr4k3n

_data/handles/dekumax.json
Auto-generated PR to register the new warden dekumax
@dekumax
=> Register warden dekumax

_data/handles/topoz.json
Auto-generated PR to register the new warden topoz
@qin523
=> Register warden topoz

_data/handles/cerid.json
Auto-generated PR to register the new warden cerid
=> Register warden cerid

_data/handles/HeiXiaZiBTC.json
Auto-generated PR to register the new warden HeiXiaZiBTC
@HeiXiaZiBTC
=> Register warden HeiXiaZiBTC

_data/handles/saga.json
Auto-generated PR to register the new warden saga
=> Register warden saga

_data/handles/lbjyang.json
Auto-generated PR to register the new warden lbjyang
@LBJyang
=> Register warden lbjyang

_data/handles/tabboz.json
Auto-generated PR to register the new warden tabboz
=> Register warden tabboz

_data/handles/yazm.json
Auto-generated PR to register the new warden yazm
=> Register warden yazm

_data/handles/torof.json
Auto-generated PR to register the new warden torof
@Torof
=> Register warden torof

_data/handles/Lena_h.json
Auto-generated PR to register the new warden Lena_h
=> Register warden Lena_h

_data/handles/norush8194.json
Auto-generated PR to register the new warden norush8194
=> Register warden norush8194

_data/handles/rks16.json
Auto-generated PR to register the new warden rks16
=> Register warden rks16

_data/handles/Cyb3rz0n3.json
Auto-generated PR to register the new warden Cyb3rz0n3
=> Register warden Cyb3rz0n3

_data/handles/0xbecco.json
Auto-generated PR to register the new warden 0xbecco
@iBeccoo
=> Register warden 0xbecco

_data/handles/sharingan.json
Auto-generated PR to register the new warden sharingan
@sk-holmes
=> Register warden sharingan

_data/handles/fribas.json
Auto-generated PR to register the new warden fribas
@fribas84
=> Register warden fribas

_data/handles/MD.json
Auto-generated PR to register the new warden MD
=> Register warden MD

_data/handles/Rozzo.json
Auto-generated PR to register the new warden Rozzo
@xRozzo
=> Register warden Rozzo

_data/handles/stevifi.json
Auto-generated PR to register the new warden stevifi
=> Register warden stevifi

_data/handles/0xAkira.json
Auto-generated PR to register the new warden 0xAkira
@0xAkira
=> Register warden 0xAkira

_data/handles/257bits.json
Auto-generated PR to register the new warden 257bits
=> Register warden 257bits

_data/handles/falconhoof.json
Auto-generated PR to register the new warden falconhoof
@Qormatic
=> Register warden falconhoof

_data/handles/cheatc0d3.json
Auto-generated PR to register the new warden cheatc0d3
=> Register warden cheatc0d3

_data/handles/plainshift.json
Help desk request to update payment wallet for the team.
=> Update plainshift.json wallet update

_data/handles/0xSolanum.json
Auto-generated PR to register the new warden 0xSolanum
@Beruf9776
=> Register warden 0xSolanum

_data/handles/kristian57.json
Auto-generated PR to register the new warden kristian57
=> Register warden kristian57

_data/handles/0x0khalifah.json
Auto-generated PR to register the new warden 0x0khalifah
=> Register warden 0x0khalifah

_data/handles/franco22.json
Auto-generated PR to register the new warden franco22
=> Register warden franco22

_data/handles/en0c.json
Auto-generated PR to register the new warden en0c
@en0c-026
=> Register warden en0c

_data/handles/kkkmmmsk.json
Auto-generated PR to register the new warden kkkmmmsk
=> Register warden kkkmmmsk

_data/handles/joesan.json
Auto-generated PR to register the new warden joesan
@joesanOg
=> Register warden joesan

_data/handles/aycozynfada.json
Auto-generated PR to register the new warden aycozynfada
@aycozy
=> Register warden aycozynfada

_data/handles/jonny_web3.json
Auto-generated PR to register the new warden jonny_web3
=> Register warden jonny_web3

_data/handles/huntingbugs.json
Auto-generated PR to register the new warden huntingbugs
=> Register warden huntingbugs

_data/handles/hindsight.json
Auto-generated PR to register the new warden hindsight
=> Register warden hindsight

_data/handles/shaflow2.json
Auto-generated PR to register the new warden shaflow2
=> Register warden shaflow2

_data/handles/steadyman.json
Auto-generated PR to register the new warden steadyman
=> Register warden steadyman

_data/handles/Black_Box_DD.json
This auto-generated PR creates the team Black_Box_DD
=> Create team Black_Box_DD

_data/handles/0xScourgedev.json
Auto-generated PR to register the new warden 0xScourgedev
@ljz3
=> Register warden 0xScourgedev

_data/handles/codejand.json
Auto-generated PR to register the new warden codejand
=> Register warden codejand

_data/handles/kek_ccak256.json
Auto-generated PR to register the new warden kek_ccak256
=> Register warden kek_ccak256

_data/handles/0xdit.json, _data/handles/cybercum.json
Auto-generated PR to register the new warden cybercum
=> Register warden 0xdit

_data/handles/0xtankr.json
Auto-generated PR to register the new warden 0xtankr
=> Register warden 0xtankr

_data/handles/toekneetkc.json
Auto-generated PR to register the new warden toekneetkc
=> Register warden toekneetkc

_data/handles/beescuit.json
Auto-generated PR to register the new warden beescuit
@beescuit
=> Register warden beescuit

_data/handles/Reshy.json
Auto-generated PR to register the new warden Reshy
=> Register warden Reshy

_data/handles/Black_Box_DD.json
This auto-generated PR modifies the team Black_Box_DD
The request was made by ch13fd357r0y3r
=> Edit team Black_Box_DD

_data/handles/k4n3ki.json
Auto-generated PR to register the new warden k4n3ki
@0xk4n3ki
=> Register warden k4n3ki

_data/handles/droptpackets.json
Auto-generated PR to register the new warden droptpackets
=> Register warden droptpackets

_data/handles/paperroast.json
Auto-generated PR to register the new warden paperroast
@paper-roast
=> Register warden paperroast

_data/handles/Alfa.json
Auto-generated PR to register the new warden Alfa
@Alfa11917676
=> Register warden Alfa

_data/handles/yhtyyar.json
Auto-generated PR to register the new warden yhtyyar
=> Register warden yhtyyar

_data/handles/H3is3nb3rg.json
Auto-generated PR to register the new warden H3is3nb3rg
@ Isma589
=> Register warden H3is3nb3rg

_data/handles/perseus.json
Auto-generated PR to register the new warden perseus
@perseus-audit
=> Register warden perseus

_data/handles/kendevi.json
Auto-generated PR to register the new warden kendevi
=> Register warden kendevi

_data/handles/PavelCore.json
Auto-generated PR to register the new warden PavelCore
@pavelcore
=> Register warden PavelCore

_data/handles/eirik.json
Auto-generated PR to register the new warden eirik
=> Register warden eirik

_data/handles/e0d1n.json
Auto-generated PR to register the new warden e0d1n
=> Register warden e0d1n

_data/handles/YowiSec.json
Auto-generated PR to register the new warden YowiSec
@YowiSec
=> Register warden YowiSec

_data/handles/peigan7414.json
Auto-generated PR to register the new warden peigan7414
@PeiGan
=> Register warden peigan7414

_data/handles/TolgaOrion.json
Auto-generated PR to register the new warden TolgaOrion
=> Register warden TolgaOrion

_data/handles/nicetea.json
Auto-generated PR to register the new warden nicetea
=> Register warden nicetea

_data/handles/Stefan-Nikolov.json
Auto-generated PR to register the new warden Stefan-Nikolov
@ stefan-nikolov96
=> Register warden Stefan-Nikolov

_data/handles/yogi.json
Auto-generated PR to register the new warden yogi
=> Register warden yogi

_data/handles/retroactivized.json
Auto-generated PR to register the new warden retroactivized
=> Register warden retroactivized

_data/handles/DuncanDuMond.json
Auto-generated PR to register the new warden DuncanDuMond
@DuncanDuMond
=> Register warden DuncanDuMond

_data/handles/mehmet.json
Auto-generated PR to register the new warden mehmet
=> Register warden mehmet

_data/handles/Isomorphism.json
Auto-generated PR to register the new warden Isomorphism
=> Register warden Isomorphism

_data/handles/Philogicae.json
Reverts code-423n4/code423n4.com#12588
=> Revert "Register warden Philogicae"

_data/handles/FaisalAli.json
Auto-generated PR to register the new warden FaisalAli
@FaisalAli19
=> Register warden FaisalAli

_data/handles/sezio.json
Auto-generated PR to register the new warden sezio
@sergiovks
=> Register warden sezio

_data/handles/MCL-ZK.json
This auto-generated PR creates the team MCL-ZK
=> Create team MCL-ZK

_data/handles/Ghinter.json
Auto-generated PR to register the new warden Ghinter
=> Register warden Ghinter

_data/handles/zkLotus.json
This auto-generated PR creates the team zkLotus
=> Create team zkLotus

_data/handles/SHA_256.json
Auto-generated PR to register the new warden SHA_256
=> Register warden SHA_256

_data/handles/pro9933.json
Auto-generated PR to register the new warden pro9933
=> Register warden pro9933

_data/handles/Nomad.json
Auto-generated PR to register the new warden Nomad
@nNomadddd
=> Register warden Nomad

_data/handles/rufflabs.json
Auto-generated PR to register the new warden rufflabs
@rufflabs
=> Register warden rufflabs

_data/handles/yumsec.json
Auto-generated PR to register the new warden yumsec
@yumsec
=> Register warden yumsec

_data/handles/Boyege.json
Auto-generated PR to register the new warden Boyege
@Boyege
=> Register warden Boyege

_data/handles/PositiveWeb3.json
Auto-generated PR to register the new warden PositiveWeb3
=> Register warden PositiveWeb3

_data/handles/timo.json
Auto-generated PR to register the new warden timo
=> Register warden timo

_data/handles/0x0.json
Auto-generated PR to register the new warden 0x0
@0x0-github
=> Register warden 0x0

_data/handles/Sec_p0x.json
Auto-generated PR to register the new warden Sec_p0x
@piyushimself
=> Register warden Sec_p0x

_data/handles/zmachx.json
Auto-generated PR to register the new warden zmachx
=> Register warden zmachx

_data/handles/nikakhachi.json
Auto-generated PR to register the new warden nikakhachi
@nikakhachi
=> Register warden nikakhachi

_data/handles/rockchun.json
Auto-generated PR to register the new warden rockchun
=> Register warden rockchun

_data/handles/dayoz_.json
Auto-generated PR to register the new warden dayoz_
=> Register warden dayoz_

_data/handles/Fayaz81069.json
Auto-generated PR to register the new warden Fayaz81069
=> Register warden Fayaz81069

_data/handles/Najnomics.json
Auto-generated PR to register the new warden Najnomics
@@Najnomics
=> Register warden Najnomics

_data/handles/jdranpariya.json
Auto-generated PR to register the new warden jdranpariya
=> Register warden jdranpariya

_data/handles/backd00r104.json
Auto-generated PR to register the new warden backd00r104
=> Register warden backd00r104

_data/handles/Bolby.json
Auto-generated PR to register the new warden Bolby
=> Register warden Bolby

_data/handles/Vadimu.json
Auto-generated PR to register the new warden Vadimu
=> Register warden Vadimu

_data/handles/arnauec.json
Auto-generated PR to register the new warden arnauec
@Arnauec
=> Register warden arnauec

_data/handles/1AutumnLeaf.json
Auto-generated PR to register the new warden 1AutumnLeaf
=> Register warden 1AutumnLeaf

_data/handles/karpovpw.json
Auto-generated PR to register the new warden karpovpw
@karpovpw
=> Register warden karpovpw

_data/handles/diempi.json
Auto-generated PR to register the new warden diempi
@diempi
=> Register warden diempi

_data/handles/Rotisary.json
Auto-generated PR to register the new warden Rotisary
@Rotisary
=> Register warden Rotisary

_data/handles/duaoxiao.json
Auto-generated PR to register the new warden duaoxiao
=> Register warden duaoxiao

_data/handles/krot-0025.json
Auto-generated PR to register the new warden krot-0025
@yash-0025
=> Register warden krot-0025

_data/handles/Aksh.json
Auto-generated PR to register the new warden Aksh
@akki0319
=> Register warden Aksh

_data/handles/00decree.json
Auto-generated PR to register the new warden 00decree
@00decree
=> Register warden 00decree

_data/handles/Beosin.json
Auto-generated PR to register the new warden Beosin
=> Register warden Beosin

_data/handles/hkey.json
Auto-generated PR to register the new warden hkey
@hkey0
=> Register warden hkey

_data/handles/maulbeere.json
Auto-generated PR to register the new warden maulbeere
=> Register warden maulbeere

_data/handles/telegin.json
Auto-generated PR to register the new warden telegin
@drinkius
=> Register warden telegin

_data/handles/krystal1s.json
Auto-generated PR to register the new warden krystal1s
=> Register warden krystal1s

_data/handles/caesear.json
Auto-generated PR to register the new warden caesear
@cc
=> Register warden caesear

_data/handles/0xWSeeC.json
Auto-generated PR to register the new warden 0xWSeeC
=> Register warden 0xWSeeC

_data/handles/hennessydylan.json
Auto-generated PR to register the new warden hennessydylan
@hennessydylan
=> Register warden hennessydylan

_data/handles/brb2jz.json
Auto-generated PR to register the new warden brb2jz
=> Register warden brb2jz

_data/handles/hao329527.json
Auto-generated PR to register the new warden hao329527
=> Register warden hao329527

_data/handles/migueldelosrios.json
Auto-generated PR to register the new warden migueldelosrios
@0xSixtySeven
=> Register warden migueldelosrios

_data/handles/gulDozer.json
Auto-generated PR to register the new warden gulDozer
=> Register warden gulDozer

_data/handles/BTinoRi.json
Auto-generated PR to register the new warden BTinoRi
=> Register warden BTinoRi

_data/handles/Xanadu.json
Auto-generated PR to register the new warden Xanadu
@xanaduG
=> Register warden Xanadu

_data/handles/deki.json
Auto-generated PR to register the new warden deki
=> Register warden deki

_data/handles/c4-audit.json
Auto-generated PR to register the new warden c4-audit
=> Register warden c4-audit

_data/handles/kaiser0.json
Auto-generated PR to register the new warden kaiser0
@resaik012
=> Register warden kaiser0

_data/handles/yelax.json
Auto-generated PR to register the new warden yelax
=> Register warden yelax

_data/handles/thebeaneffect.json
Auto-generated PR to register the new warden thebeaneffect
=> Register warden thebeaneffect

_data/handles/Soltho.json
Auto-generated PR to register the new warden Soltho
=> Register warden Soltho

_data/handles/S5.json
This auto-generated PR modifies the team S5
The request was made by geodude
=> Edit team S5

_data/handles/4undRaiser.json
Auto-generated PR to register the new warden 4undRaiser
@4undRaiser
=> Register warden 4undRaiser

_data/handles/dragon.json
Auto-generated PR to register the new warden dragon
=> Register warden dragon

_data/handles/Stormy.json
Auto-generated PR to register the new warden Stormy
=> Register warden Stormy

_data/handles/sugar.json
Auto-generated PR to register the new warden sugar
=> Register warden sugar

_data/handles/CaeraDenoir.json
Auto-generated PR to register the new warden CaeraDenoir
@CaeraDenoir
=> Register warden CaeraDenoir

_data/handles/bahadorgh.json
Auto-generated PR to register the new warden bahadorgh
@bahadorgh
=> Register warden bahadorgh

_data/handles/omnifient.json
Auto-generated PR to register the new warden omnifient
@omnifient
=> Register warden omnifient

_data/handles/kybercheba.json
Auto-generated PR to register the new warden kybercheba
@Wertusser
=> Register warden kybercheba

_data/handles/0xVolcano.json
Auto-generated PR to register the new warden 0xVolcano
=> Register warden 0xVolcano

_data/handles/satya1256.json
Auto-generated PR to register the new warden satya1256
=> Register warden satya1256

_data/handles/Pirate_hunter.json
Auto-generated PR to register the new warden Pirate_hunter
@prince-panwar
=> Register warden Pirate_hunter

_data/handles/0xllimos.json
Auto-generated PR to register the new warden 0xllimos
@albert-llimos
=> Register warden 0xllimos

_data/handles/kelvinaddr.json
Auto-generated PR to register the new warden kelvinaddr
=> Register warden kelvinaddr

_data/handles/t_whynot.json
Auto-generated PR to register the new warden t_whynot
@https://github.com/theresa-whynot
=> Register warden t_whynot

_data/handles/guschi18.json
Auto-generated PR to register the new warden guschi18
=> Register warden guschi18

_data/handles/bdmcbri.json
Auto-generated PR to register the new warden bdmcbri
@bdmcbri
=> Register warden bdmcbri

_data/handles/sqrlfirst.json
Auto-generated PR to register the new warden sqrlfirst
@sqrlfirst
=> Register warden sqrlfirst

_data/handles/zh1x1an1221.json
Auto-generated PR to register the new warden zh1x1an1221
=> Register warden zh1x1an1221

_data/handles/dudecoding998.json
Auto-generated PR to register the new warden dudecoding998
=> Register warden dudecoding998

_data/handles/davirain.json
Auto-generated PR to register the new warden davirain
@DaviRain-Su
=> Register warden davirain

_data/handles/zkrunner.json
Auto-generated PR to register the new warden zkrunner
=> Register warden zkrunner

_data/handles/zkLotus.json
This auto-generated PR modifies the team zkLotus
The request was made by escrow
=> Edit team zkLotus

_data/handles/romfol.json
Auto-generated PR to register the new warden romfol
@romfol
=> Register warden romfol

_data/handles/Ruben.json
Auto-generated PR to register the new warden Ruben
=> Register warden Ruben

_data/handles/zyklotomic.json
Auto-generated PR to register the new warden zyklotomic
=> Register warden zyklotomic

_data/handles/alix40.json
Auto-generated PR to register the new warden alix40
=> Register warden alix40

_data/handles/metin1.json
Auto-generated PR to register the new warden metin1
=> Register warden metin1

_data/handles/zero-idea.json
This auto-generated PR creates the team zero-idea
=> Create team zero-idea

_data/handles/amr9k8.json
Auto-generated PR to register the new warden amr9k8
@amr9k8
=> Register warden amr9k8

_data/handles/probiit.json
Auto-generated PR to register the new warden probiit
@probiit
=> Register warden probiit

_data/handles/merigo.json
Auto-generated PR to register the new warden merigo
=> Register warden merigo

_data/handles/crudiedo.json
Auto-generated PR to register the new warden crudiedo
@crudiedo
=> Register warden crudiedo

_data/handles/ziggyaudit.json
Auto-generated PR to register the new warden ziggyaudit
=> Register warden ziggyaudit

_data/handles/GangsOfBrahmin.json
This auto-generated PR modifies the team GangsOfBrahmin
The request was made by Satyam_Sharma
=> Edit team GangsOfBrahmin

_data/handles/hisganbc1.json
Auto-generated PR to register the new warden hisganbc1
=> Register warden hisganbc1

_data/handles/Eigenvectors.json
This auto-generated PR creates the team Eigenvectors
=> Create team Eigenvectors

_data/handles/uint008.json
Auto-generated PR to register the new warden uint008
=> Register warden uint008

_data/handles/AM.json
This auto-generated PR creates the team AM
=> Create team AM

_data/handles/qiubaoyang520.json
Auto-generated PR to register the new warden qiubaoyang520
=> Register warden qiubaoyang520

_data/handles/jimmysyw.json
Auto-generated PR to register the new warden jimmysyw
=> Register warden jimmysyw

_data/handles/nick0ve.json
Auto-generated PR to register the new warden nick0ve
@nick0ve
=> Register warden nick0ve

_data/handles/kuihua.json
Auto-generated PR to register the new warden kuihua
=> Register warden kuihua

_data/handles/0x6d6164616e.json
Auto-generated PR to register the new warden 0x6d6164616e
=> Register warden 0x6d6164616e

_data/handles/kimchi.json
Auto-generated PR to register the new warden kimchi
=> Register warden kimchi

_data/handles/tjade273.json
Auto-generated PR to register the new warden tjade273
@tjade273
=> Register warden tjade273

_data/handles/COSMIC-BEE-REACH.json
This auto-generated PR modifies the team COSMIC-BEE-REACH
The request was made by 0xarno
=> Edit team COSMIC-BEE-REACH

_data/handles/darkbit.json
Auto-generated PR to register the new warden darkbit
=> Register warden darkbit

_data/handles/Robert.json
Auto-generated PR to register the new warden Robert
@RobertMCForster
=> Register warden Robert

_data/handles/dedo93.json
Auto-generated PR to register the new warden dedo93
=> Register warden dedo93

_data/handles/Arion.json
Auto-generated PR to register the new warden Arion
@0xArion
=> Register warden Arion

_data/handles/VicenteM.json
Auto-generated PR to register the new warden VicenteM
=> Register warden VicenteM

_data/handles/RamenPeople.json
This auto-generated PR creates the team RamenPeople
=> Create team RamenPeople

_data/handles/Rishabh03.json
Auto-generated PR to register the new warden Rishabh03
@RishabhTibrewal
=> Register warden Rishabh03

_data/handles/linuslandin.json
Auto-generated PR to register the new warden linuslandin
=> Register warden linuslandin

_data/handles/mikasa.json
Auto-generated PR to register the new warden mikasa
=> Register warden mikasa

_data/handles/danielng250.json
Auto-generated PR to register the new warden danielng250
@ndtr2000
=> Register warden danielng250

_data/handles/Compez.json
Auto-generated PR to register the new warden Compez
@KambizAsadzadeh
=> Register warden Compez

_data/handles/Kaizuki.json
Auto-generated PR to register the new warden Kaizuki
=> Register warden Kaizuki

_data/handles/stzky.json
Auto-generated PR to register the new warden stzky
=> Register warden stzky

_data/handles/MarcosDaniel.json
Auto-generated PR to register the new warden MarcosDaniel
@marcosdanieltorres
=> Register warden MarcosDaniel

_data/handles/mcbagz.json
Auto-generated PR to register the new warden mcbagz
@mcbagz
=> Register warden mcbagz

_data/handles/qweqweqweasd.json
This auto-generated PR creates the team qweqweqweasd
=> Create team qweqweqweasd

_data/handles/Yostos.json
Auto-generated PR to register the new warden Yostos
=> Register warden Yostos

_data/handles/Collinsoden.json
Auto-generated PR to register the new warden Collinsoden
@Collinsoden22
=> Register warden Collinsoden

_data/handles/Hoax.json
This auto-generated PR creates the team Hoax
=> Create team Hoax

_data/handles/0xEllipticCurve.json
Auto-generated PR to register the new warden 0xEllipticCurve
=> Register warden 0xEllipticCurve

_data/handles/0xjuan.json
Auto-generated PR to register the new warden 0xjuan
@juan.selvan
=> Register warden 0xjuan

_data/handles/oxizo.json
Auto-generated PR to register the new warden oxizo
=> Register warden oxizo

_data/handles/m1nd0v3rfl0w.json
Auto-generated PR to register the new warden m1nd0v3rfl0w
@m1nd0v3rfl0w
=> Register warden m1nd0v3rfl0w

_data/handles/naman1729.json
Auto-generated PR to register the new warden naman1729
=> Register warden naman1729

_data/handles/kahuna99.json
Auto-generated PR to register the new warden kahuna99
@kahuna99
=> Register warden kahuna99

_data/handles/sayaeffify.json
Auto-generated PR to register the new warden sayaeffify
=> Register warden sayaeffify

_data/handles/KHOROAMU.json
Auto-generated PR to register the new warden KHOROAMU
=> Register warden KHOROAMU

_data/handles/matejdb.json
Auto-generated PR to register the new warden matejdb
@matejdrazic
=> Register warden matejdb

_data/handles/yojeff.json
Auto-generated PR to register the new warden yojeff
@jvojeff
=> Register warden yojeff

_data/handles/0xabhay.json
Auto-generated PR to register the new warden 0xabhay
=> Register warden 0xabhay

_data/handles/0xadra101.json
Auto-generated PR to register the new warden 0xadra101
=> Register warden 0xadra101

_data/handles/Fabrisme.json
Auto-generated PR to register the new warden Fabrisme
=> Register warden Fabrisme

_data/handles/0xe4669da.json
Auto-generated PR to register the new warden 0xe4669da
@m-waqas88
=> Register warden 0xe4669da

_data/handles/kat_N.json
Auto-generated PR to register the new warden kat_N
=> Register warden kat_N

_data/handles/caoguojun0.json
Auto-generated PR to register the new warden caoguojun0
@caoguojun0
=> Register warden caoguojun0

_data/handles/achello.json
Auto-generated PR to register the new warden achello
=> Register warden achello

_data/handles/beval.json
Auto-generated PR to register the new warden beval
@beval1
=> Register warden beval

_data/handles/sayedex.json
Auto-generated PR to register the new warden sayedex
@sayedex
=> Register warden sayedex

_data/handles/klonylo.json
Auto-generated PR to register the new warden klonylo
=> Register warden klonylo

_data/handles/5sigma.json
Auto-generated PR to register the new warden 5sigma
=> Register warden 5sigma

_data/handles/0xygyn.json
Auto-generated PR to register the new warden 0xygyn
=> Register warden 0xygyn

_data/handles/DrAngler.json
Auto-generated PR to register the new warden DrAngler
=> Register warden DrAngler

_data/handles/mxuse.json
Auto-generated PR to register the new warden mxuse
=> Register warden mxuse

_data/handles/0xSatyaETH.json
Auto-generated PR to register the new warden 0xSatyaETH
@0xSatyaETH
=> Register warden 0xSatyaETH

_data/handles/R23.json
Auto-generated PR to register the new warden R23
=> Register warden R23

_data/handles/echolinq.json
Auto-generated PR to register the new warden echolinq
@echolinq
=> Register warden echolinq

_data/handles/radiken.json
Auto-generated PR to register the new warden radiken
@radiken
=> Register warden radiken

_data/handles/GtkArjun147.json
Auto-generated PR to register the new warden GtkArjun147
@GTK-ARJUN
=> Register warden GtkArjun147

_data/handles/SilentSecurity.json
This auto-generated PR creates the team SilentSecurity
=> Create team SilentSecurity

_data/handles/saint_gabriel0.json
Auto-generated PR to register the new warden saint_gabriel0
@saintgabriel0
=> Register warden saint_gabriel0

_data/handles/Gizem.json
Auto-generated PR to register the new warden Gizem
@gzfs
=> Register warden Gizem

_data/handles/roleengineer.json
Auto-generated PR to register the new warden roleengineer
@roleengineer
=> Register warden roleengineer

_data/handles/yobiz.json
Auto-generated PR to register the new warden yobiz
=> Register warden yobiz

_data/handles/crack-the-kelp.json
This auto-generated PR creates the team crack-the-kelp
=> Create team crack-the-kelp

_data/handles/33BYTEZZZ.json
This auto-generated PR modifies the team 33BYTEZZZ
The request was made by zuhaibmohd
=> Edit team 33BYTEZZZ

_data/handles/DLIFE_BY.json
Auto-generated PR to register the new warden DLIFE_BY
@LBiyou
=> Register warden DLIFE_BY

_data/handles/amatureApe.json
Auto-generated PR to register the new warden amatureApe
@https://github.com/amatureApe
=> Register warden amatureApe

_data/handles/V.json
Auto-generated PR to register the new warden V
=> Register warden V

_data/handles/_nextgen.json
Auto-generated PR to register the new warden _nextgen
@1isaaclaryea
=> Register warden _nextgen

_data/handles/PositiveSecurity.json
This auto-generated PR creates the team PositiveSecurity
=> Create team PositiveSecurity

_data/handles/0xd24258bb.json
Auto-generated PR to register the new warden 0xd24258bb
=> Register warden 0xd24258bb

_data/handles/y0ng0p3.json
Auto-generated PR to register the new warden y0ng0p3
=> Register warden y0ng0p3

_data/handles/minh20051202.json
Auto-generated PR to register the new warden minh20051202
@minh20051202
=> Register warden minh20051202

_data/handles/AlexMilkov.json
Auto-generated PR to register the new warden AlexMilkov
=> Register warden AlexMilkov

_data/handles/checktheengine.json
Auto-generated PR to register the new warden checktheengine
=> Register warden checktheengine

_data/handles/nicobourbs.json
Auto-generated PR to register the new warden nicobourbs
@nicobourbs
=> Register warden nicobourbs

_data/handles/CRIMSON-RAT-REACH.json
This auto-generated PR modifies the team CRIMSON-RAT-REACH
The request was made by paspe
=> Edit team CRIMSON-RAT-REACH

_data/handles/Linus_.json
Auto-generated PR to register the new warden Linus_
=> Register warden Linus_

_data/handles/PositiveSecurity.json
This auto-generated PR modifies the team PositiveSecurity
The request was made by AndreyBa
=> Edit team PositiveSecurity

_data/bots/SolidInspect.json
Registration for bot SolidInspect.
Description:
I have developed a sophisticated bot named SolidInspect, utilizing Python 3.8 as its programming language. This bot incorporates a single open-source tool, namely the [python-solidity-parser](https://github.com/Consensys/python-solidity-parser) from Consensys.
=> Register bot SolidInspect

_data/handles/10Million.json
Auto-generated PR to register the new warden 10Million
=> Register warden 10Million

_data/handles/0xDestin.json
Auto-generated PR to register the new warden 0xDestin
=> Register warden 0xDestin

_data/handles/bitbattleroyale.json
Auto-generated PR to register the new warden bitbattleroyale
=> Register warden bitbattleroyale

_data/handles/bakwas.json
Auto-generated PR to register the new warden bakwas
=> Register warden bakwas

_data/handles/apool.json
Auto-generated PR to register the new warden apool
=> Register warden apool

_data/handles/zahari3301.json
Auto-generated PR to register the new warden zahari3301
=> Register warden zahari3301

_data/handles/likeTheWind.json
Auto-generated PR to register the new warden likeTheWind
=> Register warden likeTheWind

_data/handles/Gionaimnea.json
Auto-generated PR to register the new warden Gionaimnea
=> Register warden Gionaimnea

_data/handles/0xsaviour_.json
Auto-generated PR to register the new warden 0xsaviour_
=> Register warden 0xsaviour_

_data/handles/Zhezhe.json
Auto-generated PR to register the new warden Zhezhe
@Zhemayel
=> Register warden Zhezhe

_data/handles/0x886699.json
Auto-generated PR to register the new warden 0x886699
=> Register warden 0x886699

_data/handles/beemining.json
Auto-generated PR to register the new warden beemining
=> Register warden beemining

_data/handles/satoshispeedrunner.json
Auto-generated PR to register the new warden satoshispeedrunner
=> Register warden satoshispeedrunner

_data/handles/kingsley.json
Auto-generated PR to register the new warden kingsley
=> Register warden kingsley

_data/handles/gaminggweigladiator.json
Auto-generated PR to register the new warden gaminggweigladiator
=> Register warden gaminggweigladiator

_data/handles/tokentombraider.json
Auto-generated PR to register the new warden tokentombraider
=> Register warden tokentombraider

_data/handles/mikx.json
Auto-generated PR to register the new warden mikx
@cptmikx
=> Register warden mikx

_data/handles/altcoinarcader.json
Auto-generated PR to register the new warden altcoinarcader
=> Register warden altcoinarcader

_data/handles/0xhitman.json
Auto-generated PR to register the new warden 0xhitman
@muhamedyashin
=> Register warden 0xhitman

_data/handles/satoshistrategymaster.json
Auto-generated PR to register the new warden satoshistrategymaster
=> Register warden satoshistrategymaster

_data/handles/kvartum.json
Auto-generated PR to register the new warden kvartum
@kvartum
=> Register warden kvartum

_data/handles/forkforkdog.json
Auto-generated PR to register the new warden forkforkdog
=> Register warden forkforkdog

_data/handles/WildSniper.json
Auto-generated PR to register the new warden WildSniper
=> Register warden WildSniper

_data/handles/Sud0u53r.json
Auto-generated PR to register the new warden Sud0u53r
@Sud0u53r
=> Register warden Sud0u53r

_data/handles/yxcpp1.json
Auto-generated PR to register the new warden yxcpp1
=> Register warden yxcpp1

_data/handles/Damboy.json
Auto-generated PR to register the new warden Damboy
@damboyyy
=> Register warden Damboy

_data/handles/lightw1nd.json
Auto-generated PR to register the new warden lightw1nd
=> Register warden lightw1nd

_data/handles/eLSeR17.json
Auto-generated PR to register the new warden eLSeR17
@eLSeR17
=> Register warden eLSeR17

_data/handles/soulXtendency.json
This auto-generated PR creates the team soulXtendency
=> Create team soulXtendency

_data/handles/ASLANBEK_KUNANBAEV.json
This auto-generated PR creates the team ASLANBEK_KUNANBAEV
=> Create team ASLANBEK_KUNANBAEV

_data/handles/kalikho.json
Auto-generated PR to register the new warden kalikho
=> Register warden kalikho

_data/handles/MirCha.json
Auto-generated PR to register the new warden MirCha
@mgaceanu
=> Register warden MirCha

_data/handles/henryfunction.json
Auto-generated PR to register the new warden henryfunction
@henryfunction
=> Register warden henryfunction

_data/handles/JoeWick.json
Auto-generated PR to register the new warden JoeWick
=> Register warden JoeWick

_data/handles/Rere.json
Auto-generated PR to register the new warden Rere
=> Register warden Rere

_data/handles/GoSlang.json
Auto-generated PR to register the new warden GoSlang
=> Register warden GoSlang

_data/handles/Appsalar.json
Auto-generated PR to register the new warden Appsalar
@Appsalar
=> Register warden Appsalar

_data/handles/fakesm1le.json
Auto-generated PR to register the new warden fakesm1le
@fakesm1le
=> Register warden fakesm1le

_data/handles/cuscak.json
Auto-generated PR to register the new warden cuscak
@cuscak
=> Register warden cuscak

_data/handles/ShubhzDev.json
Auto-generated PR to register the new warden ShubhzDev
=> Register warden ShubhzDev

_data/handles/SadeeqXmosh.json
This auto-generated PR modifies the team SadeeqXmosh
The request was made by Oxsadeeq
=> Edit team SadeeqXmosh

_data/handles/Bobby.json
Auto-generated PR to register the new warden Bobby
=> Register warden Bobby

_data/handles/shuernchua.json
Auto-generated PR to register the new warden shuernchua
@ChuaShuErn
=> Register warden shuernchua

_data/handles/Renascence-Labs.json
This auto-generated PR creates the team Renascence-Labs
=> Create team Renascence-Labs

_data/handles/todorowwww.json
Auto-generated PR to register the new warden todorowwww
=> Register warden todorowwww

_data/handles/batsanov.json
Auto-generated PR to register the new warden batsanov
@batsanov
=> Register warden batsanov

_data/handles/953.json
Auto-generated PR to register the new warden 953
@953
=> Register warden 953

_data/handles/rudolph.json
Auto-generated PR to register the new warden rudolph
@rudolphwang
=> Register warden rudolph

_data/handles/frost.json
Auto-generated PR to register the new warden frost
@frostypeng
=> Register warden frost

_data/handles/t7xdracian.json
Auto-generated PR to register the new warden t7xdracian
@trudransh
=> Register warden t7xdracian

_data/handles/SgtWhiskers.json
Auto-generated PR to register the new warden SgtWhiskers
=> Register warden SgtWhiskers

_data/handles/geodude0.json
Auto-generated PR to register the new warden geodude0
=> Register warden geodude0

_data/handles/jacobheun-test-wc.json
Auto-generated PR to register the new warden jacobheun-test-wc
=> Register warden jacobheun-test-wc

_data/handles/sinewave.json
Auto-generated PR to register the new warden sinewave
=> Register warden sinewave

_data/handles/xyz.json
Auto-generated PR to register the new warden xyz
@gaborbalazseng
=> Register warden xyz

_data/handles/bear246.json
Auto-generated PR to register the new warden bear246
@Dovm
=> Register warden bear246

_data/handles/aodkgkrogrogoovg2o3btivr.json
Auto-generated PR to register the new warden aodkgkrogrogoovg2o3btivr
=> Register warden aodkgkrogrogoovg2o3btivr

_data/handles/BlackOp.json
Auto-generated PR to register the new warden BlackOp
=> Register warden BlackOp

_data/handles/prankster.json
Auto-generated PR to register the new warden prankster
=> Register warden prankster

_data/handles/pizzaops.json
Auto-generated PR to register the new warden pizzaops
=> Register warden pizzaops

_data/handles/andywer.json
Auto-generated PR to register the new warden andywer
@andywer
=> Register warden andywer

_data/handles/xndrshea.json
Auto-generated PR to register the new warden xndrshea
=> Register warden xndrshea

_data/handles/Plair.json
Auto-generated PR to register the new warden Plair
@Plairfx
=> Register warden Plair

_data/handles/pwnstar.json
Auto-generated PR to register the new warden pwnstar
=> Register warden pwnstar

_data/handles/raspberryllama.json
This auto-generated PR modifies the team raspberryllama
The request was made by llamatest
=> Edit team raspberryllama

_data/handles/HermitJediMaster.json
Auto-generated PR to register the new warden HermitJediMaster
@Hades97
=> Register warden HermitJediMaster

_data/handles/smartoshi.json
Auto-generated PR to register the new warden smartoshi
@smartoshi
=> Register warden smartoshi

_data/handles/merunas.json
Auto-generated PR to register the new warden merunas
@merlox
=> Register warden merunas

_data/handles/LilCaera.json
This auto-generated PR creates the team LilCaera
=> Create team LilCaera

_data/handles/neeena.json
Auto-generated PR to register the new warden neeena
=> Register warden neeena

_data/handles/AuditorPraise.json
Auto-generated PR to register the new warden AuditorPraise
@auditorpraise
=> Register warden AuditorPraise

_data/handles/tadashi0x.json
Auto-generated PR to register the new warden tadashi0x
=> Register warden tadashi0x

_data/handles/distbit.json
Auto-generated PR to register the new warden distbit
@distbit0
=> Register warden distbit

_data/handles/0xufuk.json
Auto-generated PR to register the new warden 0xufuk
@0xufuk
=> Register warden 0xufuk

_data/handles/Akali.json
Auto-generated PR to register the new warden Akali
=> Register warden Akali

_data/handles/0xJaeger.json
Auto-generated PR to register the new warden 0xJaeger
@https://github.com/0xJaeger
=> Register warden 0xJaeger

_data/handles/Demirev.json
Auto-generated PR to register the new warden Demirev
@georgidemirev
=> Register warden Demirev

_data/handles/murluki.json
Auto-generated PR to register the new warden murluki
@murluki
=> Register warden murluki

_data/handles/nayan.json
Auto-generated PR to register the new warden nayan
@0xnayan
=> Register warden nayan

_data/handles/G-man.json
Auto-generated PR to register the new warden G-man
=> Register warden G-man

_data/handles/cloud_99.json
Auto-generated PR to register the new warden cloud_99
=> Register warden cloud_99

_data/handles/magicspluge.json
Auto-generated PR to register the new warden magicspluge
=> Register warden magicspluge

_data/handles/Sakar.json
Auto-generated PR to register the new warden Sakar
@sakarkc2122
=> Register warden Sakar

_data/handles/DjinnSecurity.json
Auto-generated PR to register the new warden DjinnSecurity
=> Register warden DjinnSecurity

_data/handles/0xaltego.json
Auto-generated PR to register the new warden 0xaltego
=> Register warden 0xaltego

_data/handles/timahovichivan.json
Auto-generated PR to register the new warden timahovichivan
=> Register warden timahovichivan

_data/handles/zeroqn.json
Auto-generated PR to register the new warden zeroqn
@zeroqn
=> Register warden zeroqn

_data/handles/TechieTeee.json
Auto-generated PR to register the new warden TechieTeee
@TechieTeee
=> Register warden TechieTeee

_data/handles/0xlucky.json
Auto-generated PR to register the new warden 0xlucky
=> Register warden 0xlucky

_data/handles/0xcypheron.json
Auto-generated PR to register the new warden 0xcypheron
@DavidIfebueme
=> Register warden 0xcypheron

_data/handles/CryptoProtagonist.json
Auto-generated PR to register the new warden CryptoProtagonist
=> Register warden CryptoProtagonist

_data/handles/Wolfy6848.json
Auto-generated PR to register the new warden Wolfy6848
@Wolfy6848
=> Register warden Wolfy6848

_data/handles/sergeantmajor67.json
Auto-generated PR to register the new warden sergeantmajor67
=> Register warden sergeantmajor67

_data/handles/EricCA.json
Auto-generated PR to register the new warden EricCA
=> Register warden EricCA

_data/handles/zero.json
Auto-generated PR to register the new warden zero
=> Register warden zero

_data/handles/vizks.json
Auto-generated PR to register the new warden vizks
=> Register warden vizks

_data/handles/HSP.json
Auto-generated PR to register the new warden HSP
=> Register warden HSP

_data/handles/asherlewis88.json
Auto-generated PR to register the new warden asherlewis88
@https://github.com/asherlewis88
=> Register warden asherlewis88

_data/handles/umarabox.json
Auto-generated PR to register the new warden umarabox
@umarrg
=> Register warden umarabox

_data/handles/1X1.json
Auto-generated PR to register the new warden 1X1
=> Register warden 1X1

_data/handles/CosmicDust.json
Auto-generated PR to register the new warden CosmicDust
=> Register warden CosmicDust

_data/handles/lilizhu.json
Auto-generated PR to register the new warden lilizhu
=> Register warden lilizhu

_data/handles/prakash1381.json
Auto-generated PR to register the new warden prakash1381
=> Register warden prakash1381

_data/handles/demirtasarkinbaris.json
Auto-generated PR to register the new warden demirtasarkinbaris
@demirtasarkinbaris
=> Register warden demirtasarkinbaris

_data/handles/soaphunter9993.json
Auto-generated PR to register the new warden soaphunter9993
=> Register warden soaphunter9993

_data/handles/OffsideLabs.json
This auto-generated PR modifies the team OffsideLabs
The request was made by ronnyx2017
=> Edit team OffsideLabs

_data/handles/Helio.json
Auto-generated PR to register the new warden Helio
=> Register warden Helio

_data/handles/Xeno.json
Auto-generated PR to register the new warden Xeno
=> Register warden Xeno

_data/handles/satoshiseeker.json
Auto-generated PR to register the new warden satoshiseeker
=> Register warden satoshiseeker

_data/handles/igbinosuneric.json
Auto-generated PR to register the new warden igbinosuneric
=> Register warden igbinosuneric

_data/handles/FastChecker.json
Auto-generated PR to register the new warden FastChecker
@ChrisChan
=> Register warden FastChecker

_data/handles/classism.json
Auto-generated PR to register the new warden classism
=> Register warden classism

_data/handles/scoffield.json
Auto-generated PR to register the new warden scoffield
=> Register warden scoffield

_data/handles/0xDenisMasesi.json
Auto-generated PR to register the new warden 0xDenisMasesi
=> Register warden 0xDenisMasesi

_data/handles/PsychedelicSage.json
Auto-generated PR to register the new warden PsychedelicSage
=> Register warden PsychedelicSage

_data/handles/vn73.json
Auto-generated PR to register the new warden vn73
=> Register warden vn73

_data/handles/gafram.json
Auto-generated PR to register the new warden gafram
@gafram
=> Register warden gafram

_data/handles/SpaceCowboy.json
Auto-generated PR to register the new warden SpaceCowboy
=> Register warden SpaceCowboy

_data/handles/tokentetristitan.json
Auto-generated PR to register the new warden tokentetristitan
=> Register warden tokentetristitan

_data/handles/zegarcao.json
Auto-generated PR to register the new warden zegarcao
@zeGarcao
=> Register warden zegarcao

_data/handles/santiellena.json
Auto-generated PR to register the new warden santiellena
@santiellena
=> Register warden santiellena

_data/handles/chainchief.json
Auto-generated PR to register the new warden chainchief
=> Register warden chainchief

_data/handles/0xphi.json
Auto-generated PR to register the new warden 0xphi
=> Register warden 0xphi

_data/handles/chainchas3r.json
Auto-generated PR to register the new warden chainchas3r
=> Register warden chainchas3r

_data/handles/sajeevan_58356.json
Auto-generated PR to register the new warden sajeevan_58356
@sajeevangeto
=> Register warden sajeevan_58356

_data/handles/Bustii.json
Auto-generated PR to register the new warden Bustii
@https://github.com/Bustii
=> Register warden Bustii

_data/handles/protocolpaladin.json
Auto-generated PR to register the new warden protocolpaladin
=> Register warden protocolpaladin

_data/handles/milendch.json
Auto-generated PR to register the new warden milendch
=> Register warden milendch

_data/handles/tokentameer.json
Auto-generated PR to register the new warden tokentameer
=> Register warden tokentameer

_data/handles/marshalfg.json
Auto-generated PR to register the new warden marshalfg
=> Register warden marshalfg

_data/handles/Sheron.json
Auto-generated PR to register the new warden Sheron
=> Register warden Sheron

_data/handles/kdream.json
Auto-generated PR to register the new warden kdream
=> Register warden kdream

_data/handles/gsofter.json
Auto-generated PR to register the new warden gsofter
@gsofter
=> Register warden gsofter

_data/handles/KryptoS1M.json
Auto-generated PR to register the new warden KryptoS1M
=> Register warden KryptoS1M

_data/handles/Berring.json
Auto-generated PR to register the new warden Berring
@https://github.com/Berringt
=> Register warden Berring

_data/handles/oshioke_salaki.json
Auto-generated PR to register the new warden oshioke_salaki
@Oshioke-Salaki
=> Register warden oshioke_salaki

_data/handles/sirthrall.json
Auto-generated PR to register the new warden sirthrall
@Sirthrall
=> Register warden sirthrall

_data/handles/veoquynhs.json
Auto-generated PR to register the new warden veoquynhs
@veoquynhs
=> Register warden veoquynhs

_data/handles/credence0x.json
Auto-generated PR to register the new warden credence0x
@credence0x
=> Register warden credence0x

_data/handles/idk.json
Auto-generated PR to register the new warden idk
=> Register warden idk
