- _data/handles/YusSecurity.json
This auto-generated PR modifies the team YusSecurity
The request was made by flacko
> Edit team YusSecurity

- _data/handles/forgebyola.json
Auto-generated PR to register the new warden forgebyola
@Unknownblackman
> Register warden forgebyola

- _data/handles/kocohira.json
Auto-generated PR to register the new warden kocohira
@kocohira
> Register warden kocohira

- _data/handles/CryptoDarkhorse.json
Auto-generated PR to register the new warden CryptoDarkhorse
> Register warden CryptoDarkhorse

- _data/handles/cingciripit.json
Auto-generated PR to register the new warden cingciripit
> Register warden cingciripit

- _data/handles/Eraico.json
Auto-generated PR to register the new warden Eraico
> Register warden Eraico

- _data/handles/d1g1taldynamo.json
Auto-generated PR to register the new warden d1g1taldynamo
> Register warden d1g1taldynamo

- _data/handles/erosjohn.json
Auto-generated PR to register the new warden erosjohn
@erosjohn
> Register warden erosjohn

- _data/handles/altcoinacee.json
Auto-generated PR to register the new warden altcoinacee
> Register warden altcoinacee

- _data/handles/thebirdeye.json
Auto-generated PR to register the new warden thebirdeye
> Register warden thebirdeye

- _data/handles/dwardu.json
Auto-generated PR to register the new warden dwardu
> Register warden dwardu

- _data/handles/Soliditors.json
This auto-generated PR creates the team Soliditors
> Create team Soliditors

- _data/handles/furkan_0908.json
Auto-generated PR to register the new warden furkan_0908
> Register warden furkan_0908

- _data/handles/azduR_nsfw.json
Auto-generated PR to register the new warden azduR_nsfw
> Register warden azduR_nsfw

- _data/handles/miaowu.json
Auto-generated PR to register the new warden miaowu
@miaowu
> Register warden miaowu

- _data/handles/0xwhisperingwoods.json
Auto-generated PR to register the new warden 0xwhisperingwoods
@frankomosh
> Register warden 0xwhisperingwoods

- _data/handles/0xDazai.json
Auto-generated PR to register the new warden 0xDazai
> Register warden 0xDazai

- _data/handles/general_003.json
Auto-generated PR to register the new warden general_003
> Register warden general_003

- _data/handles/Trupti1801.json
Auto-generated PR to register the new warden Trupti1801
> Register warden Trupti1801

- _data/handles/ls_toast.json
Auto-generated PR to register the new warden ls_toast
> Register warden ls_toast

- _data/handles/opposingmonkey.json
Auto-generated PR to register the new warden opposingmonkey
> Register warden opposingmonkey

- _data/handles/petel3.json
Auto-generated PR to register the new warden petel3
@petel3
> Register warden petel3

- _data/handles/Honour.json
Auto-generated PR to register the new warden Honour
@Honour_d_dev
> Register warden Honour

- _data/handles/aemil.json
Auto-generated PR to register the new warden aemil
> Register warden aemil

- _data/handles/flyzero.json
Auto-generated PR to register the new warden flyzero
> Register warden flyzero

- _data/handles/meatdance.json
Auto-generated PR to register the new warden meatdance
> Register warden meatdance

- _data/handles/Knight_Crypto.json
Auto-generated PR to register the new warden Knight_Crypto
> Register warden Knight_Crypto

- _data/handles/sorcererstellar.json
Auto-generated PR to register the new warden sorcererstellar
> Register warden sorcererstellar

- _data/handles/lanyiyrt.json
Auto-generated PR to register the new warden lanyiyrt
> Register warden lanyiyrt

- _data/handles/ledgerluminary.json
Auto-generated PR to register the new warden ledgerluminary
> Register warden ledgerluminary

- _data/handles/pbg6751.json
Auto-generated PR to register the new warden pbg6751
> Register warden pbg6751

- _data/handles/LedgerLegend.json
Auto-generated PR to register the new warden LedgerLegend
> Register warden LedgerLegend

- _data/handles/vikramaditya0.json
Auto-generated PR to register the new warden vikramaditya0
> Register warden vikramaditya0

- _data/handles/ChainCharmer.json
Auto-generated PR to register the new warden ChainCharmer
> Register warden ChainCharmer

- _data/handles/windaeolus.json
Auto-generated PR to register the new warden windaeolus
@JuneLXD
> Register warden windaeolus

- _data/handles/TokenTitan.json
Auto-generated PR to register the new warden TokenTitan
> Register warden TokenTitan

- _data/handles/usergg.json
Auto-generated PR to register the new warden usergg
> Register warden usergg

- _data/handles/nEkToSAN.json
Auto-generated PR to register the new warden nEkToSAN
> Register warden nEkToSAN

- _data/handles/puffdood.json
Auto-generated PR to register the new warden puffdood
@puffdoo
> Register warden puffdood

- _data/handles/0XHAWRE.json
Auto-generated PR to register the new warden 0XHAWRE
@https://github.com/Hafxhak
> Register warden 0XHAWRE

- _data/handles/nith567.json
Auto-generated PR to register the new warden nith567
@Nith567
> Register warden nith567

- _data/handles/GoldenGryphon.json
Auto-generated PR to register the new warden GoldenGryphon
> Register warden GoldenGryphon

- _data/handles/RedBerry.json
Auto-generated PR to register the new warden RedBerry
> Register warden RedBerry

- _data/handles/cdmorg9430.json
Auto-generated PR to register the new warden cdmorg9430
> Register warden cdmorg9430

- _data/handles/michaeljones.json
Auto-generated PR to register the new warden michaeljones
> Register warden michaeljones

- _data/handles/milamber97.json
Auto-generated PR to register the new warden milamber97
> Register warden milamber97

- _data/handles/NoodleArms.json
Auto-generated PR to register the new warden NoodleArms
> Register warden NoodleArms

- _data/handles/Raaga.json
Auto-generated PR to register the new warden Raaga
> Register warden Raaga

- _data/handles/Dev-Izu.json
Auto-generated PR to register the new warden Dev-Izu
@IzuKripto
> Register warden Dev-Izu

- _data/handles/MysticOracle.json
Auto-generated PR to register the new warden MysticOracle
> Register warden MysticOracle

- _data/handles/QuasarQuest.json
Auto-generated PR to register the new warden QuasarQuest
> Register warden QuasarQuest

- _data/handles/air_0x.json
Auto-generated PR to register the new warden air_0x
> Register warden air_0x

- _data/handles/ZenMaster.json
Auto-generated PR to register the new warden ZenMaster
> Register warden ZenMaster

- _data/handles/solosaber.json
Auto-generated PR to register the new warden solosaber
> Register warden solosaber

- _data/handles/nkbkd.json
Auto-generated PR to register the new warden nkbkd
@baahkusi
> Register warden nkbkd

- _data/handles/ProtocolPriest.json
Auto-generated PR to register the new warden ProtocolPriest
> Register warden ProtocolPriest

- _data/handles/cryptocontroller.json
Auto-generated PR to register the new warden cryptocontroller
> Register warden cryptocontroller

- _data/handles/HashHerald.json
Auto-generated PR to register the new warden HashHerald
> Register warden HashHerald

- _data/handles/DeFiDevotee.json
Auto-generated PR to register the new warden DeFiDevotee
> Register warden DeFiDevotee

- _data/handles/digitalduk3.json
Auto-generated PR to register the new warden digitalduk3
> Register warden digitalduk3

- _data/handles/Auditing_Lions.json
This auto-generated PR modifies the team Auditing_Lions
The request was made by dyoff
> Edit team Auditing_Lions

- _data/handles/Raphina.json
Auto-generated PR to register the new warden Raphina
> Register warden Raphina

- _data/handles/elitwo007.json
Auto-generated PR to register the new warden elitwo007
> Register warden elitwo007

- _data/handles/raquelangels.json
Auto-generated PR to register the new warden raquelangels
> Register warden raquelangels

- _data/handles/h01f3.json
Auto-generated PR to register the new warden h01f3
@Jacsonx
> Register warden h01f3

- _data/handles/memforvik.json
Auto-generated PR to register the new warden memforvik
> Register warden memforvik

- _data/handles/Wnati.json
Auto-generated PR to register the new warden Wnati
> Register warden Wnati

- _data/handles/GonCer.json
Auto-generated PR to register the new warden GonCer
@goncer
> Register warden GonCer

- _data/handles/Belizard.json
Auto-generated PR to register the new warden Belizard
> Register warden Belizard

- _data/handles/YouCrossTheLineAlfie.json
Auto-generated PR to register the new warden YouCrossTheLineAlfie
> Register warden YouCrossTheLineAlfie

- _data/handles/MoonWalker.json
Auto-generated PR to register the new warden MoonWalker
> Register warden MoonWalker

- _data/handles/st0yanov.json
Auto-generated PR to register the new warden st0yanov
> Register warden st0yanov

- _data/handles/Marcelinav.json
Auto-generated PR to register the new warden Marcelinav
> Register warden Marcelinav

- _data/handles/bidxor.json
Auto-generated PR to register the new warden bidxor
> Register warden bidxor

- _data/handles/manolitocodeina.json
Auto-generated PR to register the new warden manolitocodeina
> Register warden manolitocodeina

- _data/handles/Mahmud.json
Auto-generated PR to register the new warden Mahmud
@mahmudoloyede
> Register warden Mahmud

- _data/handles/zhangninghai.json
Auto-generated PR to register the new warden zhangninghai
@zhangninghai
> Register warden zhangninghai

- _data/handles/tijanisylla.json
Auto-generated PR to register the new warden tijanisylla
@tijanisylla
> Register warden tijanisylla

- _data/handles/fritzsima.json
Auto-generated PR to register the new warden fritzsima
@fritzsima
> Register warden fritzsima

- _data/handles/HY.json
Auto-generated PR to register the new warden HY
@roderickli0626
> Register warden HY

- _data/handles/bongoslav.json
Auto-generated PR to register the new warden bongoslav
@bongoslav
> Register warden bongoslav

- _data/handles/ic3.json
Auto-generated PR to register the new warden ic3
> Register warden ic3

- _data/handles/QuantumWitch.json
Auto-generated PR to register the new warden QuantumWitch
> Register warden QuantumWitch

- _data/handles/ChainNya.json
Auto-generated PR to register the new warden ChainNya
> Register warden ChainNya

- _data/handles/EternalEmpress.json
Auto-generated PR to register the new warden EternalEmpress
> Register warden EternalEmpress

- _data/handles/sh286.json
Auto-generated PR to register the new warden sh286
> Register warden sh286

- _data/handles/yvuchev.json
Auto-generated PR to register the new warden yvuchev
@YordanVuchev
> Register warden yvuchev

- _data/handles/Yier.json
Auto-generated PR to register the new warden Yier
> Register warden Yier

- _data/handles/stefanoz45.json
Auto-generated PR to register the new warden stefanoz45
> Register warden stefanoz45

- _data/handles/Kita.json
Auto-generated PR to register the new warden Kita
> Register warden Kita

- _data/handles/Fulaker.json
Auto-generated PR to register the new warden Fulaker
> Register warden Fulaker

- _data/handles/0xliberato.json
Auto-generated PR to register the new warden 0xliberato
> Register warden 0xliberato

- _data/handles/alkrrrrp.json
Auto-generated PR to register the new warden alkrrrrp
> Register warden alkrrrrp

- _data/handles/tekkac.json
Auto-generated PR to register the new warden tekkac
> Register warden tekkac

- _data/handles/RadiantReaper.json
Auto-generated PR to register the new warden RadiantReaper
> Register warden RadiantReaper

- _data/handles/MusicMiss.json
Auto-generated PR to register the new warden MusicMiss
> Register warden MusicMiss

- _data/handles/LaughingGuru.json
Auto-generated PR to register the new warden LaughingGuru
> Register warden LaughingGuru

- _data/handles/BitBuddy.json
Auto-generated PR to register the new warden BitBuddy
> Register warden BitBuddy

- _data/handles/adeen.json
Auto-generated PR to register the new warden adeen
> Register warden adeen

- _data/handles/Parley.json
Auto-generated PR to register the new warden Parley
> Register warden Parley

- _data/handles/ya3raj.json
Auto-generated PR to register the new warden ya3raj
@Yamaraj-aryan
> Register warden ya3raj

- _data/handles/Wall-d.json
This auto-generated PR creates the team Wall-d
> Create team Wall-d

- _data/handles/Test.json
This auto-generated PR creates the team Test
> Create team Test

- _data/handles/Billy_Parallel.json
Auto-generated PR to register the new warden Billy_Parallel
@billyz9611
> Register warden Billy_Parallel

- _data/handles/Smoothin.json
Auto-generated PR to register the new warden Smoothin
> Register warden Smoothin

- _data/handles/PrivateWolf.json
Auto-generated PR to register the new warden PrivateWolf
> Register warden PrivateWolf

- _data/handles/lindion5888.json
Auto-generated PR to register the new warden lindion5888
> Register warden lindion5888

- _data/handles/hodlheroa.json
Auto-generated PR to register the new warden hodlheroa
> Register warden hodlheroa

- _data/handles/CoolBoy.json
Auto-generated PR to register the new warden CoolBoy
> Register warden CoolBoy

- _data/handles/Oxonomy.json
Auto-generated PR to register the new warden Oxonomy
> Register warden Oxonomy

- _data/handles/Yekovannol.json
Auto-generated PR to register the new warden Yekovannol
> Register warden Yekovannol

- _data/handles/lod1n.json
Auto-generated PR to register the new warden lod1n
@lod1n
> Register warden lod1n

- _data/handles/HolographicHero.json
Auto-generated PR to register the new warden HolographicHero
> Register warden HolographicHero

- _data/handles/zhyn.json
Auto-generated PR to register the new warden zhyn
@zhyn-sphere
> Register warden zhyn

- _data/handles/0xfr4n.json
Auto-generated PR to register the new warden 0xfr4n
> Register warden 0xfr4n

- _data/handles/ade1.json
Auto-generated PR to register the new warden ade1
@adelibntarek
> Register warden ade1

- _data/handles/Cleric.json
Auto-generated PR to register the new warden Cleric
> Register warden Cleric

- _data/handles/morenoelizabeth.json
Auto-generated PR to register the new warden morenoelizabeth
> Register warden morenoelizabeth

- _data/handles/Crucifery.json
Auto-generated PR to register the new warden Crucifery
> Register warden Crucifery

- _data/handles/crypt0crusader.json
Auto-generated PR to register the new warden crypt0crusader
> Register warden crypt0crusader

- _data/handles/Zelleyd.json
Auto-generated PR to register the new warden Zelleyd
> Register warden Zelleyd

- _data/handles/Xanang.json
Auto-generated PR to register the new warden Xanang
> Register warden Xanang

- _data/handles/minimuminfluence.json
Auto-generated PR to register the new warden minimuminfluence
> Register warden minimuminfluence

- _data/handles/Blank_Space.json
This auto-generated PR creates the team Blank_Space
> Create team Blank_Space

- _data/handles/Eshlarnan.json
Auto-generated PR to register the new warden Eshlarnan
> Register warden Eshlarnan

- _data/handles/roguereggiant.json
Auto-generated PR to register the new warden roguereggiant
@z5pmV!BR5uBq6BD
> Register warden roguereggiant

- _data/handles/gogolevdms.json
Auto-generated PR to register the new warden gogolevdms
@gogolevdms
> Register warden gogolevdms

- _data/handles/3n0ch.json
Auto-generated PR to register the new warden 3n0ch
> Register warden 3n0ch

- _data/handles/Ongan.json
Auto-generated PR to register the new warden Ongan
> Register warden Ongan

- _data/handles/hashhhunter.json
Auto-generated PR to register the new warden hashhhunter
> Register warden hashhhunter

- _data/handles/Pevan.json
Auto-generated PR to register the new warden Pevan
> Register warden Pevan

- _data/handles/isadoraolgsgq.json
Auto-generated PR to register the new warden isadoraolgsgq
> Register warden isadoraolgsgq

- _data/handles/digitald1sciple.json
Auto-generated PR to register the new warden digitald1sciple
> Register warden digitald1sciple

- _data/handles/Nyxaris.json
Auto-generated PR to register the new warden Nyxaris
@olaoyesalem
> Register warden Nyxaris

- _data/handles/Simex91.json
Auto-generated PR to register the new warden Simex91
@lsqrl
> Register warden Simex91

- _data/handles/IceQueen.json
Auto-generated PR to register the new warden IceQueen
> Register warden IceQueen

- _data/handles/Hinartz.json
Auto-generated PR to register the new warden Hinartz
> Register warden Hinartz

- _data/handles/WittyWarlock.json
Auto-generated PR to register the new warden WittyWarlock
> Register warden WittyWarlock

- _data/handles/ducanh2706.json
Auto-generated PR to register the new warden ducanh2706
@ducanh2706
> Register warden ducanh2706

- _data/handles/Leo50.json
Auto-generated PR to register the new warden Leo50
> Register warden Leo50

- _data/handles/Stefanov.json
Auto-generated PR to register the new warden Stefanov
> Register warden Stefanov

- _data/handles/vinnienndfcm.json
Auto-generated PR to register the new warden vinnienndfcm
> Register warden vinnienndfcm

- _data/handles/aarav1656.json
Auto-generated PR to register the new warden aarav1656
> Register warden aarav1656

- _data/handles/soliditywala.json
Auto-generated PR to register the new warden soliditywala
> Register warden soliditywala

- _data/handles/ShadowNinja.json
Auto-generated PR to register the new warden ShadowNinja
> Register warden ShadowNinja

- _data/handles/kstoyanov-97.json
Auto-generated PR to register the new warden kstoyanov-97
> Register warden kstoyanov-97

- _data/handles/Skaanet.json
Auto-generated PR to register the new warden Skaanet
> Register warden Skaanet

- _data/handles/kumb1d1pm.json
Auto-generated PR to register the new warden kumb1d1pm
> Register warden kumb1d1pm

- _data/handles/PedroZurdo.json
This auto-generated PR creates the team PedroZurdo
> Create team PedroZurdo

- _data/handles/hero007.json
Auto-generated PR to register the new warden hero007
> Register warden hero007

- _data/handles/nzlatev7.json
Auto-generated PR to register the new warden nzlatev7
@nzlatev7
> Register warden nzlatev7

- _data/handles/pynschon.json
Auto-generated PR to register the new warden pynschon
> Register warden pynschon

- _data/handles/pa6kuda.json
Auto-generated PR to register the new warden pa6kuda
> Register warden pa6kuda

- _data/handles/sp4rk.json
Auto-generated PR to register the new warden sp4rk
> Register warden sp4rk

- _data/handles/Kratosssss.json
Auto-generated PR to register the new warden Kratosssss
> Register warden Kratosssss

- _data/handles/Shahroz.json
Auto-generated PR to register the new warden Shahroz
> Register warden Shahroz

- _data/handles/defi_wind.json
Auto-generated PR to register the new warden defi_wind
@manoj9april
> Register warden defi_wind

- _data/handles/Aujara.json
Auto-generated PR to register the new warden Aujara
> Register warden Aujara

- _data/handles/cudo.json
Auto-generated PR to register the new warden cudo
> Register warden cudo

- _data/handles/analyzer_alpha7.json
Auto-generated PR to register the new warden analyzer_alpha7
@analyzer_alpha7
> Register warden analyzer_alpha7

- _data/handles/karlos.json
Auto-generated PR to register the new warden karlos
@jackalkarlos
> Register warden karlos

- _data/handles/ibonomo.json
Auto-generated PR to register the new warden ibonomo
> Register warden ibonomo

- _data/handles/C1rdan.json
Auto-generated PR to register the new warden C1rdan
@C1rdanTheShipwright
> Register warden C1rdan

- _data/handles/Jade.json
Auto-generated PR to register the new warden Jade
> Register warden Jade

- _data/handles/FrizTheGamer.json
Auto-generated PR to register the new warden FrizTheGamer
> Register warden FrizTheGamer

- _data/handles/Audit_Avengers.json
- _data/handles/BLACK-PANDA-REACH.json
- _data/handles/Extropy.json
- _data/handles/Nethermind.json
Re-add the teams that were deleted [here](<https://github.com/code-423n4/code423n4.com/pull/14660/files>), [here](<https://github.com/code-423n4/code423n4.com/pull/14651/files>), [here](<https://github.com/code-423n4/code423n4.com/pull/14657/files>), and [here](<https://github.com/code-423n4/code423n4.com/pull/14016/files>)
> recover deleted teams

- _data/handles/PuzzledPenguin.json
Auto-generated PR to register the new warden PuzzledPenguin
> Register warden PuzzledPenguin

- _data/handles/EtherealEagle.json
Auto-generated PR to register the new warden EtherealEagle
> Register warden EtherealEagle

- _data/handles/0xLuckyLuke.json
Auto-generated PR to register the new warden 0xLuckyLuke
> Register warden 0xLuckyLuke

- _data/handles/lantis1ran.json
Auto-generated PR to register the new warden lantis1ran
> Register warden lantis1ran

- _data/handles/abdessalem.json
Auto-generated PR to register the new warden abdessalem
@abdessalem-code
> Register warden abdessalem

- _data/handles/blackdynamit3.json
Auto-generated PR to register the new warden blackdynamit3
> Register warden blackdynamit3

- _data/handles/am0o0.json
Auto-generated PR to register the new warden am0o0
> Register warden am0o0

- _data/handles/0xpoor4ever.json
Auto-generated PR to register the new warden 0xpoor4ever
> Register warden 0xpoor4ever

- _data/handles/avinashbhagat.json
Auto-generated PR to register the new warden avinashbhagat
@avi0477
> Register warden avinashbhagat

- _data/handles/LipeTuga.json
Auto-generated PR to register the new warden LipeTuga
> Register warden LipeTuga

- _data/handles/victormerino.json
Auto-generated PR to register the new warden victormerino
@victormer
> Register warden victormerino

- _data/handles/xploeed.json
Auto-generated PR to register the new warden xploeed
> Register warden xploeed

- _data/handles/consolexyz.json
Auto-generated PR to register the new warden consolexyz
@consolexyz
> Register warden consolexyz

- _data/handles/SeveritySquad.json
This auto-generated PR modifies the team SeveritySquad
The request was made by castle_chain
> Edit team SeveritySquad

- _data/handles/sdonkov.json
Auto-generated PR to register the new warden sdonkov
> Register warden sdonkov

- _data/handles/TopStar.json
Auto-generated PR to register the new warden TopStar
@Top88Star
> Register warden TopStar

- _data/handles/0xkkH4k3r.json
Auto-generated PR to register the new warden 0xkkH4k3r
@KiranKBR
> Register warden 0xkkH4k3r

- _data/handles/meta_88.json
Auto-generated PR to register the new warden meta_88
> Register warden meta_88

- _data/handles/Spman2330.json
Auto-generated PR to register the new warden Spman2330
@spman2330
> Register warden Spman2330

- _data/handles/branson.json
Auto-generated PR to register the new warden branson
> Register warden branson

- _data/handles/captcyrust.json
Auto-generated PR to register the new warden captcyrust
> Register warden captcyrust

- _data/handles/blazebear.json
Auto-generated PR to register the new warden blazebear
> Register warden blazebear

- _data/handles/Kensin_R.json
Auto-generated PR to register the new warden Kensin_R
> Register warden Kensin_R

- _data/handles/anya.json
Auto-generated PR to register the new warden anya
@Anushya-Raghavan
> Register warden anya

- _data/handles/enami_el.json
Auto-generated PR to register the new warden enami_el
> Register warden enami_el

- _data/handles/Hblackfox.json
Auto-generated PR to register the new warden Hblackfox
> Register warden Hblackfox

- _data/handles/Vancelot.json
Auto-generated PR to register the new warden Vancelot
@Vancelott
> Register warden Vancelot

- _data/handles/IzuMan.json
Auto-generated PR to register the new warden IzuMan
@IzuMan0x
> Register warden IzuMan

- _data/handles/AuditAvengers.json
This auto-generated PR modifies the team AuditAvengers
The request was made by piyushshukla
> Edit team AuditAvengers

- _data/handles/gavfu.json
Auto-generated PR to register the new warden gavfu
@gavfu
> Register warden gavfu

- _data/handles/falc.json
Auto-generated PR to register the new warden falc
> Register warden falc

- _data/handles/0x80085.json
Auto-generated PR to register the new warden 0x80085
@Shmuck
> Register warden 0x80085

- _data/handles/TECHFUND.json
This auto-generated PR modifies the team TECHFUND
The request was made by piyushshukla
> Edit team TECHFUND

- _data/handles/nslavchev.json
Auto-generated PR to register the new warden nslavchev
> Register warden nslavchev

- _data/handles/atul.json
Auto-generated PR to register the new warden atul
> Register warden atul

- _data/handles/zubec.json
Auto-generated PR to register the new warden zubec
@kroist
> Register warden zubec

- _data/handles/Wezabis.json
Auto-generated PR to register the new warden Wezabis
@wezabis
> Register warden Wezabis

- _data/handles/LBB88.json
Auto-generated PR to register the new warden LBB88
> Register warden LBB88

- _data/handles/shxdow.json
Auto-generated PR to register the new warden shxdow
@shxdow
> Register warden shxdow

- _data/handles/Aiknr.json
Auto-generated PR to register the new warden Aiknr
> Register warden Aiknr

- _data/handles/ycl82.json
Auto-generated PR to register the new warden ycl82
> Register warden ycl82

- _data/handles/XLCYun.json
Auto-generated PR to register the new warden XLCYun
> Register warden XLCYun

- _data/handles/nervouspika.json
Auto-generated PR to register the new warden nervouspika
> Register warden nervouspika

- _data/handles/bareMetalExecution.json
This auto-generated PR modifies the team bareMetalExecution
The request was made by Daniel526
> Edit team bareMetalExecution

- _data/handles/lionking927.json
Auto-generated PR to register the new warden lionking927
@softwaredev927
> Register warden lionking927

- _data/handles/okhaimie.json
Auto-generated PR to register the new warden okhaimie
@okhaimie-dev
> Register warden okhaimie

- _data/handles/imchrismayfield.json
Auto-generated PR to register the new warden imchrismayfield
@christophermayfield
> Register warden imchrismayfield

- _data/handles/ronpetamgas666.json
Auto-generated PR to register the new warden ronpetamgas666
> Register warden ronpetamgas666

- _data/handles/ljb630web3.json
Auto-generated PR to register the new warden ljb630web3
> Register warden ljb630web3

- _data/handles/ciomorvio.json
Auto-generated PR to register the new warden ciomorvio
@ciomorvio
> Register warden ciomorvio

- _data/handles/hima.json
Auto-generated PR to register the new warden hima
> Register warden hima

- _data/handles/nikplok.json
Auto-generated PR to register the new warden nikplok
@Benkben
> Register warden nikplok

- _data/handles/allahu4akbar.json
Auto-generated PR to register the new warden allahu4akbar
> Register warden allahu4akbar

- _data/handles/kennedy1030.json
Auto-generated PR to register the new warden kennedy1030
@kennedy1030
> Register warden kennedy1030

- _data/handles/BigGoose.json
- _data/handles/biggoosee.json
Auto-generated PR to register the new warden biggoosee
@gainlee
> Register warden BigGoose

- _data/handles/0xFieT.json
Auto-generated PR to register the new warden 0xFieT
> Register warden 0xFieT

- _data/handles/Ketchup256.json
Auto-generated PR to register the new warden Ketchup256
> Register warden Ketchup256

- _data/handles/Malware.json
Auto-generated PR to register the new warden Malware
> Register warden Malware

- _data/handles/andreas610.json
Auto-generated PR to register the new warden andreas610
> Register warden andreas610

- _data/handles/0xSecurityGuard.json
This auto-generated PR modifies the team 0xSecurityGuard
The request was made by zhaojohnson
> Edit team 0xSecurityGuard

- _data/handles/IdrisUsman.json
Auto-generated PR to register the new warden IdrisUsman
@Idris usman
> Register warden IdrisUsman

- _data/handles/huguez17.json
Auto-generated PR to register the new warden huguez17
> Register warden huguez17

- _data/handles/Knight0027.json
Auto-generated PR to register the new warden Knight0027
> Register warden Knight0027

- _data/handles/Billionaire1.json
Auto-generated PR to register the new warden Billionaire1
@Billionaire123456
> Register warden Billionaire1

- _data/handles/shahriar668.json
Auto-generated PR to register the new warden shahriar668
@shahriar669
> Register warden shahriar668

- _data/handles/blp_brochure.json
Auto-generated PR to register the new warden blp_brochure
> Register warden blp_brochure

- _data/handles/nandumaster.json
Auto-generated PR to register the new warden nandumaster
> Register warden nandumaster

- _data/handles/odipar69.json
Auto-generated PR to register the new warden odipar69
@odipars
> Register warden odipar69

- _data/handles/theegreat.json
Auto-generated PR to register the new warden theegreat
> Register warden theegreat

- _data/handles/defoxy1.json
Auto-generated PR to register the new warden defoxy1
@dev-defoxy
> Register warden defoxy1

- _data/handles/ASHIK_MIA.json
Auto-generated PR to register the new warden ASHIK_MIA
> Register warden ASHIK_MIA

- _data/handles/abd.json
Auto-generated PR to register the new warden abd
@ahmethedev
> Register warden abd

- _data/handles/bazigar.json
Auto-generated PR to register the new warden bazigar
> Register warden bazigar

- _data/handles/E11eEvans.json
Auto-generated PR to register the new warden E11eEvans
> Register warden E11eEvans

- _data/handles/blessingwisdom.json
Auto-generated PR to register the new warden blessingwisdom
@blessingwisdom
> Register warden blessingwisdom

- _data/handles/luvyakizzyashto.json
Auto-generated PR to register the new warden luvyakizzyashto
@luvyakizzyashto
> Register warden luvyakizzyashto

- _data/handles/cola.json
Auto-generated PR to register the new warden cola
> Register warden cola

- _data/handles/Mr_Steve.json
Auto-generated PR to register the new warden Mr_Steve
@ashish56858
> Register warden Mr_Steve

- _data/handles/Web3Goose.json
This auto-generated PR modifies the team Web3Goose
The request was made by 0xAadi
> Edit team Web3Goose

- _data/handles/alagbe003.json
Auto-generated PR to register the new warden alagbe003
@alagbe003
> Register warden alagbe003

- _data/handles/b069.json
Auto-generated PR to register the new warden b069
@Andramichae
> Register warden b069

- _data/handles/godz.json
Auto-generated PR to register the new warden godz
> Register warden godz

- _data/handles/kind0.json
Auto-generated PR to register the new warden kind0
> Register warden kind0

- _data/handles/shaixia.json
Auto-generated PR to register the new warden shaixia
> Register warden shaixia

- _data/handles/dragon777.json
Auto-generated PR to register the new warden dragon777
@nur
> Register warden dragon777

- _data/handles/0xSojol.json
Auto-generated PR to register the new warden 0xSojol
> Register warden 0xSojol

- _data/handles/BABEhjh.json
Auto-generated PR to register the new warden BABEhjh
> Register warden BABEhjh

- _data/handles/poslednaya.json
Auto-generated PR to register the new warden poslednaya
> Register warden poslednaya

- _data/handles/davies0212.json
Auto-generated PR to register the new warden davies0212
@davies0212
> Register warden davies0212

- _data/handles/OliveTr.json
Auto-generated PR to register the new warden OliveTr
> Register warden OliveTr

- _data/handles/brolag.json
Auto-generated PR to register the new warden brolag
@brolag
> Register warden brolag

- _data/handles/caldoza.json
Auto-generated PR to register the new warden caldoza
> Register warden caldoza

- _data/handles/vietnhim.json
Auto-generated PR to register the new warden vietnhim
> Register warden vietnhim

- _data/handles/engr5050.json
Auto-generated PR to register the new warden engr5050
> Register warden engr5050

- _data/handles/pulkit0111.json
Auto-generated PR to register the new warden pulkit0111
@Pulkit0111
> Register warden pulkit0111

- _data/handles/timofey_kabakov.json
Auto-generated PR to register the new warden timofey_kabakov
@okatau
> Register warden timofey_kabakov

- _data/handles/alexwww.json
Auto-generated PR to register the new warden alexwww
> Register warden alexwww

- _data/handles/dadoo.json
Auto-generated PR to register the new warden dadoo
> Register warden dadoo

- _data/handles/good0000vegetable-v2.json
Auto-generated PR to register the new warden good0000vegetable-v2
> Register warden good0000vegetable-v2

- _data/handles/aaa.json
Auto-generated PR to register the new warden aaa
> Register warden aaa

- _data/handles/smartkelvin.json
Auto-generated PR to register the new warden smartkelvin
@https://github.com/smartkelvin123
> Register warden smartkelvin

- _data/handles/gerceboss.json
Auto-generated PR to register the new warden gerceboss
@gerceboss
> Register warden gerceboss

- _data/handles/regz.json
Auto-generated PR to register the new warden regz
> Register warden regz

- _data/handles/FindEverythingX.json
Auto-generated PR to register the new warden FindEverythingX
> Register warden FindEverythingX

- _data/handles/504hk.json
Auto-generated PR to register the new warden 504hk
> Register warden 504hk

- _data/handles/heedfxn.json
Auto-generated PR to register the new warden heedfxn
> Register warden heedfxn

- _data/handles/wonderboy777.json
Auto-generated PR to register the new warden wonderboy777
@SuperDev0123
> Register warden wonderboy777

- _data/handles/Koala.json
Auto-generated PR to register the new warden Koala
> Register warden Koala

- _data/handles/0xAbloh.json
Auto-generated PR to register the new warden 0xAbloh
> Register warden 0xAbloh

- _data/handles/corporalking.json
Auto-generated PR to register the new warden corporalking
> Register warden corporalking

- _data/handles/shanb1605.json
Auto-generated PR to register the new warden shanb1605
@shanb1605
> Register warden shanb1605

- _data/handles/ukemeikut.json
Auto-generated PR to register the new warden ukemeikut
> Register warden ukemeikut

- _data/handles/Nerdymax.json
Auto-generated PR to register the new warden Nerdymax
@maxxy-tech
> Register warden Nerdymax

- _data/handles/hsncyln0.json
Auto-generated PR to register the new warden hsncyln0
> Register warden hsncyln0

- _data/handles/0xashok.json
Auto-generated PR to register the new warden 0xashok
> Register warden 0xashok

- _data/handles/omnislash.json
Auto-generated PR to register the new warden omnislash
@alan-cousin
> Register warden omnislash

- _data/handles/yasmine.json
Auto-generated PR to register the new warden yasmine
@yasmine8
> Register warden yasmine

- _data/handles/daveproxy80.json
Auto-generated PR to register the new warden daveproxy80
@DADADAVE80
> Register warden daveproxy80

- _data/handles/yoisha.json
Auto-generated PR to register the new warden yoisha
@y-pakorn
> Register warden yoisha

- _data/handles/lala001215.json
Auto-generated PR to register the new warden lala001215
> Register warden lala001215

- _data/handles/cherrySec.json
This auto-generated PR creates the team cherrySec
> Create team cherrySec

- _data/handles/ka3l.json
Auto-generated PR to register the new warden ka3l
> Register warden ka3l

- _data/handles/anemone0759.json
Auto-generated PR to register the new warden anemone0759
> Register warden anemone0759

- _data/handles/DayaaDean.json
Auto-generated PR to register the new warden DayaaDean
@bayou020
> Register warden DayaaDean

- _data/handles/zeroaddress.json
Auto-generated PR to register the new warden zeroaddress
@zeroaddresss
> Register warden zeroaddress

- _data/handles/discotest.json
Auto-generated PR to register the new warden discotest
> Register warden discotest

- _data/handles/isommie.json
Auto-generated PR to register the new warden isommie
@anajembaedwin
> Register warden isommie

- _data/handles/Hoax.json
This auto-generated PR modifies the team Hoax
The request was made by Collinsoden
> Edit team Hoax

- _data/handles/O_Abdullahi.json
Auto-generated PR to register the new warden O_Abdullahi
> Register warden O_Abdullahi

- _data/handles/shiatsu.json
Auto-generated PR to register the new warden shiatsu
@shiat5u
> Register warden shiatsu

- _data/handles/0xdaem0n.json
Auto-generated PR to register the new warden 0xdaem0n
@biboftw
> Register warden 0xdaem0n

- _data/handles/raouf2ouf.json
Auto-generated PR to register the new warden raouf2ouf
@raouf2ouf
> Register warden raouf2ouf

- _data/handles/gladiator111.json
Auto-generated PR to register the new warden gladiator111
> Register warden gladiator111

- _data/handles/Shahil_Hussain.json
Auto-generated PR to register the new warden Shahil_Hussain
@0x-Shahil-Hussain
> Register warden Shahil_Hussain

- _data/handles/E_Beggar.json
Auto-generated PR to register the new warden E_Beggar
> Register warden E_Beggar

- _data/handles/wangereth.json
Auto-generated PR to register the new warden wangereth
> Register warden wangereth

- _data/handles/sangal0810.json
Auto-generated PR to register the new warden sangal0810
> Register warden sangal0810

- _data/handles/quantumattacker0.json
Auto-generated PR to register the new warden quantumattacker0
@apirker
> Register warden quantumattacker0

- _data/handles/AlgorinthLabsLlc.json
This auto-generated PR modifies the team AlgorinthLabsLlc
The request was made by oldguard
> Edit team AlgorinthLabsLlc

- _data/handles/CodeWasp.json
This auto-generated PR modifies the team CodeWasp
The request was made by kuprum
> Edit team CodeWasp

- _data/handles/mantihs.json
Auto-generated PR to register the new warden mantihs
@manti
> Register warden mantihs

- _data/handles/PLUTOOVERPOWER.json
Auto-generated PR to register the new warden PLUTOOVERPOWER
> Register warden PLUTOOVERPOWER

- _data/handles/kingleard.json
Auto-generated PR to register the new warden kingleard
> Register warden kingleard

- _data/handles/ikolev.json
Auto-generated PR to register the new warden ikolev
> Register warden ikolev

- _data/handles/Lanfear.json
Auto-generated PR to register the new warden Lanfear
> Register warden Lanfear

- _data/handles/pivanov.json
Auto-generated PR to register the new warden pivanov
> Register warden pivanov

- _data/handles/codexNature.json
Auto-generated PR to register the new warden codexNature
@codexNature
> Register warden codexNature

- _data/handles/EaglesSecurity.json
This auto-generated PR creates the team EaglesSecurity
> Create team EaglesSecurity

- _data/handles/Haribabupulibandla.json
Auto-generated PR to register the new warden Haribabupulibandla
> Register warden Haribabupulibandla

- _data/handles/EchoSpr.json
Auto-generated PR to register the new warden EchoSpr
@https://github.com/EchoSpr
> Register warden EchoSpr

- _data/handles/aleksandar_k.json
Auto-generated PR to register the new warden aleksandar_k
@Aleksandar Krastinkov
> Register warden aleksandar_k

- _data/handles/baz1ka.json
Auto-generated PR to register the new warden baz1ka
@baz1ka
> Register warden baz1ka

- _data/handles/Sajjad.json
Auto-generated PR to register the new warden Sajjad
> Register warden Sajjad

- _data/handles/Katrix.json
Auto-generated PR to register the new warden Katrix
@KatrixReloaded
> Register warden Katrix

- _data/handles/Nave.json
Auto-generated PR to register the new warden Nave
> Register warden Nave

- _data/handles/LittleT.json
Auto-generated PR to register the new warden LittleT
> Register warden LittleT

- _data/handles/DPS.json
This auto-generated PR creates the team DPS
> Create team DPS

- _data/handles/crypto-one.json
Auto-generated PR to register the new warden crypto-one
@Crypto-One-dev
> Register warden crypto-one

- _data/handles/krisp.json
Auto-generated PR to register the new warden krisp
@krisp7917
> Register warden krisp

- _data/handles/kwar13.json
Auto-generated PR to register the new warden kwar13
@kavehtehrani
> Register warden kwar13

- _data/handles/keeping2Code.json
Auto-generated PR to register the new warden keeping2Code
@keeping2Code
> Register warden keeping2Code

- _data/handles/bitwisebytes.json
Auto-generated PR to register the new warden bitwisebytes
@maschad96
> Register warden bitwisebytes

- _data/handles/covey0x07.json
Auto-generated PR to register the new warden covey0x07
@covey0x07
> Register warden covey0x07

- _data/handles/mrima.json
Auto-generated PR to register the new warden mrima
@mosesmrima
> Register warden mrima

- _data/handles/Frivo__.json
Auto-generated PR to register the new warden Frivo__
@Frivoo
> Register warden Frivo__

- _data/handles/samuria.json
Auto-generated PR to register the new warden samuria
@samuria
> Register warden samuria

- _data/handles/0xAman.json
Auto-generated PR to register the new warden 0xAman
> Register warden 0xAman

- _data/handles/dimoztarra.json
Auto-generated PR to register the new warden dimoztarra
> Register warden dimoztarra

- _data/handles/emilesean.json
Auto-generated PR to register the new warden emilesean
@emilesean
> Register warden emilesean

- _data/handles/Sparrow.json
Auto-generated PR to register the new warden Sparrow
> Register warden Sparrow

- _data/handles/Tritonn.json
Auto-generated PR to register the new warden Tritonn
@Tritonn204
> Register warden Tritonn

- _data/handles/nathanjones0161.json
Auto-generated PR to register the new warden nathanjones0161
@Nathan12212
> Register warden nathanjones0161

- _data/handles/Gigalias.json
Auto-generated PR to register the new warden Gigalias
> Register warden Gigalias

- _data/handles/DemoreX.json
Auto-generated PR to register the new warden DemoreX
> Register warden DemoreX

- _data/handles/SkyRom.json
Auto-generated PR to register the new warden SkyRom
> Register warden SkyRom

- _data/handles/fabrice_sam_3105.json
Auto-generated PR to register the new warden fabrice_sam_3105
@fabrice32
> Register warden fabrice_sam_3105

- _data/handles/nnamdi0482.json
Auto-generated PR to register the new warden nnamdi0482
> Register warden nnamdi0482

- _data/handles/profsrzoom.json
Auto-generated PR to register the new warden profsrzoom
@joelvaiju
> Register warden profsrzoom

- _data/handles/Kunhah.json
Auto-generated PR to register the new warden Kunhah
@Kunhqh
> Register warden Kunhah

- _data/handles/gajiknownnothing.json
Auto-generated PR to register the new warden gajiknownnothing
> Register warden gajiknownnothing

- _data/handles/bachpc.json
Auto-generated PR to register the new warden bachpc
@bachpc
> Register warden bachpc

- _data/handles/adilc.json
Auto-generated PR to register the new warden adilc
@achoudhury4927
> Register warden adilc

- _data/handles/tanvir3.json
Auto-generated PR to register the new warden tanvir3
@https://github.com/B-Tanvir
> Register warden tanvir3

- _data/handles/rmzy47.json
Auto-generated PR to register the new warden rmzy47
@ r-mzy47
> Register warden rmzy47

- _data/handles/waydou.json
Auto-generated PR to register the new warden waydou
> Register warden waydou

- _data/handles/Blockchainbaddie.json
Auto-generated PR to register the new warden Blockchainbaddie
@khadeeejah
> Register warden Blockchainbaddie

- _data/handles/icy_petal.json
Auto-generated PR to register the new warden icy_petal
@icypetal
> Register warden icy_petal

- _data/handles/marinov23.json
Auto-generated PR to register the new warden marinov23
@GMarinov2
> Register warden marinov23

- _data/handles/pwn2happy.json
Auto-generated PR to register the new warden pwn2happy
> Register warden pwn2happy

- _data/handles/GuardianSphere.json
This auto-generated PR creates the team GuardianSphere
> Create team GuardianSphere

- _data/handles/KYP.json
This auto-generated PR creates the team KYP
> Create team KYP

- _data/handles/BlockBreach_Audits.json
This auto-generated PR creates the team BlockBreach_Audits
> Create team BlockBreach_Audits

- _data/handles/GuardianSphere.json
This auto-generated PR modifies the team GuardianSphere
The request was made by Mylifechangefast_eth
> Edit team GuardianSphere

- _data/handles/Koycegiz.json
This auto-generated PR creates the team Koycegiz
> Create team Koycegiz

- _data/handles/KYP.json
This auto-generated PR modifies the team KYP
The request was made by yotov721
> Edit team KYP

- _data/handles/LessDupes.json
This auto-generated PR creates the team LessDupes
> Create team LessDupes

- _data/handles/Web3Vikings.json
This auto-generated PR creates the team Web3Vikings
> Create team Web3Vikings

- _data/handles/Dup1337.json
This auto-generated PR modifies the team Dup1337
The request was made by sorrynotsorry
> Edit team Dup1337

- _data/handles/TPSec.json
This auto-generated PR creates the team TPSec
> Create team TPSec

- _data/handles/ASCANsec.json
This team requested deletion (see here: https://github.com/code-423n4/code423n4.com/pull/16867), but has submissions. Archiving instead.
> Archive Team: ASCANsec

- _data/handles/LFGSecurity.json
This team requested deletion (see here: https://github.com/code-423n4/code423n4.com/pull/16874), but has past awarded findings. Archiving instead.
> Archive Team: LFGSecurity

- _data/handles/winwin.json
This auto-generated PR creates the team winwin
> Create team winwin

- _data/handles/kukerlabs.json
This auto-generated PR creates the team kukerlabs
> Create team kukerlabs

- _data/handles/PolarizedLight.json
This auto-generated PR creates the team PolarizedLight
> Create team PolarizedLight

- _data/handles/S5.json
This auto-generated PR updates payment addresses for team S5. (request made by YungMessiah)
> Update payment addresses for team S5

- _data/handles/Dup1337.json
This auto-generated PR updates payment addresses for team Dup1337. (request made by sorrynotsorry)
> Update payment addresses for team Dup1337

- _data/handles/LessDupes.json
This auto-generated PR updates payment addresses for team LessDupes. (request made by 3docSec)
> Update payment addresses for team LessDupes

- _data/handles/hubble.json
This auto-generated PR updates payment addresses for team hubble. (request made by ksk2345)
> Update payment addresses for team hubble

- _data/handles/0xMATRIX.json
This auto-generated PR creates the team 0xMATRIX
> Create team 0xMATRIX

- _data/handles/XR20.json
This auto-generated PR creates the team XR20
> Create team XR20

- _data/handles/BlockSafe.json
This auto-generated PR creates the team BlockSafe
> Create team BlockSafe

- _data/handles/Yunaci.json
This auto-generated PR creates the team Yunaci
> Create team Yunaci

- _data/handles/AirSprint.json
This auto-generated PR modifies the team AirSprint
The request was made by CongZhang-CertiK
> Edit team AirSprint

- _data/handles/Team_RockSolid.json
This auto-generated PR creates the team Team_RockSolid
> Create team Team_RockSolid

- _data/handles/kukerlabs.json
This auto-generated PR modifies the team kukerlabs
The request was made by gorskireket
> Edit team kukerlabs

- _data/handles/bareMetalExecution.json
Team has requested deletion (see here: https://github.com/code-423n4/code423n4.com/pull/16899), but has past submissions. Archiving instead.
> Archive Team bareMetalExecution

- _data/handles/Safisec3.json
Reverts code-423n4/code423n4.com#16912
> Re-Create team Safisec3

- _data/handles/BlockSafe.json
This auto-generated PR modifies the team BlockSafe
The request was made by PrasadLak
> Edit team BlockSafe

- _data/handles/dinosaur.json
This auto-generated PR creates the team dinosaur
> Create team dinosaur

- _data/handles/WinSec.json
This auto-generated PR modifies the team WinSec
The request was made by 0xweb3boy
> Edit team WinSec

- _data/handles/SWATSecurity.json
This auto-generated PR creates the team SWATSecurity
> Create team SWATSecurity

- _data/handles/Team-SAND-DD.json
This auto-generated PR modifies the team Team-SAND-DD
The request was made by avik_saikat
> Edit team Team-SAND-DD

- _data/handles/Centaur.json
This auto-generated PR modifies the team Centaur
The request was made by Mylifechangefast_eth
> Edit team Centaur

- _data/handles/fungi.json
This auto-generated PR creates the team fungi
> Create team fungi

- _data/handles/EPSec.json
This auto-generated PR modifies the team EPSec
The request was made by 1337web3
> Edit team EPSec

- _data/handles/win-win.json
This auto-generated PR creates the team win-win
> Create team win-win

- _data/handles/ForkEth.json
This auto-generated PR modifies the team ForkEth
The request was made by NullbutC00L
> Edit team ForkEth

- _data/handles/0xHunterSec.json
This auto-generated PR creates the team 0xHunterSec
> Create team 0xHunterSec

- _data/handles/win-win.json
This auto-generated PR modifies the team win-win
The request was made by Satyam_Sharma
> Edit team win-win

- _data/handles/GangsOfBrahmin.json
Team has requested deletion (see here: https://github.com/code-423n4/code423n4.com/pull/16930), but has past submissions. Archiving instead.
> Archive Team GangsOfBrahmin

- _data/handles/Fortis_audits.json
This auto-generated PR modifies the team Fortis_audits
The request was made by Bluedragon101
> Edit team Fortis_audits

- _data/handles/GEEKS.json
This auto-generated PR creates the team GEEKS
> Create team GEEKS

- _data/handles/unRekt.json
This auto-generated PR creates the team unRekt
> Create team unRekt

- _data/handles/Nebuchadnezzar.json
This auto-generated PR creates the team Nebuchadnezzar
> Create team Nebuchadnezzar

- _data/handles/50audits.json
This auto-generated PR modifies the team 50audits
The request was made by thisvishalsingh
> Edit team 50audits

- _data/handles/20centclub.json
This auto-generated PR creates the team 20centclub
> Create team 20centclub

- _data/handles/NexusAudits.json
This auto-generated PR creates the team NexusAudits
> Create team NexusAudits

- _data/handles/INDHawks.json
This auto-generated PR creates the team INDHawks
> Create team INDHawks

- _data/handles/Decipher100Eyes.json
This auto-generated PR creates the team Decipher100Eyes
> Create team Decipher100Eyes

- _data/handles/fungi.json
This auto-generated PR modifies the team fungi
The request was made by hezze
> Edit team fungi

- _data/handles/BaldHeads.json
This auto-generated PR creates the team BaldHeads
> Create team BaldHeads

- _data/handles/COSMIC-BEE-REACH.json
Team has requested deletion (see here: https://github.com/code-423n4/code423n4.com/pull/16953) but has past submissions. Archiving instead.
> Archive Team COSMIC-BEE-REACH

- _data/handles/RI_trollers.json
This auto-generated PR creates the team RI_trollers
> Create team RI_trollers

- _data/handles/BugBountyHunters.json
This auto-generated PR creates the team BugBountyHunters
> Create team BugBountyHunters

- _data/handles/BugBountyHunter.json
This auto-generated PR creates the team BugBountyHunter
> Create team BugBountyHunter

- _data/handles/RI_trollers.json
This auto-generated PR modifies the team RI_trollers
The request was made by rscodes
> Edit team RI_trollers

- _data/handles/Safisec3.json
Archiving team in response to this deletion request: https://github.com/code-423n4/code423n4.com/pull/16950
> Archive Team Safisec3

- _data/handles/BugMafia.json
This auto-generated PR creates the team BugMafia
> Create team BugMafia

- _data/handles/0xSecurityGuard.json
Reverts code-423n4/code423n4.com#16917
> Revert deletion, then archive team 0xSecurityGuard

- _data/handles/Femboys.json
This auto-generated PR creates the team Femboys
> Create team Femboys

- _data/handles/Zubat.json
This auto-generated PR creates the team Zubat
> Create team Zubat

- _data/handles/0xgozol.json
This auto-generated PR creates the team 0xgozol
> Create team 0xgozol

- _data/handles/Vulnerabits.json
This auto-generated PR creates the team Vulnerabits
> Create team Vulnerabits

- _data/handles/PolarizedLight.json
This auto-generated PR modifies the team PolarizedLight
The request was made by ChaseTheLight
> Edit team PolarizedLight

- _data/handles/X.json
This auto-generated PR creates the team X
> Create team X

- _data/handles/RadiantLabs.json
This auto-generated PR creates the team RadiantLabs
> Create team RadiantLabs

- _data/handles/KaligoAudits.json
This auto-generated PR creates the team KaligoAudits
> Create team KaligoAudits

- _data/handles/ShadowBytes.json
This auto-generated PR creates the team ShadowBytes
> Create team ShadowBytes

- _data/handles/BEYOND.json
This auto-generated PR modifies the team BEYOND
The request was made by Greed
> Edit team BEYOND

- _data/handles/BugPull.json
This auto-generated PR creates the team BugPull
> Create team BugPull

- _data/handles/LogBytes.json
This auto-generated PR creates the team LogBytes
> Create team LogBytes

- _data/handles/Shield.json
This auto-generated PR modifies the team Shield
The request was made by Udsen
> Edit team Shield

- _data/handles/Undefined.json
This auto-generated PR creates the team Undefined
> Create team Undefined

- _data/handles/100HP.json
This auto-generated PR creates the team 100HP
> Create team 100HP

- _data/handles/Bughunterz.json
This auto-generated PR creates the team Bughunterz
> Create team Bughunterz

- _data/handles/0xE79e.json
- _data/handles/0xNubs.json
- _data/handles/FORTIFYX.json
- _data/handles/INDHawks.json
Original deletion requests:
- 0xE79e: https://github.com/code-423n4/code423n4.com/pull/16975
- 0xNubs: https://github.com/code-423n4/code423n4.com/pull/16979
- FORTIFYX: https://github.com/code-423n4/code423n4.com/pull/16989
- INDHawks: https://github.com/code-423n4/code423n4.com/pull/16991
> Archive Multiple Teams

- _data/handles/TestinKevs.json
This auto-generated PR modifies the team TestinKevs
The request was made by SamusElderg
> Edit team TestinKevs

- _data/handles/GEEKS.json
This auto-generated PR modifies the team GEEKS
The request was made by 0xfave
> Edit team GEEKS

- _data/handles/mashbust.json
This auto-generated PR creates the team mashbust
> Create team mashbust

- _data/handles/Gladiators.json
This auto-generated PR creates the team Gladiators
> Create team Gladiators

- _data/handles/MKVsentry.json
This auto-generated PR creates the team MKVsentry
> Create team MKVsentry

- _data/handles/Trident-Audits.json
This auto-generated PR creates the team Trident-Audits
> Create team Trident-Audits

- _data/handles/Trident-Audits.json
This auto-generated PR modifies the team Trident-Audits
The request was made by mgnfy_view
> Edit team Trident-Audits

- _data/handles/PathFinders.json
This auto-generated PR creates the team PathFinders
> Create team PathFinders

- _data/handles/DOWSERS.json
This auto-generated PR creates the team DOWSERS
> Create team DOWSERS

- _data/handles/DigiSafe.json
This auto-generated PR creates the team DigiSafe
> Create team DigiSafe

- _data/handles/RAJPUTANA_RIFLES.json
This auto-generated PR creates the team RAJPUTANA_RIFLES
> Create team RAJPUTANA_RIFLES

- _data/handles/mashbust.json
This auto-generated PR modifies the team mashbust
The request was made by abdulsamijay
> Edit team mashbust

- _data/handles/BugPull.json
This auto-generated PR modifies the team BugPull
The request was made by IlIlHunterlIlI
> Edit team BugPull

- _data/handles/RadiantLabs.json
This auto-generated PR modifies the team RadiantLabs
The request was made by EV_om
> Edit team RadiantLabs

- _data/handles/ParaTroopers.json
This auto-generated PR creates the team ParaTroopers
> Create team ParaTroopers

- _data/handles/RAJPUTANA_RIFLES.json
- _data/handles/Vulnerabits.json
Original deletion requests:
- https://github.com/code-423n4/code423n4.com/pull/17015
- https://github.com/code-423n4/code423n4.com/pull/17017
> Archive teams: `RAJPUTANA_RIFLES` and `Vulnerabits`

- _data/handles/Omnes.json
This auto-generated PR creates the team Omnes
> Create team Omnes

- _data/handles/OpaBatyo.json
This auto-generated PR creates the team OpaBatyo
> Create team OpaBatyo

- _data/handles/Subroutine.json
This auto-generated PR creates the team Subroutine
> Create team Subroutine

- _data/handles/DigiSafe.json
This auto-generated PR modifies the team DigiSafe
The request was made by Svetoslavb
> Edit team DigiSafe

- _data/handles/MKVsentry.json
This auto-generated PR modifies the team MKVsentry
The request was made by bozhikov_
> Edit team MKVsentry

- _data/handles/wasm_it.json
This auto-generated PR creates the team wasm_it
> Create team wasm_it

- _data/handles/DOWSERS.json
This auto-generated PR modifies the team DOWSERS
The request was made by desaperh
> Edit team DOWSERS

- _data/handles/win-win.json
Deletion originally requested here: https://github.com/code-423n4/code423n4.com/pull/17039 - archiving instead.
> Archive team win-win

- _data/handles/WolfMen.json
This auto-generated PR creates the team WolfMen
> Create team WolfMen

- _data/handles/0xfort-com.json
This auto-generated PR creates the team 0xfort-com
> Create team 0xfort-com

- _data/handles/ChainPatrol.json
This auto-generated PR creates the team ChainPatrol
> Create team ChainPatrol

- _data/handles/Hu3SLabs.json
This auto-generated PR creates the team Hu3SLabs
> Create team Hu3SLabs

- _data/handles/BugHunters1.json
This auto-generated PR creates the team BugHunters1
> Create team BugHunters1

- _data/handles/audism.json
This auto-generated PR creates the team audism
> Create team audism

- _data/handles/valley_security.json
This auto-generated PR creates the team valley_security
> Create team valley_security

- _data/handles/SecLat.json
This auto-generated PR creates the team SecLat
> Create team SecLat

- _data/handles/Team-Slayer.json
Team requested deletion here: https://github.com/code-423n4/code423n4.com/pull/17053
Archiving instead.
> Archive Team: Team-Slayer

- _data/handles/WolfMen.json
This auto-generated PR modifies the team WolfMen
The request was made by jovemjeune
> Edit team WolfMen

- _data/handles/tenge_club.json
This auto-generated PR creates the team tenge_club
> Create team tenge_club

- _data/handles/056Security.json
This auto-generated PR creates the team 056Security
> Create team 056Security

- _data/handles/sparrowhawl.json
This auto-generated PR creates the team sparrowhawl
> Create team sparrowhawl

- _data/handles/100HP.json
Original deletion request: https://github.com/code-423n4/code423n4.com/pull/17055
Archiving instead.
> Archive Team: 100HP

- _data/handles/CipherShieldGlobal.json
This auto-generated PR creates the team CipherShieldGlobal
> Create team CipherShieldGlobal

- _data/handles/Vidus.json
This auto-generated PR creates the team Vidus
> Create team Vidus

- _data/handles/Exigentaudits.json
This auto-generated PR creates the team Exigentaudits
> Create team Exigentaudits

- _data/handles/EastHats.json
This auto-generated PR creates the team EastHats
> Create team EastHats

- _data/handles/Zyphernix_Security.json
This auto-generated PR creates the team Zyphernix_Security
> Create team Zyphernix_Security

- _data/handles/BugMafia.json
Original request: https://github.com/code-423n4/code423n4.com/pull/17068
> Archive Team: BugMafia

- _data/handles/Sparkware.json
Original request: https://github.com/code-423n4/code423n4.com/pull/17072
> Archive Team: Sparkware

- _data/handles/Zyphernix_Security.json
This auto-generated PR modifies the team Zyphernix_Security
The request was made by 0xcodingowls
> Edit team Zyphernix_Security

- _data/handles/DaidalosInitiative.json
This auto-generated PR creates the team DaidalosInitiative
> Create team DaidalosInitiative

- _data/handles/ShieldLabs.json
This auto-generated PR creates the team ShieldLabs
> Create team ShieldLabs

- _data/handles/fungi.json
Original deletion request here: https://github.com/code-423n4/code423n4.com/pull/17077
Archiving instead.
> Archive Team: fungi

- _data/handles/AndoyaSec.json
This auto-generated PR creates the team AndoyaSec
> Create team AndoyaSec

- _data/handles/CSL.json
This auto-generated PR modifies the team CSL
The request was made by levi_104
> Edit team CSL

- _data/handles/bumbleb33.json
This auto-generated PR creates the team bumbleb33
> Create team bumbleb33

- _data/handles/Vagabond.json
This auto-generated PR creates the team Vagabond
> Create team Vagabond

- _data/handles/st_runk.json
This auto-generated PR creates the team st_runk
> Create team st_runk

- _data/handles/TheKhans.json
This auto-generated PR creates the team TheKhans
> Create team TheKhans

- _data/handles/0xCodeRedFinders.json
This auto-generated PR creates the team 0xCodeRedFinders
> Create team 0xCodeRedFinders

- _data/handles/OakSecurity.json
This auto-generated PR creates the team OakSecurity
> Create team OakSecurity

- _data/handles/Contest-Squad.json
This auto-generated PR creates the team Contest-Squad
> Create team Contest-Squad

- _data/handles/Striking_Lions.json
This auto-generated PR creates the team Striking_Lions
> Create team Striking_Lions

- _data/handles/Securr.json
This auto-generated PR creates the team Securr
> Create team Securr

- _data/handles/12121212.json
This auto-generated PR creates the team 12121212
> Create team 12121212

- _data/handles/HackSyndicate.json
This auto-generated PR creates the team HackSyndicate
> Create team HackSyndicate

- _data/handles/EternalLuck.json
This auto-generated PR creates the team EternalLuck
> Create team EternalLuck

- _data/handles/VeriaLabs.json
This auto-generated PR creates the team VeriaLabs
> Create team VeriaLabs

- _data/handles/LlamaFactor.json
This auto-generated PR creates the team LlamaFactor
> Create team LlamaFactor

- _data/handles/Arjuna.json
This auto-generated PR creates the team Arjuna
> Create team Arjuna

- _data/handles/Heavyweight_hunters.json
This auto-generated PR creates the team Heavyweight_hunters
> Create team Heavyweight_hunters

- _data/handles/jwebprojecs.json
This auto-generated PR creates the team jwebprojecs
> Create team jwebprojecs

- _data/handles/phaseTwo.json
This auto-generated PR creates the team phaseTwo
> Create team phaseTwo

- _data/handles/MerkleSec.json
This auto-generated PR creates the team MerkleSec
> Create team MerkleSec

- _data/handles/Ward.json
This auto-generated PR modifies the team Ward
The request was made by 0xpessimist
> Edit team Ward

- _data/handles/JWEBPROJECTS.json
This auto-generated PR creates the team JWEBPROJECTS
> Create team JWEBPROJECTS

- _data/handles/potatoad-sec.json
This auto-generated PR creates the team potatoad-sec
> Create team potatoad-sec

- _data/handles/WILL_of_LORD.json
This auto-generated PR creates the team WILL_of_LORD
> Create team WILL_of_LORD

- _data/handles/DoubleDragon.json
This auto-generated PR creates the team DoubleDragon
> Create team DoubleDragon

- _data/handles/SlayerSecurity.json
This auto-generated PR creates the team SlayerSecurity
> Create team SlayerSecurity

- _data/handles/JWEBPROJECTS.json
This auto-generated PR modifies the team JWEBPROJECTS
The request was made by jauvany
> Edit team JWEBPROJECTS

- _data/handles/IQ_hunter.json
This auto-generated PR creates the team IQ_hunter
> Create team IQ_hunter

- _data/handles/KannAudits.json
This auto-generated PR creates the team KannAudits
> Create team KannAudits

- _data/handles/GMJ.json
This auto-generated PR creates the team GMJ
> Create team GMJ

- _data/handles/Brototo.json
This auto-generated PR creates the team Brototo
> Create team Brototo

- _data/handles/ByteGuard.json
This auto-generated PR creates the team ByteGuard
> Create team ByteGuard

- _data/handles/KannAudits.json
This auto-generated PR modifies the team KannAudits
The request was made by 0xKann
> Edit team KannAudits

- _data/handles/ajaks.json
This auto-generated PR creates the team ajaks
> Create team ajaks

- _data/handles/OakSecurity.json
This auto-generated PR modifies the team OakSecurity
The request was made by ps
> Edit team OakSecurity

- _data/handles/Guardians.json
This auto-generated PR modifies the team Guardians
The request was made by 0xozovehe
> Edit team Guardians

- _data/handles/0xVI.json
This auto-generated PR creates the team 0xVI
> Create team 0xVI

- _data/handles/SafetyBytes.json
This auto-generated PR creates the team SafetyBytes
> Create team SafetyBytes

- _data/handles/Cutthroat_Security.json
This auto-generated PR modifies the team Cutthroat_Security
The request was made by LordAlive
> Edit team Cutthroat_Security

- _data/handles/Striking_Lions.json
This auto-generated PR modifies the team Striking_Lions
The request was made by misbahu
> Edit team Striking_Lions

- _data/handles/CODESPECT.json
This auto-generated PR creates the team CODESPECT
> Create team CODESPECT

- _data/handles/rapid.json
This auto-generated PR creates the team rapid
> Create team rapid

- _data/handles/Arjuna.json
This auto-generated PR modifies the team Arjuna
The request was made by calc1f4r
> Edit team Arjuna

- _data/handles/Buggers.json
This auto-generated PR creates the team Buggers
> Create team Buggers

- _data/handles/Coverage.json
This auto-generated PR modifies the team Coverage
The request was made by zegarcao
> Edit team Coverage

- _data/handles/HalalAudits.json
This auto-generated PR creates the team HalalAudits
> Create team HalalAudits

- _data/handles/ProtocolBreakers.json
This auto-generated PR creates the team ProtocolBreakers
> Create team ProtocolBreakers

- _data/handles/HaidutiSec.json
This auto-generated PR creates the team HaidutiSec
> Create team HaidutiSec

- _data/handles/0xForte.json
This auto-generated PR creates the team 0xForte
> Create team 0xForte

- _data/handles/0xForte.json
This auto-generated PR modifies the team 0xForte
The request was made by Brdjx
> Edit team 0xForte

- _data/handles/QuillAudits_Elite.json
This auto-generated PR creates the team QuillAudits_Elite
> Create team QuillAudits_Elite

- _data/handles/Trikal_Hackers.json
This auto-generated PR creates the team Trikal_Hackers
> Create team Trikal_Hackers

- _data/handles/HashNodeLabs.json
This auto-generated PR creates the team HashNodeLabs
> Create team HashNodeLabs

- _data/handles/Buggers.json
This auto-generated PR modifies the team Buggers
The request was made by Arvolear
> Edit team Buggers

- _data/handles/InterOp.json
This auto-generated PR creates the team InterOp
> Create team InterOp

- _data/handles/Ikigai.json
This auto-generated PR creates the team Ikigai
> Create team Ikigai

- _data/handles/Ledger_Patrol.json
This auto-generated PR creates the team Ledger_Patrol
> Create team Ledger_Patrol

- _data/handles/Arculus_Security.json
This auto-generated PR creates the team Arculus_Security
> Create team Arculus_Security

- _data/handles/ASTRA.json
This auto-generated PR creates the team ASTRA
> Create team ASTRA

- _data/handles/ashdib.json
This auto-generated PR creates the team ashdib
> Create team ashdib

- _data/handles/Arculus_Security.json
This auto-generated PR modifies the team Arculus_Security
The request was made by 0xabhay
> Edit team Arculus_Security

- _data/handles/VulnSeekers.json
This auto-generated PR creates the team VulnSeekers
> Create team VulnSeekers

- _data/handles/momentum.json
This auto-generated PR creates the team momentum
> Create team momentum

- _data/handles/Web3Husaria.json
This auto-generated PR creates the team Web3Husaria
> Create team Web3Husaria

- _data/handles/MohitAndRanjan.json
This auto-generated PR creates the team MohitAndRanjan
> Create team MohitAndRanjan

- _data/handles/Hardcore.json
This auto-generated PR creates the team Hardcore
> Create team Hardcore

- _data/handles/Hardcore.json
This auto-generated PR modifies the team Hardcore
The request was made by hanz
> Edit team Hardcore

- _data/handles/Kodo_Warriors.json
This auto-generated PR creates the team Kodo_Warriors
> Create team Kodo_Warriors

- _data/handles/Duality404.json
This auto-generated PR creates the team Duality404
> Create team Duality404

- _data/handles/BestBugBusters.json
This auto-generated PR creates the team BestBugBusters
> Create team BestBugBusters

- _data/handles/DreamTeam.json
This auto-generated PR creates the team DreamTeam
> Create team DreamTeam

- _data/handles/HaidutiSec.json
This auto-generated PR modifies the team HaidutiSec
The request was made by Merulez99
> Edit team HaidutiSec

- _data/handles/LeonCode4rena.json
This auto-generated PR creates the team LeonCode4rena
> Create team LeonCode4rena

- _data/handles/TeamEmminence.json
This auto-generated PR creates the team TeamEmminence
> Create team TeamEmminence

- _data/handles/Doogle.json
This auto-generated PR creates the team Doogle
> Create team Doogle

- _data/handles/bytesguard.json
This auto-generated PR creates the team bytesguard
> Create team bytesguard

- _data/handles/RektZero.json
This auto-generated PR creates the team RektZero
> Create team RektZero

- _data/handles/SlayTheAudit.json
This auto-generated PR creates the team SlayTheAudit
> Create team SlayTheAudit

- _data/handles/theraiders.json
This auto-generated PR creates the team theraiders
> Create team theraiders

- _data/handles/audism.json
This auto-generated PR modifies the team audism
The request was made by jeffy
> Edit team audism

- _data/handles/MohitAndRanjan.json
This auto-generated PR modifies the team MohitAndRanjan
The request was made by mohit_codes
> Edit team MohitAndRanjan

- _data/handles/NakMuay.json
This auto-generated PR creates the team NakMuay
> Create team NakMuay

- _data/handles/0xWithdrawers.json
This auto-generated PR creates the team 0xWithdrawers
> Create team 0xWithdrawers

- _data/handles/Uzarix.json
This auto-generated PR creates the team Uzarix
> Create team Uzarix

- _data/handles/algiz.json
This auto-generated PR creates the team algiz
> Create team algiz

- _data/handles/SlaapLekker.json
This auto-generated PR creates the team SlaapLekker
> Create team SlaapLekker

- _data/handles/Yandry_labs.json
This auto-generated PR creates the team Yandry_labs
> Create team Yandry_labs

- _data/handles/latamwarrios.json
This auto-generated PR creates the team latamwarrios
> Create team latamwarrios

- _data/handles/AuditIntern.json
This auto-generated PR modifies the team AuditIntern
The request was made by lihwy
> Edit team AuditIntern

- _data/handles/Zealynx.json
This auto-generated PR creates the team Zealynx
> Create team Zealynx

- _data/handles/SilverShell.json
This auto-generated PR creates the team SilverShell
> Create team SilverShell

- _data/handles/calldata.json
This auto-generated PR creates the team calldata
> Create team calldata

- _data/handles/redByte.json
This auto-generated PR creates the team redByte
> Create team redByte

- _data/handles/QuillAudits_Elite.json
This auto-generated PR modifies the team QuillAudits_Elite
The request was made by QuillAudits_Team
> Edit team QuillAudits_Elite

- _data/handles/HexxaProtocol.json
This auto-generated PR creates the team HexxaProtocol
> Create team HexxaProtocol

- _data/handles/Bcity.json
This auto-generated PR creates the team Bcity
> Create team Bcity

- _data/handles/xX_360_NoScOpE_Xx.json
This auto-generated PR creates the team xX_360_NoScOpE_Xx
> Create team xX_360_NoScOpE_Xx

- _data/handles/tech22_05.json
This auto-generated PR creates the team tech22_05
> Create team tech22_05

- _data/handles/bytesguard.json
This auto-generated PR modifies the team bytesguard
The request was made by Viraz
> Edit team bytesguard

- _data/handles/CodeBreakerS.json
This auto-generated PR creates the team CodeBreakerS
> Create team CodeBreakerS

- _data/handles/Web3Hunters.json
This auto-generated PR creates the team Web3Hunters
> Create team Web3Hunters

- _data/handles/algiz.json
This auto-generated PR modifies the team algiz
The request was made by vard
> Edit team algiz

- _data/handles/nanofish.json
This auto-generated PR creates the team nanofish
> Create team nanofish

- _data/handles/Sqaure.json
This auto-generated PR creates the team Sqaure
> Create team Sqaure

- _data/handles/ShredSecurity.json
This auto-generated PR creates the team ShredSecurity
> Create team ShredSecurity

- _data/handles/VinciGearHead.json
This auto-generated PR creates the team VinciGearHead
> Create team VinciGearHead

- _data/handles/M00NROCK.json
This auto-generated PR creates the team M00NROCK
> Create team M00NROCK

- _data/handles/TheRealVikings.json
This auto-generated PR creates the team TheRealVikings
> Create team TheRealVikings

- _data/handles/ShredSecurity.json
This auto-generated PR modifies the team ShredSecurity
The request was made by kenzowhitehat
> Edit team ShredSecurity

- _data/handles/KeccakCrew.json
This auto-generated PR creates the team KeccakCrew
> Create team KeccakCrew

- _data/handles/NamG.json
This auto-generated PR creates the team NamG
> Create team NamG

- _data/handles/FinalBossAI.json
This auto-generated PR creates the team FinalBossAI
> Create team FinalBossAI

- _data/handles/Web3Vikings.json
This auto-generated PR modifies the team Web3Vikings
The request was made by 0xdice91
> Edit team Web3Vikings

- _data/handles/0xCartel.json
This auto-generated PR creates the team 0xCartel
> Create team 0xCartel

- _data/handles/piki-nodes.json
This auto-generated PR creates the team piki-nodes
> Create team piki-nodes

- _data/handles/SmartCiphers.json
This auto-generated PR creates the team SmartCiphers
> Create team SmartCiphers

- _data/handles/SmartCiphers.json
This auto-generated PR modifies the team SmartCiphers
The request was made by TactfulCipher
> Edit team SmartCiphers

- _data/handles/Rajesh.json
This auto-generated PR creates the team Rajesh
> Create team Rajesh
