_data/handles/rajatbeladiya.json
This auto-generated PR updates info for warden rajatbeladiya
@rajatbeladiya
=> Update warden rajatbeladiya

_data/handles/topsniper496.json
This auto-generated PR updates info for warden topsniper496
=> Update warden topsniper496

_data/handles/Picodes.json
This auto-generated PR updates info for warden Picodes
@Picodes
=> Update warden Picodes

_data/handles/Saintcode_.json
This auto-generated PR updates info for warden Saintcode_
@Elpacos
=> Update warden Saintcode_

_data/handles/ych18.json
This auto-generated PR updates info for warden ych18
@ych18
=> Update warden ych18

_data/handles/shenwilly.json
This auto-generated PR updates info for warden shenwilly
@shenwilly
=> Update warden shenwilly

_data/handles/Funen.json
This auto-generated PR updates info for warden Funen
@https://github.com/o0Funen0o
=> Update warden Funen

_data/handles/exd0tpy.json
This auto-generated PR updates info for warden exd0tpy
@exd0tpy
=> Update warden exd0tpy

_data/handles/kenzo.json
This auto-generated PR updates info for warden kenzo
@KenzoAgada
=> Update warden kenzo

_data/handles/m_Rassska.json
This auto-generated PR updates info for warden m_Rassska
@Rassska
=> Update warden m_Rassska

_data/handles/Aymen0909.json
This auto-generated PR updates info for warden Aymen0909
@Aymen1001
=> Update warden Aymen0909

_data/handles/jonatascm.json
This auto-generated PR updates info for warden jonatascm
@jonatascm
=> Update warden jonatascm

_data/handles/Foundation.json
=> Update team Foundation

_data/handles/0x4non.json
This auto-generated PR updates info for warden 0x4non
@eugenioclrc
=> Update warden 0x4non

_data/handles/cRat1st0s.json
This auto-generated PR updates info for warden cRat1st0s
=> Update warden cRat1st0s

_data/handles/Soosh.json
This auto-generated PR updates info for warden Soosh
=> Update warden Soosh

_data/handles/0xsanson.json
This auto-generated PR updates info for warden 0xsanson
@0xsanson
=> Update warden 0xsanson

_data/handles/broccolirob.json
This auto-generated PR updates info for warden broccolirob
@broccolirob
=> Update warden broccolirob

_data/handles/c3phas.json
This auto-generated PR updates info for warden c3phas
@c3phas
=> Update warden c3phas

_data/handles/rfa.json
This auto-generated PR updates info for warden rfa
@rfart
=> Update warden rfa

_data/handles/Czar102.json
This auto-generated PR updates info for warden Czar102
@Czar102
=> Update warden Czar102

_data/handles/0xDjango.json
This auto-generated PR updates info for warden 0xDjango
@fatherGoose1
=> Update warden 0xDjango

_data/handles/gogo.json
This auto-generated PR updates info for warden gogo
@https://github.com/GeorgiGeorgiev7
=> Update warden gogo

_data/handles/Treasure-Seeker.json
This auto-generated PR updates info for warden Treasure-Seeker
=> Update warden Treasure-Seeker

_data/handles/Tomio.json
This auto-generated PR updates info for warden Tomio
@https://github.com/TomioWrdn
=> Update warden Tomio

_data/handles/itsmeSTYJ.json
This auto-generated PR updates info for warden itsmeSTYJ
@STYJ
=> Update warden itsmeSTYJ

_data/handles/astrolince.json
This auto-generated PR updates info for warden astrolince
@astrolince
=> Update warden astrolince

_data/handles/UVvirus.json
This auto-generated PR updates info for warden UVvirus
=> Update warden UVvirus

_data/handles/slywaters.json
This auto-generated PR updates info for warden slywaters
=> Update warden slywaters

_data/handles/__141345__.json
Auto-generated PR to register the new warden __141345__
=> Register warden __141345__

_data/handles/naranco.json
Auto-generated PR to register the new warden naranco
=> Register warden naranco

_data/handles/Aldrins6.json
Auto-generated PR to register the new warden Aldrins6
@aj242424
=> Register warden Aldrins6

_data/handles/viking71.json
Auto-generated PR to register the new warden viking71
@vishnuram1999
=> Register warden viking71

_data/handles/codetilda.json
Auto-generated PR to register the new warden codetilda
@codetilda
=> Register warden codetilda

_data/handles/lionblocktx.json
Auto-generated PR to register the new warden lionblocktx
=> Register warden lionblocktx

_data/handles/SeniorKit.json
Auto-generated PR to register the new warden SeniorKit
@kitromanov
=> Register warden SeniorKit

_data/handles/TerrierLover.json
This auto-generated PR updates info for warden TerrierLover
@terrier-lover
=> Update warden TerrierLover

_data/handles/georgypetrov.json
This auto-generated PR updates info for warden georgypetrov
@georgiypetrov
=> Update warden georgypetrov

_data/handles/MiloTruck.json
This auto-generated PR updates info for warden MiloTruck
@MiloTruck
=> Update warden MiloTruck

_data/handles/emmanuelOV.json
Auto-generated PR to register the new warden emmanuelOV
=> Register warden emmanuelOV

_data/handles/0xsi.json
Auto-generated PR to register the new warden 0xsi
@Simon-Busch
=> Register warden 0xsi

_data/handles/Chandr.json
This auto-generated PR updates info for warden Chandr
=> Update warden Chandr

_data/handles/0xefrain.json
This auto-generated PR updates info for warden 0xefrain
@0xefrain
=> Update warden 0xefrain

_data/handles/danb.json
This auto-generated PR updates info for warden danb
@danbinnun1
=> Update warden danb

_data/handles/jayfromthe13th.json
This auto-generated PR updates info for warden jayfromthe13th
=> Update warden jayfromthe13th

_data/handles/okkothejawa.json
This auto-generated PR updates info for warden okkothejawa
@okkothejawa
=> Update warden okkothejawa

_data/handles/peiw.json
This auto-generated PR updates info for warden peiw
@peiwangdb
=> Update warden peiw

_data/handles/0xbeven.json
Auto-generated PR to register the new warden 0xbeven
=> Register warden 0xbeven

_data/handles/5000e12.json
This auto-generated PR updates info for warden 5000e12
=> Update warden 5000e12

_data/handles/dirk_y.json
This auto-generated PR updates info for warden dirk_y
@djb15
=> Update warden dirk_y

_data/handles/0x52.json
This auto-generated PR updates info for warden 0x52
=> Update warden 0x52

_data/handles/0xmint.json
This auto-generated PR updates info for warden 0xmint
@ShadowyTekCoder
=> Update warden 0xmint

_data/handles/0xKitsune.json
This auto-generated PR updates info for warden 0xKitsune
@0xKitsune
=> Update warden 0xKitsune

_data/handles/Amithuddar.json
This auto-generated PR updates info for warden Amithuddar
=> Update warden Amithuddar

_data/handles/GalloDaSballo.json
This auto-generated PR updates info for warden GalloDaSballo
@GalloDaSballo
=> Update warden GalloDaSballo

_data/handles/ballx.json
This auto-generated PR updates info for warden ballx
@balook
=> Update warden ballx

_data/handles/sseefried.json
This auto-generated PR updates info for warden sseefried
@sseefried
=> Update warden sseefried

_data/handles/zzzitron.json
This auto-generated PR updates info for warden zzzitron
@zzzitron
=> Update warden zzzitron

_data/handles/wuestholz.json
This auto-generated PR updates info for warden wuestholz
@wuestholz
=> Update warden wuestholz

_data/handles/rishabh.json
This auto-generated PR updates info for warden rishabh
@0xrishabh
=> Update warden rishabh

_data/handles/Tutturu.json
This auto-generated PR updates info for warden Tutturu
@tuturu-tech
=> Update warden Tutturu

_data/handles/Waze.json
This auto-generated PR updates info for warden Waze
@calmkidd
=> Update warden Waze

_data/handles/Limbooo.json
This auto-generated PR updates info for warden Limbooo
@khalidfsh
=> Update warden Limbooo

_data/handles/Critical.json
This auto-generated PR updates info for warden Critical
@crtcal
=> Update warden Critical

_data/handles/ladboy233.json
This auto-generated PR updates info for warden ladboy233
=> Update warden ladboy233

_data/handles/AmitN.json
This auto-generated PR updates info for warden AmitN
=> Update warden AmitN

_data/handles/0x29A.json
This auto-generated PR adds polygon address for team 0x29A
=> Add address for team 0x29A

_data/handles/hake.json
This auto-generated PR updates info for warden hake
=> Update warden hake

_data/handles/aysha.json
This auto-generated PR updates info for warden aysha
@aysha8665
=> Update warden aysha

_data/handles/JohnSmith.json
This auto-generated PR updates info for warden JohnSmith
=> Update warden JohnSmith

_data/handles/0xNazgul.json
This auto-generated PR updates info for warden 0xNazgul
@0xNazgul
=> Update warden 0xNazgul

_data/handles/asutorufos.json
This auto-generated PR updates info for warden asutorufos
@asutorufo
=> Update warden asutorufos

_data/handles/Haruxe.json
This auto-generated PR updates info for warden Haruxe
@Haruxe
=> Update warden Haruxe

_data/handles/PwnedNoMore.json
This auto-generated PR adds polygon address for team PwnedNoMore
=> Add address for team PwnedNoMore

_data/handles/JosepBove.json
Auto-generated PR to register the new warden JosepBove
@JosepBove
=> Register warden JosepBove

_data/handles/i0001.json
Auto-generated PR to register the new warden i0001
i01001
=> Register warden i0001

_data/handles/Keen_Sheen.json
Auto-generated PR to register the new warden Keen_Sheen
@https://github.com/Keen-Sheen
=> Register warden Keen_Sheen

_data/handles/grGred.json
This auto-generated PR updates info for warden grGred
@grGRed
=> Update warden grGred

_data/handles/0xkatana.json
This auto-generated PR updates info for warden 0xkatana
=> Update warden 0xkatana

_data/handles/reassor.json
This auto-generated PR updates info for warden reassor
=> Update warden reassor

_data/handles/Tadashi.json
This auto-generated PR updates info for warden Tadashi
@htadashi
=> Update warden Tadashi

_data/handles/Kun.json
This auto-generated PR updates info for warden Kun
@https://github.com/nkitlabs
=> Update warden Kun

functions/old-submit-finding.js, gatsby-node.esm.js, src/components/reporter/OldSubmitFindings.js, src/templates/OldReportForm.js
As a last resort, during low coverage.
A new link is available:
=> Re-allow unauthenticated reporting

_data/handles/apostle0x01.json
This auto-generated PR updates info for warden apostle0x01
@apostle0x001
=> Update warden apostle0x01

_data/handles/robee.json
This auto-generated PR updates info for warden robee
=> Update warden robee

_data/handles/onion.json
Auto-generated PR to register the new warden onion
@Aayushman Thapa Magar
=> Register warden onion

_data/handles/lukaprini.json
Auto-generated PR to register the new warden lukaprini
=> Register warden lukaprini

_data/handles/shog00n.json
Auto-generated PR to register the new warden shog00n
=> Register warden shog00n

_data/handles/antonttc.json
This auto-generated PR updates info for warden antonttc
@antoncoding
=> Update warden antonttc

_data/handles/Noah3o6.json
This auto-generated PR updates info for warden Noah3o6
=> Update warden Noah3o6

_data/handles/RedOneN.json
This auto-generated PR updates info for warden RedOneN
=> Update warden RedOneN

_data/handles/Fitraldys.json
This auto-generated PR updates info for warden Fitraldys
@fitraldy
=> Update warden Fitraldys

_data/handles/masterchief.json
This auto-generated PR updates info for warden masterchief
=> Update warden masterchief

_data/handles/mauricio1802.json
This auto-generated PR updates info for warden mauricio1802
@mauricio1802
=> Update warden mauricio1802

_data/handles/tintin.json
This auto-generated PR updates info for warden tintin
@zhongeric
=> Update warden tintin

_data/handles/timur_guvenkaya.json
Auto-generated PR to register the new warden timur_guvenkaya
@timurguvenkaya
=> Register warden timur_guvenkaya

_data/handles/cloudjunky.json
This auto-generated PR updates info for warden cloudjunky
=> Update warden cloudjunky

_data/handles/PPrieditis.json
This auto-generated PR updates info for warden PPrieditis
@PeterisPrieditis
=> Update warden PPrieditis

_data/handles/joestakey.json
This auto-generated PR updates info for warden joestakey
@joestakey
=> Update warden joestakey

_data/handles/svskaushik.json
Auto-generated PR to register the new warden svskaushik
@svskaushik
=> Register warden svskaushik

_data/handles/DMoore.json
Auto-generated PR to register the new warden DMoore
=> Register warden DMoore

_data/handles/ylv.json
Auto-generated PR to register the new warden ylv
=> Register warden ylv

_data/handles/jtseng.json
Auto-generated PR to register the new warden jtseng
=> Register warden jtseng

_data/handles/horsefacts.json
This auto-generated PR updates info for warden horsefacts
@ecmendenhall
=> Update warden horsefacts

_data/handles/Sneakyninja0129.json
Auto-generated PR to register the new warden Sneakyninja0129
=> Register warden Sneakyninja0129

_data/handles/fuloXX.json
Auto-generated PR to register the new warden fuloXX
=> Register warden fuloXX

_data/handles/0xkowloon.json
This auto-generated PR updates info for warden 0xkowloon
@0xkowloon
=> Update warden 0xkowloon

_data/handles/bitorhugo.json
Auto-generated PR to register the new warden bitorhugo
@bitorhugo
=> Register warden bitorhugo

_data/handles/paulbraganza.json
Auto-generated PR to register the new warden paulbraganza
@paulbraganza12
=> Register warden paulbraganza

_data/handles/grrwahrr.json
This auto-generated PR updates info for warden grrwahrr
@grrwahrr
=> Update warden grrwahrr

_data/handles/_Adam.json
This auto-generated PR updates info for warden _Adam
=> Update warden _Adam

_data/handles/async.json
This auto-generated PR updates info for warden async
=> Update warden async

_data/handles/0xHinthunter.json
Auto-generated PR to register the new warden 0xHinthunter
=> Register warden 0xHinthunter

_data/handles/muhammadhassan.json
Auto-generated PR to register the new warden muhammadhassan
@https://github.com/smuhammathassan
=> Register warden muhammadhassan

_data/handles/pedroais.json
This auto-generated PR updates info for warden pedroais
@pedroais
=> Update warden pedroais

_data/handles/Kenshin.json
This auto-generated PR updates info for warden Kenshin
@t-nero
=> Update warden Kenshin

_data/handles/kenta.json
This auto-generated PR updates info for warden kenta
=> Update warden kenta

_data/handles/albincsergo.json
Auto-generated PR to register the new warden albincsergo
@albincsergo
=> Register warden albincsergo

_data/handles/chatch.json
This auto-generated PR updates info for warden chatch
@chatch
=> Update warden chatch

_data/handles/xiaoming90.json
This auto-generated PR updates info for warden xiaoming90
@xiaoming9090
=> Update warden xiaoming90

_data/handles/sashik_eth.json
This auto-generated PR updates info for warden sashik_eth
=> Update warden sashik_eth

_data/handles/philogy.json
This auto-generated PR updates info for warden philogy
@Philogy
=> Update warden philogy

_data/handles/saian.json
This auto-generated PR updates info for warden saian
=> Update warden saian

_data/handles/Doba.json
Auto-generated PR to register the new warden Doba
@HugoGallagher
=> Register warden Doba

_data/handles/ak1.json
This auto-generated PR updates info for warden ak1
@https://github.com/aktech297
=> Update warden ak1

_data/handles/LordHeb.json
This auto-generated PR updates info for warden LordHeb
@Hebx
=> Update warden LordHeb

_data/handles/Ch_301.json
This auto-generated PR updates info for warden Ch_301
@301Ch
=> Update warden Ch_301

_data/handles/seblw.json
Auto-generated PR to register the new warden seblw
@seblw
=> Register warden seblw

_data/handles/UnusualTurtle.json
This auto-generated PR updates info for warden UnusualTurtle
@sraihandzaky
=> Update warden UnusualTurtle

_data/handles/datapunk.json
This auto-generated PR updates info for warden datapunk
=> Update warden datapunk

_data/handles/gzeon.json
This auto-generated PR updates info for warden gzeon
@gzeoneth
=> Update warden gzeon

_data/handles/Nethermind.json
This auto-generated PR adds polygon address for team Nethermind
=> Add address for team Nethermind

_data/handles/BowTiedWardens.json
This auto-generated PR adds polygon address for team BowTiedWardens
=> Add address for team BowTiedWardens

_data/handles/0xf15ers.json
This auto-generated PR adds polygon address for team 0xf15ers
=> Add address for team 0xf15ers

_data/handles/saneryee.json
This auto-generated PR updates info for warden saneryee
@gsangeryee
=> Update warden saneryee

_data/handles/DecorativePineapple.json
This auto-generated PR updates info for warden DecorativePineapple
@DecorativePineapple
=> Update warden DecorativePineapple

_data/handles/rbserver.json
Auto-generated PR to register the new warden rbserver
=> Register warden rbserver

_data/handles/DimitarDimitrov.json
Auto-generated PR to register the new warden DimitarDimitrov
@dplamenov
=> Register warden DimitarDimitrov

_data/handles/0x09GTO.json
Auto-generated PR to register the new warden 0x09GTO
=> Register warden 0x09GTO

_data/handles/0xriver.json
This auto-generated PR updates info for warden 0xriver
=> Update warden 0xriver

_data/handles/Vexjon.json
Auto-generated PR to register the new warden Vexjon
=> Register warden Vexjon

_data/handles/brgltd.json
Auto-generated PR to register the new warden brgltd
@brgltd
=> Register warden brgltd

_data/handles/caventa.json
Auto-generated PR to register the new warden caventa
=> Register warden caventa

_data/handles/n0tspam.json
This auto-generated PR updates info for warden n0tspam
@n0tspam
=> Update warden n0tspam

_data/handles/shw.json
This auto-generated PR updates info for warden shw
@x9453
=> Update warden shw

_data/handles/dannyphantom.json, _data/handles/danykillyou.json
Auto-generated PR to register the new warden danykillyou
=> Register warden danykillyou

_data/handles/calebbweaver.json
Auto-generated PR to register the new warden calebbweaver
=> Register warden calebbweaver

_data/handles/shri4net.json
This auto-generated PR updates info for warden shri4net
@shri4net
=> Update warden shri4net

_data/handles/Dustz.json
Auto-generated PR to register the new warden Dustz
@maborri
=> Register warden Dustz

_data/handles/M001.json
Auto-generated PR to register the new warden M001
=> Register warden M001

_data/handles/Bruhhh.json
This auto-generated PR updates info for warden Bruhhh
=> Update warden Bruhhh

_data/handles/kyteg.json
Auto-generated PR to register the new warden kyteg
@kyteg
=> Register warden kyteg

_data/handles/cogitoergosumsw.json
This auto-generated PR updates info for warden cogitoergosumsw
@cogitoergosumsw
=> Update warden cogitoergosumsw

_data/handles/sahar.json
This auto-generated PR updates info for warden sahar
=> Update warden sahar

_data/handles/Kong.json
This auto-generated PR updates info for warden Kong
=> Update warden Kong

_data/handles/Saw-mon_and_Natalie.json
This auto-generated PR updates info for warden Saw-mon_and_Natalie
@Saw-mon-and-Natalie
=> Update warden Saw-mon_and_Natalie

_data/handles/DoryZaih.json
Auto-generated PR to register the new warden DoryZaih
=> Register warden DoryZaih

_data/handles/benbaessler.json
Auto-generated PR to register the new warden benbaessler
@benbaessler
=> Register warden benbaessler

_data/handles/0x040.json
Auto-generated PR to register the new warden 0x040
=> Register warden 0x040

_data/handles/august.json
Auto-generated PR to register the new warden august
@augustjest
=> Register warden august

_data/handles/hubble.json
This auto-generated PR adds polygon address for team hubble
=> Add address for team hubble

_data/handles/bbrho.json
This auto-generated PR updates info for warden bbrho
@https://github.com/bbrho
=> Update warden bbrho

_data/handles/wilytama.json
Auto-generated PR to register the new warden wilytama
=> Register warden wilytama

_data/handles/donosonaumczuk.json
Auto-generated PR to register the new warden donosonaumczuk
@donosonaumczuk
=> Register warden donosonaumczuk

_data/handles/Loggy.json
Auto-generated PR to register the new warden Loggy
@Loggy
=> Register warden Loggy

_data/handles/panprog.json
Auto-generated PR to register the new warden panprog
@panprog
=> Register warden panprog

_data/handles/Chinmay.json
Auto-generated PR to register the new warden Chinmay
@Chinmay-F
=> Register warden Chinmay

_data/handles/jyt.json
Auto-generated PR to register the new warden jyt
=> Register warden jyt

_data/handles/hack3r-0m.json
This auto-generated PR updates info for warden hack3r-0m
@hack3r-0m
=> Update warden hack3r-0m

_data/handles/8olidity.json
This auto-generated PR updates info for warden 8olidity
=> Update warden 8olidity

_data/handles/hrishibhat.json
This auto-generated PR updates info for warden hrishibhat
@hrishibhat
=> Update warden hrishibhat

_data/handles/karanctf.json
Auto-generated PR to register the new warden karanctf
=> Register warden karanctf

_data/handles/BouSalman.json
This auto-generated PR updates info for warden BouSalman
@https://github.com/bousalman
=> Update warden BouSalman

_data/handles/s3cunda.json
This auto-generated PR updates info for warden s3cunda
@s3cunda
=> Update warden s3cunda

_data/handles/riptide.json
Auto-generated PR to register the new warden riptide
=> Register warden riptide

_data/handles/kobyhall.json
Auto-generated PR to register the new warden kobyhall
=> Register warden kobyhallx

_data/handles/arcoun.json
Auto-generated PR to register the new warden arcoun
=> Register warden arcoun

_data/handles/Kulk0.json
This auto-generated PR updates info for warden Kulk0
@Kuly14
=> Update warden Kulk0

_data/handles/pedr02b2.json
This auto-generated PR updates info for warden pedr02b2
@02b2
=> Update warden pedr02b2

_data/handles/pablitxn.json
Auto-generated PR to register the new warden pablitxn
@pablitxn
=> Register warden pablitxn

_data/handles/MikeDougherty.json
Auto-generated PR to register the new warden MikeDougherty
@doughertym
=> Register warden MikeDougherty

_data/handles/BenjaminSalon.json
Auto-generated PR to register the new warden BenjaminSalon
@benjaminsalon
=> Register warden BenjaminSalon

_data/handles/Kamil-Chmielewski.json
Auto-generated PR to register the new warden Kamil-Chmielewski
@ChmielewskiKamil
=> Register warden Kamil-Chmielewski

_data/handles/cmichel.json
This auto-generated PR updates info for warden cmichel
@MrToph
=> Update warden cmichel

_data/handles/RafaTatay.json, _data/handles/tay054.json
Auto-generated PR to register the new warden RafaTatay
@RafaTatay
=> Register warden tay054

_data/handles/eighty.json
Auto-generated PR to register the new warden eighty
=> Register warden eighty

_data/handles/lcfr.json, _data/handles/lcfr_eth.json
Auto-generated PR to register the new warden lcfr
=> Register warden lcfr_eth

_data/handles/ayeslick.json
This auto-generated PR updates info for warden ayeslick
=> Update warden ayeslick

_data/handles/ronn1e.json, _data/handles/ronnyx2017.json
Auto-generated PR to register the new warden ronnyx2017
=> Register warden ronnyx2017

_data/handles/devtooligan.json
This auto-generated PR updates info for warden devtooligan
@devtooligan
=> Update warden devtooligan

_data/handles/bardamu.json
This auto-generated PR updates info for warden bardamu
=> Update warden bardamu

_data/handles/ulad.json
Auto-generated PR to register the new warden ulad
=> Register warden ulad

_data/handles/Kyosi.json
Auto-generated PR to register the new warden Kyosi
=> Register warden Kyosi

_data/handles/skavans.json
Auto-generated PR to register the new warden skavans
=> Register warden skavans

_data/handles/Kthere.json
This auto-generated PR updates info for warden Kthere
@KalpitaMandal
=> Update warden Kthere

_data/handles/skoorch.json
This auto-generated PR updates info for warden skoorch
=> Update warden skoorch

_data/handles/Twpony.json
This auto-generated PR updates info for warden Twpony
@twpony
=> Update warden Twpony

_data/handles/Jujic.json
This auto-generated PR updates info for warden Jujic
=> Update warden Jujic

_data/handles/0xalpharush.json
This auto-generated PR updates info for warden 0xalpharush
@0xalpharush
=> Update warden 0xalpharush

_data/handles/PaludoX0.json
Auto-generated PR to register the new warden PaludoX0
=> Register warden PaludoX0

_data/handles/jadechip.json
Auto-generated PR to register the new warden jadechip
@jadechip
=> Register warden jadechip

_data/handles/Bahurum.json
This auto-generated PR updates info for warden Bahurum
@bahurum
=> Update warden Bahurum

_data/handles/cryptonue.json
Auto-generated PR to register the new warden cryptonue
=> Register warden cryptonue

_data/handles/SooYa.json
This auto-generated PR updates info for warden SooYa
@Sleepless19
=> Update warden SooYa

_data/handles/tomtsaoao.json
This auto-generated PR updates info for warden tomtsaoao
=> Update warden tomtsaoao

_data/handles/TheBearJew.json
Auto-generated PR to register the new warden TheBearJew
=> Register warden TheBearJew

_data/handles/CryptoMartian.json
Added the moralis id for the warden
=> Update moralis id for cryptomartian

_data/handles/DevABDee.json
Auto-generated PR to register the new warden DevABDee
@DevABDee
=> Register warden DevABDee

_data/handles/Gee.json
Auto-generated PR to register the new warden Gee
@gee
=> Register warden Gee

_data/handles/seanamani.json
This auto-generated PR updates info for warden seanamani
@seanamani.sa@gmail.com
=> Update warden seanamani

_data/handles/greedythib.json
Auto-generated PR to register the new warden greedythib
=> Register warden greedythib

_data/handles/RustyRabbit.json
This auto-generated PR updates info for warden RustyRabbit
=> Update warden RustyRabbit

_data/handles/p_crypt0.json
This auto-generated PR updates info for warden p_crypt0
=> Update warden p_crypt0

_data/handles/plotchy.json
This auto-generated PR updates info for warden plotchy
@plotchy
=> Update warden plotchy

_data/handles/Jmaxmanblue.json
Auto-generated PR to register the new warden Jmaxmanblue
=> Register warden Jmaxmanblue

_data/handles/yeabu.json
This auto-generated PR updates info for warden yeabu
@yeabu369
=> Update warden yeabu

_data/handles/Piratica21.json
Auto-generated PR to register the new warden Piratica21
=> Register warden Piratica21

_data/handles/softandwet.json
Auto-generated PR to register the new warden softandwet
=> Register warden softandwet

_data/handles/luckypanda.json
Auto-generated PR to register the new warden luckypanda
@https://github.com/jte0711
=> Register warden luckypanda

_data/handles/Artriy.json
Auto-generated PR to register the new warden Artriy
@Artriy
=> Register warden Artriy

_data/handles/velvetee.json
Auto-generated PR to register the new warden velvetee
=> Register warden velvetee

_data/handles/Migue.json
Auto-generated PR to register the new warden Migue
@MigueTripi
=> Register warden Migue

_data/handles/putricio.json
Auto-generated PR to register the new warden putricio
@putricio01
=> Register warden putricio

_data/handles/xpriment626.json
This auto-generated PR updates info for warden xpriment626
@xpriment626
=> Update warden xpriment626

_data/handles/RoiEvenHaim.json
This auto-generated PR updates info for warden RoiEvenHaim
=> Update warden RoiEvenHaim

_data/handles/Maxime.json
Auto-generated PR to register the new warden Maxime
@skimaharvey
=> Register warden Maxime

_data/handles/Titi.json
Auto-generated PR to register the new warden Titi
@thermohaline
=> Register warden Titi

_data/handles/duc.json
Auto-generated PR to register the new warden duc
@huuducst
=> Register warden duc

_data/handles/CodingNameKiki.json
Auto-generated PR to register the new warden CodingNameKiki
=> Register warden CodingNameKiki

_data/handles/BastionSCH.json
Auto-generated PR to register the new warden BastionSCH
=> Register warden BastionSCH

_data/handles/h3ck.json
Auto-generated PR to register the new warden h3ck
=> Register warden h3ck

_data/handles/vyorkin.json
This auto-generated PR updates info for warden vyorkin
@vyorkin
=> Update warden vyorkin

_data/handles/trx314.json
Auto-generated PR to register the new warden trx314
=> Register warden trx314

_data/handles/0xDanielC.json
Auto-generated PR to register the new warden 0xDanielC
@DanielCawley
=> Register warden 0xDanielC

_data/handles/Otaiki.json
Auto-generated PR to register the new warden Otaiki
@Otaiki1
=> Register warden Otaiki

_data/handles/eklipz.json
Auto-generated PR to register the new warden eklipz
=> Register warden eklipz

_data/handles/jayphbee.json
This auto-generated PR updates info for warden jayphbee
@calldata
=> Update warden jayphbee

_data/handles/faulcrox.json
Auto-generated PR to register the new warden faulcrox
@yashtotla
=> Register warden faulcrox

_data/handles/abdlaziz_s.json
Auto-generated PR to register the new warden abdlaziz_s
@abdlazizs
=> Register warden abdlaziz_s

_data/handles/2997ms.json
Auto-generated PR to register the new warden 2997ms
@2997ms
=> Register warden 2997ms

_data/handles/blockdev.json
This auto-generated PR updates info for warden blockdev
@0xbok
=> Update warden blockdev

_data/handles/babpls.json
Auto-generated PR to register the new warden babpls
=> Register warden babpls

_data/handles/jojo.json
Auto-generated PR to register the new warden jojo
@unyijojo
=> Register warden jojo

_data/handles/obront.json
This auto-generated PR updates info for warden obront
@zobront
=> Update warden obront

_data/handles/msarosh1.json, _data/handles/octo.json
Auto-generated PR to register the new warden msarosh1
@msarosh1
=> Register warden octo

_data/handles/wira.json
Auto-generated PR to register the new warden wira
=> Register warden wira

_data/handles/ye0lde.json
This auto-generated PR updates info for warden ye0lde
@ye0lde
=> Update warden ye0lde

_data/handles/navinavu.json
This auto-generated PR updates info for warden navinavu
@NaviNavu
=> Update warden navinavu

_data/handles/Ruhum.json
This auto-generated PR updates info for warden Ruhum
@0xruhum
=> Update warden Ruhum

_data/handles/4cce1er.json
Auto-generated PR to register the new warden 4cce1er
=> Register warden 4cce1er

_data/handles/Keg.json
Auto-generated PR to register the new warden Keg
=> Register warden Keg

_data/handles/Throne6g.json, _data/handles/throne6g.json
Auto-generated PR to register the new warden throne6g
@Throne6G
=> Register warden throne6g

_data/handles/gmhacker.json
Auto-generated PR to register the new warden gmhacker
@goncaloMagalhaes
=> Register warden gmhacker

_data/handles/dzhawsh.json
Auto-generated PR to register the new warden dzhawsh
=> Register warden dzhawsh

_data/handles/immeas.json
Auto-generated PR to register the new warden immeas
=> Register warden immeas

_data/handles/codemedici.json
Auto-generated PR to register the new warden codemedici
=> Register warden codemedici

_data/handles/0xWill.json
Auto-generated PR to register the new warden 0xWill
@https://github.com/WillSchiller
=> Register warden 0xWill

_data/handles/leonardoalt.json
This auto-generated PR updates info for warden leonardoalt
@leonardoalt
=> Update warden leonardoalt

_data/handles/Dark_Meta.json
Auto-generated PR to register the new warden Dark_Meta
@Crypto-Snow
=> Register warden Dark_Meta

_data/handles/_mundhrakeshav.json
Auto-generated PR to register the new warden _mundhrakeshav
@mundhrakeshav
=> Register warden _mundhrakeshav

_data/handles/M0ndoHEHE.json
This auto-generated PR updates info for warden M0ndoHEHE
@0xYoshi
=> Update warden M0ndoHEHE

_data/handles/littlefrankie.json
This auto-generated PR updates info for warden littlefrankie
=> Update warden littlefrankie

_data/handles/frangio.json
This auto-generated PR updates info for warden frangio
@frangio
=> Update warden frangio

_data/handles/jimmix.json
This auto-generated PR updates info for warden jimmix
@richance
=> Update warden jimmix

_data/handles/parashar.json
This auto-generated PR updates info for warden parashar
@0xparashar
=> Update warden parashar

_data/handles/GiveMeTestEther.json
This auto-generated PR updates info for warden GiveMeTestEther
=> Update warden GiveMeTestEther

_data/handles/bearonbike.json
This auto-generated PR updates info for warden bearonbike
=> Update warden bearonbike

_data/handles/byndooa.json
This auto-generated PR updates info for warden byndooa
@https://github.com/danogurtsov
=> Update warden byndooa

_data/handles/khatakey.json
Auto-generated PR to register the new warden khatakey
=> Register warden khatakey

_data/handles/kmt.json
Auto-generated PR to register the new warden kmt
@weev3
=> Register warden kmt

_data/handles/TrungOre.json
This auto-generated PR updates info for warden TrungOre
@WelToHackerLand
=> Update warden TrungOre

_data/handles/aspi.json
Auto-generated PR to register the new warden aspi
=> Register warden aspi

_data/handles/Haipls.json
Auto-generated PR to register the new warden Haipls
=> Register warden Haipls

_data/handles/ashiq0x01.json
Auto-generated PR to register the new warden ashiq0x01
=> Register warden ashiq0x01

_data/handles/Knaky.json
Auto-generated PR to register the new warden Knaky
=> Register warden Knaky

_data/handles/medikko.json
Auto-generated PR to register the new warden medikko
@Medikko
=> Register warden medikko

_data/handles/JDeryl.json
This auto-generated PR updates info for warden JDeryl
@mjariruddin
=> Update warden JDeryl

_data/handles/Chxpz.json
Auto-generated PR to register the new warden Chxpz
@@Chxpz
=> Register warden Chxpz

_data/handles/Moon.json
Auto-generated PR to register the new warden Moon
@valour01
=> Register warden Moon

_data/handles/owenthurm.json
Auto-generated PR to register the new warden owenthurm
@owenThurm
=> Register warden owenthurm

_data/handles/scauditor_eth.json
Auto-generated PR to register the new warden scauditor_eth
=> Register warden scauditor_eth

_data/handles/Scocco.json
This auto-generated PR updates info for warden Scocco
@cfsdes
=> Update warden Scocco

_data/handles/zer0dot.json
This auto-generated PR updates info for warden zer0dot
@Zer0dot
=> Update warden zer0dot

_data/handles/karmacoma.json
This auto-generated PR updates info for warden karmacoma
@karmacoma-eth
=> Update warden karmacoma

_data/handles/sepirothx.json
Auto-generated PR to register the new warden sepirothx
@sepiroth-x
=> Register warden sepirothx

_data/handles/Demon_Skorosti.json
Auto-generated PR to register the new warden Demon_Skorosti
@DemonSk
=> Register warden Demon_Skorosti

_data/handles/certora.json
This auto-generated PR updates info for warden certora
@itay25433@gmail.com
=> Update warden certora

_data/handles/TomFrenchBlockchain.json
This auto-generated PR updates info for warden TomFrenchBlockchain
@tomafrench
=> Update warden TomFrenchBlockchain

_data/handles/bharg4v.json
This auto-generated PR updates info for warden bharg4v
@Bhargava-krishna
=> Update warden bharg4v

_data/handles/vagebond.json
Auto-generated PR to register the new warden vagebond
=> Register warden vagebond

_data/handles/a12jmx.json
This auto-generated PR updates info for warden a12jmx
@a12jmx
=> Update warden a12jmx

_data/handles/ggballas.json
Auto-generated PR to register the new warden ggballas
=> Register warden ggballas

_data/handles/T_.json
Auto-generated PR to register the new warden T_
=> Register warden T_

_data/handles/Metatron.json
This auto-generated PR updates info for warden Metatron
@WhiteMetatron
=> Update warden Metatron

_data/handles/jwood.json
Auto-generated PR to register the new warden jwood
=> Register warden jwood

_data/handles/aah.json
Auto-generated PR to register the new warden aah
@harperaa
=> Register warden aah

_data/handles/zeesaw.json
This auto-generated PR updates info for warden zeesaw
=> Update warden zeesaw

_data/handles/jamesluther.json
Auto-generated PR to register the new warden jamesluther
=> Register warden jamesluther

_data/handles/vlad_bochok.json
This auto-generated PR updates info for warden vlad_bochok
@vladbochok
=> Update warden vlad_bochok

_data/handles/MoDeFi.json
Auto-generated PR to register the new warden MoDeFi
@mojtb
=> Register warden MoDeFi

_data/handles/jok3r.json
Auto-generated PR to register the new warden jok3r
=> Register warden jok3r

_data/handles/usmannk.json
Auto-generated PR to register the new warden usmannk
@usmannk
=> Register warden usmannk

_data/handles/b1gw00d.json
Auto-generated PR to register the new warden b1gw00d
=> Register warden b1gw00d

_data/handles/mayo.json
This auto-generated PR updates info for warden mayo
=> Update warden mayo

_data/handles/rvierdiiev.json
Auto-generated PR to register the new warden rvierdiiev
=> Register warden rvierdiiev

_data/handles/SAFISEC.json
Auto-generated PR to register the new warden SAFISEC
@SaFiSec
=> Register warden SAFISEC

_data/handles/slippopz.json
Auto-generated PR to register the new warden slippopz
=> Register warden slippopz

_data/handles/fulminatingmoat.json
Auto-generated PR to register the new warden fulminatingmoat
@fulminatingmoat
=> Register warden fulminatingmoat

_data/handles/raz0r.json
This auto-generated PR updates info for warden raz0r
@Raz0r
=> Update warden raz0r

_data/handles/themystery.json
This auto-generated PR updates info for warden themystery
@iamsahu
=> Update warden themystery

_data/handles/d3e4.json
Auto-generated PR to register the new warden d3e4
=> Register warden d3e4

_data/handles/yixxas.json
Auto-generated PR to register the new warden yixxas
@yixxas
=> Register warden yixxas

_data/handles/LeoS.json
Auto-generated PR to register the new warden LeoS
@LeoSchyns
=> Register warden LeoS

_data/handles/0xSlime.json
Auto-generated PR to register the new warden 0xSlime
@benleim
=> Register warden 0xSlime

_data/handles/Morph.json
This auto-generated PR updates info for warden Morph
@0xMorph
=> Update warden Morph

_data/handles/Peep.json
This auto-generated PR updates info for warden Peep
@xBalbinus
=> Update warden Peep

_data/handles/yac.json
This auto-generated PR creates the team yac
=> Create team yac

_data/handles/ch0bu.json
Auto-generated PR to register the new warden ch0bu
=> Register warden ch0bu

_data/handles/freeatnet.json
Auto-generated PR to register the new warden freeatnet
=> Register warden freeatnet

_data/handles/Saberdz.json
Auto-generated PR to register the new warden Saberdz
=> Register warden Saberdz

_data/handles/sp4c3m4n.json
Auto-generated PR to register the new warden sp4c3m4n
@sp4c3m4n
=> Register warden sp4c3m4n

_data/handles/sy100x.json
Auto-generated PR to register the new warden sy100x
@sy100x
=> Register warden sy100x

_data/handles/Diraco.json
Auto-generated PR to register the new warden Diraco
@iamdiraco
=> Register warden Diraco

_data/handles/totomanov.json
Auto-generated PR to register the new warden totomanov
@totomanov
=> Register warden totomanov

_data/handles/1cf.json
Auto-generated PR to register the new warden 1cf
@cfiestas6
=> Register warden 1cf

_data/handles/iamwhitelights.json
Auto-generated PR to register the new warden iamwhitelights
@johnnyshankman
=> Register warden iamwhitelights

_data/handles/yasir.json
Auto-generated PR to register the new warden yasir
=> Register warden yasir

_data/handles/chrisdior4.json
Auto-generated PR to register the new warden chrisdior4
=> Register warden chrisdior4

_data/handles/epizeuxius.json
Auto-generated PR to register the new warden epizeuxius
=> Register warden epizeuxius

_data/handles/newfork01.json
Auto-generated PR to register the new warden newfork01
=> Register warden newfork01

_data/handles/SaeedAlipoor01988.json
Auto-generated PR to register the new warden SaeedAlipoor01988
@https://github.com/saeedalipoorcom
=> Register warden SaeedAlipoor01988

_data/handles/JansenC.json
Auto-generated PR to register the new warden JansenC
=> Register warden JansenC

_data/handles/paribus.json
Auto-generated PR to register the new warden paribus
=> Register warden paribus

_data/handles/yash90.json
This auto-generated PR updates info for warden yash90
@kumaryash90
=> Update warden yash90

_data/handles/bengalaQ.json
This auto-generated PR updates info for warden bengalaQ
=> Update warden bengalaQ

_data/handles/bw.json
This auto-generated PR updates info for warden bw
@bernard-wagner
=> Update warden bw

_data/handles/Cr4ckM3.json
This auto-generated PR updates info for warden Cr4ckM3
@lmy375
=> Update warden Cr4ckM3

_data/handles/The_GUILD.json
This auto-generated PR creates the team The_GUILD
=> Create team The_GUILD

_data/handles/h4x0rs.json
This auto-generated PR creates the team h4x0rs
=> Create team h4x0rs

_data/handles/dic0de.json
This auto-generated PR updates info for warden dic0de
@dic0de
=> Update warden dic0de

_data/handles/zkhorse.json
This auto-generated PR adds polygon address for team zkhorse
=> Add address for team zkhorse

_data/handles/stevenlriv.json
Auto-generated PR to register the new warden stevenlriv
@stevenlriv
=> Register warden stevenlriv

_data/handles/Nsecv.json
Auto-generated PR to register the new warden Nsecv
=> Register warden Nsecv

_data/handles/beelzebufo.json
Auto-generated PR to register the new warden beelzebufo
=> Register warden beelzebufo

_data/handles/hails.json
Auto-generated PR to register the new warden hails
=> Register warden hails

_data/handles/Lead_Belly.json
Auto-generated PR to register the new warden Lead_Belly
=> Register warden Lead_Belly

_data/handles/ltyu.json
Auto-generated PR to register the new warden ltyu
@ltyu
=> Register warden ltyu

_data/handles/SinceJuly.json
Auto-generated PR to register the new warden SinceJuly
=> Register warden SinceJuly

_data/handles/0xhunter.json
Auto-generated PR to register the new warden 0xhunter
=> Register warden 0xhunter

_data/handles/code46ash.json
Auto-generated PR to register the new warden code46ash
=> Register warden code46ash

_data/handles/Ephraim.json
This auto-generated PR updates info for warden Ephraim
@Ephraim-nonso
=> Update warden Ephraim

_data/handles/BRB.json
Auto-generated PR to register the new warden BRB
@craftysecurity
=> Register warden BRB

_data/handles/EthLedger.json
This auto-generated PR updates info for warden EthLedger
@finnvm
=> Update warden EthLedger

_data/handles/exp7l.json
Auto-generated PR to register the new warden exp7l
@exp7l
=> Register warden exp7l

_data/handles/urek.json
Auto-generated PR to register the new warden urek
=> Register warden urek

_data/handles/RaymondFam.json
Auto-generated PR to register the new warden RaymondFam
@raymondfam
=> Register warden RaymondFam

_data/handles/Josiah.json
Auto-generated PR to register the new warden Josiah
@https://github.com/joshfam
=> Register warden Josiah

_data/handles/shark.json
Auto-generated PR to register the new warden shark
@Sharkri
=> Register warden shark

_data/handles/StefanAndrei.json
Auto-generated PR to register the new warden StefanAndrei
@stefanandy
=> Register warden StefanAndrei

_data/handles/bankisan.json
Auto-generated PR to register the new warden bankisan
=> Register warden bankisan

_data/handles/gurri.json
Auto-generated PR to register the new warden gurri
=> Register warden gurri

_data/handles/aidank1234.json
Auto-generated PR to register the new warden aidank1234
@aidank1234
=> Register warden aidank1234

_data/handles/coder_rancho.json
Auto-generated PR to register the new warden coder_rancho
@coder-rancho
=> Register warden coder_rancho

_data/handles/Boogeyman.json
Auto-generated PR to register the new warden Boogeyman
@Boogeyboy
=> Register warden Boogeyman

_data/handles/w0Lfrum.json
Auto-generated PR to register the new warden w0Lfrum
@supernova8649
=> Register warden w0Lfrum

_data/handles/mrkokrm.json
Auto-generated PR to register the new warden mrkokrm
@markosneiders
=> Register warden mrkokrm

_data/handles/Predator.json
Auto-generated PR to register the new warden Predator
@APIScorcher
=> Register warden Predator

_data/handles/Rui.json
Auto-generated PR to register the new warden Rui
=> Register warden Rui

_data/handles/0xonny.json
Auto-generated PR to register the new warden 0xonny
=> Register warden 0xonny

_data/handles/nvmdma.json
Auto-generated PR to register the new warden nvmdma
=> Register warden nvmdma

_data/handles/Beched.json
Auto-generated PR to register the new warden Beched
@beched
=> Register warden Beched

_data/handles/R2.json
Auto-generated PR to register the new warden R2
=> Register warden R2

_data/handles/B2.json
Auto-generated PR to register the new warden B2
=> Register warden B2

_data/handles/matcha.json
Auto-generated PR to register the new warden matcha
@pragyachik
=> Register warden matcha

_data/handles/Shishigami.json
Auto-generated PR to register the new warden Shishigami
=> Register warden Shishigami

_data/handles/Allarious.json
Auto-generated PR to register the new warden Allarious
@Allarious
=> Register warden Allarious

_data/handles/robertkodra.json
Auto-generated PR to register the new warden robertkodra
@robertkodra
=> Register warden robertkodra

_data/handles/udayj.json
Auto-generated PR to register the new warden udayj
@udayj
=> Register warden udayj

_data/handles/asdqweboq.json
Auto-generated PR to register the new warden asdqweboq
=> Register warden asdqweboq

_data/handles/Polandia94.json
Auto-generated PR to register the new warden Polandia94
@polandia94
=> Register warden Polandia94

_data/handles/Margaret.json
Auto-generated PR to register the new warden Margaret
=> Register warden Margaret

_data/handles/tonisives.json
Auto-generated PR to register the new warden tonisives
@tonisives
=> Register warden tonisives

_data/handles/ChristianKuri.json
Auto-generated PR to register the new warden ChristianKuri
@ChristianKuri
=> Register warden ChristianKuri

_data/handles/__acidicHydrogen__.json
Auto-generated PR to register the new warden __acidicHydrogen__
@ankurdubey521
=> Register warden __acidicHydrogen__

_data/handles/NVZ.json
Auto-generated PR to register the new warden NVZ
=> Register warden NVZ

_data/handles/harisbaig.json
Auto-generated PR to register the new warden harisbaig
@mharisbaig
=> Register warden harisbaig

_data/handles/VrONTg.json
Auto-generated PR to register the new warden VrONTg
=> Register warden VrONTg

_data/handles/cducrest.json
Auto-generated PR to register the new warden cducrest
@cducrest
=> Register warden cducrest

_data/handles/Dionysus.json
Auto-generated PR to register the new warden Dionysus
@FinagleLord
=> Register warden Dionysus

_data/handles/kadejo.json
Auto-generated PR to register the new warden kadejo
=> Register warden kadejo

_data/handles/Ada.json
Auto-generated PR to register the new warden Ada
=> Register warden Ada

_data/handles/ali_shehab.json
Auto-generated PR to register the new warden ali_shehab
=> Register warden ali_shehab

_data/handles/Kresh.json
Auto-generated PR to register the new warden Kresh
@1kresh
=> Register warden Kresh

_data/handles/elawbek.json
Auto-generated PR to register the new warden elawbek
=> Register warden elawbek

_data/handles/DrazenP.json
Auto-generated PR to register the new warden DrazenP
=> Register warden DrazenP

_data/handles/Tifokk.json
Auto-generated PR to register the new warden Tifokk
=> Register warden Tifokk

_data/handles/spark.json
Auto-generated PR to register the new warden spark
=> Register warden spark

_data/handles/enckrish.json
Auto-generated PR to register the new warden enckrish
@enckrish
=> Register warden enckrish

_data/handles/lyle.json
Auto-generated PR to register the new warden lyle
@kfukue
=> Register warden lyle

_data/handles/Rock888.json
Auto-generated PR to register the new warden Rock888
=> Register warden Rock888

_data/handles/s1r1us.json
Auto-generated PR to register the new warden s1r1us
@msrkp
=> Register warden s1r1us

_data/handles/ne0n.json
Auto-generated PR to register the new warden ne0n
=> Register warden ne0n

_data/handles/Weekend16.json
Auto-generated PR to register the new warden Weekend16
=> Register warden Weekend16

_data/handles/Sandwich.json
Auto-generated PR to register the new warden Sandwich
@SandwichDev
=> Register warden Sandwich

_data/handles/louhk.json
Auto-generated PR to register the new warden louhk
=> Register warden louhk

_data/handles/cranfo.json
Auto-generated PR to register the new warden cranfo
@festevezz
=> Register warden cranfo

_data/handles/ampak.json
Auto-generated PR to register the new warden ampak
=> Register warden ampak

_data/handles/peachtea.json
Auto-generated PR to register the new warden peachtea
@icedpeachtea
=> Register warden peachtea

_data/handles/emrekocak.json
Auto-generated PR to register the new warden emrekocak
=> Register warden emrekocak

_data/handles/wuwe1.json
This auto-generated PR updates info for warden wuwe1
@wuwe1
=> Update warden wuwe1

_data/handles/cryptostellar5.json
Auto-generated PR to register the new warden cryptostellar5
=> Register warden cryptostellar5

_data/handles/B353N.json
Auto-generated PR to register the new warden B353N
=> Register warden B353N

_data/handles/hxzy.json
Auto-generated PR to register the new warden hxzy
@xzy012
=> Register warden hxzy

_data/handles/Quiark.json
Auto-generated PR to register the new warden Quiark
@quiark
=> Register warden Quiark

_data/handles/easy_peasy.json
Auto-generated PR to register the new warden easy_peasy
=> Register warden easy_peasy

_data/handles/MasterCookie.json
Auto-generated PR to register the new warden MasterCookie
=> Register warden MasterCookie

_data/handles/0x85102.json
Auto-generated PR to register the new warden 0x85102
=> Register warden 0x85102

_data/handles/bill.json
This auto-generated PR updates info for warden bill
@StillFantastic
=> Update warden bill

_data/handles/LeoGold.json
This auto-generated PR updates info for warden LeoGold
@falilah
=> Update warden LeoGold

_data/handles/Diana.json
Auto-generated PR to register the new warden Diana
=> Register warden Diana

_data/handles/kris.json
Auto-generated PR to register the new warden kris
=> Register warden kris

_data/handles/Barichek.json
Auto-generated PR to register the new warden Barichek
=> Register warden Barichek

_data/handles/V_B.json
This auto-generated PR creates the team V_B
=> Create team V_B

_data/handles/StevenL.json
Auto-generated PR to register the new warden StevenL
=> Register warden StevenL

_data/handles/riczard.json
Auto-generated PR to register the new warden riczard
=> Register warden riczard

_data/handles/marce1993.json
Auto-generated PR to register the new warden marce1993
@marce1994
=> Register warden marce1993

_data/handles/archiepiket.json
Auto-generated PR to register the new warden archiepiket
=> Register warden archiepiket

_data/handles/petersspetrov.json
Auto-generated PR to register the new warden petersspetrov
@SvetoslavGochev
=> Register warden petersspetrov

_data/handles/millersplanet.json
Auto-generated PR to register the new warden millersplanet
@JuanXavier
=> Register warden millersplanet

_data/handles/Lockwu.json
Auto-generated PR to register the new warden Lockwu
@Lockwu6749
=> Register warden Lockwu

_data/handles/bountybunny.json
Auto-generated PR to register the new warden bountybunny
=> Register warden bountybunny

_data/handles/kodyvim.json
Auto-generated PR to register the new warden kodyvim
=> Register warden kodyvim

_data/handles/got_targ.json
Auto-generated PR to register the new warden got_targ
=> Register warden got_targ

_data/handles/Himanshu_.json, _data/handles/Himanshu_6353.json
Auto-generated PR to register the new warden Himanshu_6353
@himanshu-Bhatt
=> Register warden Himanshu_

_data/handles/Mick3y.json
Auto-generated PR to register the new warden Mick3y
=> Register warden Mick3y

_data/handles/cbaglieri.json
Auto-generated PR to register the new warden cbaglieri
@mbaglieri
=> Register warden cbaglieri

_data/handles/marktrs.json
Auto-generated PR to register the new warden marktrs
@marktrs
=> Register warden marktrs

_data/handles/midnight-madman.json
Auto-generated PR to register the new warden midnight-madman
@midnight-madman
=> Register warden midnight-madman

_data/handles/SnowMan.json
Auto-generated PR to register the new warden SnowMan
=> Register warden SnowMan

_data/handles/ontofractal.json
Auto-generated PR to register the new warden ontofractal
@ontofractal
=> Register warden ontofractal

_data/handles/Neokry.json
Auto-generated PR to register the new warden Neokry
@neokry
=> Register warden Neokry

_data/handles/Louie.json
Auto-generated PR to register the new warden Louie
=> Register warden Louie

_data/handles/noways.json
Auto-generated PR to register the new warden noways
=> Register warden noways

_data/handles/jsonDoge.json
Auto-generated PR to register the new warden jsonDoge
=> Register warden jsonDoge

_data/handles/bil_101.json
Auto-generated PR to register the new warden bil_101
=> Register warden bil_101

_data/handles/virus.json
Auto-generated PR to register the new warden virus
=> Register warden virus

_data/handles/slowmoses.json
Auto-generated PR to register the new warden slowmoses
=> Register warden slowmoses

_data/handles/houssem.json
Auto-generated PR to register the new warden houssem
=> Register warden houssem

_data/handles/yosriady.json
Auto-generated PR to register the new warden yosriady
@yosriady
=> Register warden yosriady

_data/handles/0x5rings.json
Auto-generated PR to register the new warden 0x5rings
=> Register warden 0x5rings

_data/handles/CodeBlooded.json
Auto-generated PR to register the new warden CodeBlooded
@okekefrancis112
=> Register warden CodeBlooded

_data/handles/nadino.json
Auto-generated PR to register the new warden nadino
=> Register warden nadino

_data/handles/v_lnko.json
Auto-generated PR to register the new warden v_lnko
@vvlnko
=> Register warden v_lnko

_data/handles/elprofesor.json
This auto-generated PR updates info for warden elprofesor
@kamensec
=> Update warden elprofesor

_data/handles/Sta1400.json
Auto-generated PR to register the new warden Sta1400
@Sta1400
=> Register warden Sta1400

_data/handles/0xdeadbeef.json
Auto-generated PR to register the new warden 0xdeadbeef
=> Register warden 0xdeadbeef

_data/handles/JuaniGallo.json
Auto-generated PR to register the new warden JuaniGallo
=> Register warden JuaniGallo

_data/handles/0xSmurf.json
Auto-generated PR to register the new warden 0xSmurf
=> Register warden 0xSmurf

_data/handles/Pheonix.json
Auto-generated PR to register the new warden Pheonix
=> Register warden Pheonix

_data/handles/Isah.json
Auto-generated PR to register the new warden Isah
=> Register warden Isah

_data/handles/pa6221.json
Auto-generated PR to register the new warden pa6221
=> Register warden pa6221

_data/handles/Mrspencer.json
Auto-generated PR to register the new warden Mrspencer
@3lackrambo
=> Register warden Mrspencer

_data/handles/Mukund.json
Auto-generated PR to register the new warden Mukund
=> Register warden Mukund

_data/handles/asgeir.json
This auto-generated PR updates info for warden asgeir
@manboy-eth
=> Update warden asgeir

_data/handles/ggwp.json
This auto-generated PR updates info for warden ggwp
=> Update warden ggwp

_data/handles/literallymarvellous.json
Auto-generated PR to register the new warden literallymarvellous
@https://github.com/literallymarvellous
=> Register warden literallymarvellous

_data/handles/ch.json
Auto-generated PR to register the new warden ch
@chaooooooooos
=> Register warden ch

_data/handles/AkshaySrivastav.json
Auto-generated PR to register the new warden AkshaySrivastav
=> Register warden AkshaySrivastav

_data/handles/Trust.json
This auto-generated PR updates info for warden Trust
@trust1995
=> Update warden Trust

_data/handles/m00npapi.json
Auto-generated PR to register the new warden m00npapi
@Mugrebot
=> Register warden m00npapi

_data/handles/flingz.json
Auto-generated PR to register the new warden flingz
=> Register warden flingz

_data/handles/d3layd.json
Auto-generated PR to register the new warden d3layd
@d3layd
=> Register warden d3layd

_data/handles/Deathstore.json
Auto-generated PR to register the new warden Deathstore
@https://github.com/Deathstore
=> Register warden Deathstore

_data/handles/Venson.json
Auto-generated PR to register the new warden Venson
=> Register warden Venson

_data/handles/OptimismSec.json
This auto-generated PR creates the team OptimismSec
=> Create team OptimismSec

_data/handles/JLevick.json
Auto-generated PR to register the new warden JLevick
=> Register warden JLevick

_data/handles/SEVEN.json
Auto-generated PR to register the new warden SEVEN
=> Register warden SEVEN

_data/handles/adriro.json
Auto-generated PR to register the new warden adriro
@romeroadrian
=> Register warden adriro

_data/handles/cygaar.json
This auto-generated PR updates info for warden cygaar
@cygaar
=> Update warden cygaar

_data/handles/Gooby.json
Auto-generated PR to register the new warden Gooby
=> Register warden Gooby

_data/handles/miel.json
Auto-generated PR to register the new warden miel
=> Register warden miel

_data/handles/wesbz.json
Auto-generated PR to register the new warden wesbz
@wesbz
=> Register warden wesbz

_data/handles/martyhu.json
Auto-generated PR to register the new warden martyhu
@martyhu
=> Register warden martyhu

_data/handles/LostPotato.json
Auto-generated PR to register the new warden LostPotato
=> Register warden LostPotato

_data/handles/eugenereznikdesign.json
Auto-generated PR to register the new warden eugenereznikdesign
=> Register warden eugenereznikdesign

_data/handles/lancha1927.json
Auto-generated PR to register the new warden lancha1927
@imblackjack1
=> Register warden lancha1927

_data/handles/Satyam_Sharma.json
Auto-generated PR to register the new warden Satyam_Sharma
=> Register warden Satyam_Sharma

_data/handles/mcfreshness.json
Auto-generated PR to register the new warden mcfreshness
=> Register warden mcfreshness

_data/handles/shivaam.json
Auto-generated PR to register the new warden shivaam
@shivam2320
=> Register warden shivaam

_data/handles/gd.json
Auto-generated PR to register the new warden gd
@0x3f97
=> Register warden gd

_data/handles/AB92.json
Auto-generated PR to register the new warden AB92
=> Register warden AB92

_data/handles/Zer0Luck.json
Auto-generated PR to register the new warden Zer0Luck
@dnsdudrla97
=> Register warden Zer0Luck

_data/handles/beardofginger.json
This auto-generated PR updates info for warden beardofginger
=> Update warden beardofginger

_data/handles/etash.json
Auto-generated PR to register the new warden etash
@etashhh
=> Register warden etash

_data/handles/osadavc.json
Auto-generated PR to register the new warden osadavc
@osadavc
=> Register warden osadavc

_data/handles/isiah.json
Auto-generated PR to register the new warden isiah
=> Register warden isiah

_data/handles/ErrorWolf74.json
Auto-generated PR to register the new warden ErrorWolf74
=> Register warden ErrorWolf74

_data/handles/bbuddha.json
Auto-generated PR to register the new warden bbuddha
=> Register warden bbuddha

_data/handles/casweeney.json
Auto-generated PR to register the new warden casweeney
@casweeney
=> Register warden casweeney

_data/handles/gbotemi.json
Auto-generated PR to register the new warden gbotemi
@aagbotemi
=> Register warden gbotemi

_data/handles/testing123.json
Auto-generated PR to register the new warden testing123
=> Register warden testing123

_data/handles/e3243eric.json
Auto-generated PR to register the new warden e3243eric
@e3243eric
=> Register warden e3243eric

_data/handles/0xpaneil.json
Auto-generated PR to register the new warden 0xpaneil
=> Register warden 0xpaneil

_data/handles/GuessWho_1337.json
This auto-generated PR updates info for warden GuessWho_1337
=> Update warden GuessWho_1337

_data/handles/LemonKurd.json
Auto-generated PR to register the new warden LemonKurd
=> Register warden LemonKurd

_data/handles/teo.json
Auto-generated PR to register the new warden teo
=> Register warden teo

_data/handles/VirtualSuccessDev.json
Auto-generated PR to register the new warden VirtualSuccessDev
@virtualsuccessdev
=> Register warden VirtualSuccessDev

_data/handles/komplexa.json
Auto-generated PR to register the new warden komplexa
@komplexa
=> Register warden komplexa

_data/handles/mastamynd.json
Auto-generated PR to register the new warden mastamynd
@gudchyld
=> Register warden mastamynd

_data/handles/cocoakoala.json
Auto-generated PR to register the new warden cocoakoala
=> Register warden cocoakoala

_data/handles/BlackAdam.json
Auto-generated PR to register the new warden BlackAdam
@ultra-tech-code
=> Register warden BlackAdam

_data/handles/Larry_Fisherman.json
Auto-generated PR to register the new warden Larry_Fisherman
=> Register warden Larry_Fisherman

_data/handles/SPYBOY.json
Auto-generated PR to register the new warden SPYBOY
=> Register warden SPYBOY

_data/handles/IDKD.json
Auto-generated PR to register the new warden IDKD
=> Register warden IDKD

_data/handles/0xDmitry.json
Auto-generated PR to register the new warden 0xDmitry
@0xDmitry
=> Register warden 0xDmitry

_data/handles/alexxander.json
Auto-generated PR to register the new warden alexxander
=> Register warden alexxander

_data/handles/IllIllI.json
This auto-generated PR updates info for warden IllIllI
@IllIllI000
=> Update warden IllIllI

_data/handles/LorneMalvo.json
Auto-generated PR to register the new warden LorneMalvo
@lordmalvo
=> Register warden LorneMalvo

_data/handles/paradox.json
Auto-generated PR to register the new warden paradox
@secbit-leo
=> Register warden paradox

_data/handles/NikoPotamus.json
Auto-generated PR to register the new warden NikoPotamus
=> Register warden NikoPotamus

_data/handles/zhyd1997.json
Auto-generated PR to register the new warden zhyd1997
@zhyd1997
=> Register warden zhyd1997

src/pages/contests/index.js, src/pages/index.js
Removed display of contest counts from corresponding headlines.
=> Removing contest counts from headers

_data/handles/lichu.json
Auto-generated PR to register the new warden lichu
=> Register warden lichu

_data/handles/nighthawk.json
Auto-generated PR to register the new warden nighthawk
@nighthawk
=> Register warden nighthawk

_data/handles/bin.json
Auto-generated PR to register the new warden bin
@sunnybinb
=> Register warden bin

_data/handles/iulian.json
Auto-generated PR to register the new warden iulian
=> Register warden iulian

_data/handles/GNFinder.json
Auto-generated PR to register the new warden GNFinder
@https://github.com/GNFinder
=> Register warden GNFinder

_data/handles/ds_bb.json
Auto-generated PR to register the new warden ds_bb
=> Register warden ds_bb

_data/handles/Avinash.json
Auto-generated PR to register the new warden Avinash
=> Register warden Avinash

_data/handles/erensa.json
Auto-generated PR to register the new warden erensa
=> Register warden erensa

_data/handles/Laverstation.json
Auto-generated PR to register the new warden Laverstation
@Laverstation
=> Register warden Laverstation

_data/handles/catwhiskeys.json
Auto-generated PR to register the new warden catwhiskeys
=> Register warden catwhiskeys

_data/handles/CloudEllie.json
Auto-generated PR to register the new warden CloudEllie
@CloudEllie
=> Register warden CloudEllie

_data/handles/LDZoid.json
Auto-generated PR to register the new warden LDZoid
@ldzoid
=> Register warden LDZoid

_data/handles/kjn7.json
Auto-generated PR to register the new warden kjn7
@kjn7
=> Register warden kjn7

_data/handles/skyle.json
Auto-generated PR to register the new warden skyle
=> Register warden skyle

_data/handles/M4TZ1P.json
This auto-generated PR modifies the team M4TZ1P
The request was made by DekaiHako
=> Edit team M4TZ1P

_data/handles/amarachiugwu.json
Auto-generated PR to register the new warden amarachiugwu
@amarachiugwu
=> Register warden amarachiugwu

_data/handles/Sayrarh.json
Auto-generated PR to register the new warden Sayrarh
@https://github.com/Sayrarh
=> Register warden Sayrarh

_data/handles/ctf_sec.json
Auto-generated PR to register the new warden ctf_sec
=> Register warden ctf_sec

_data/handles/sha256yan.json
Auto-generated PR to register the new warden sha256yan
=> Register warden sha256yan

_data/handles/WarDog94.json
Auto-generated PR to register the new warden WarDog94
@kjuhasz
=> Register warden WarDog94

_data/handles/Calnix.json
Auto-generated PR to register the new warden Calnix
@calnix
=> Register warden Calnix

_data/handles/centie.json
Auto-generated PR to register the new warden centie
@centie22
=> Register warden centie

_data/handles/zabuza.json
Auto-generated PR to register the new warden zabuza
@mubcar
=> Register warden zabuza

_data/handles/n0mine.json
Auto-generated PR to register the new warden n0mine
=> Register warden n0mine

_data/handles/vagrant.json
Auto-generated PR to register the new warden vagrant
=> Register warden vagrant

_data/handles/OdionOseiwe.json
Auto-generated PR to register the new warden OdionOseiwe
@OdionOseiwe
=> Register warden OdionOseiwe

_data/handles/haxshad.json
Auto-generated PR to register the new warden haxshad
@haxshad
=> Register warden haxshad

_data/handles/johnny.json
Auto-generated PR to register the new warden johnny
=> Register warden johnny

_data/handles/tameryus.json
Auto-generated PR to register the new warden tameryus
=> Register warden tameryus

_data/handles/KhaZix.json
Auto-generated PR to register the new warden KhaZix
=> Register warden KhaZix

_data/handles/dec3ntraliz3d.json
Auto-generated PR to register the new warden dec3ntraliz3d
=> Register warden dec3ntraliz3d

_data/handles/DavidKathoh.json
Auto-generated PR to register the new warden DavidKathoh
=> Register warden DavidKathoh

_data/handles/shreyaspapi.json
Auto-generated PR to register the new warden shreyaspapi
@shreyaspapi
=> Register warden shreyaspapi

_data/handles/liobrasil.json
Auto-generated PR to register the new warden liobrasil
@liobrasil
=> Register warden liobrasil

_data/handles/Lashx.json
Auto-generated PR to register the new warden Lashx
=> Register warden Lashx

_data/handles/iepathos.json
Auto-generated PR to register the new warden iepathos
@iepathos
=> Register warden iepathos

_data/handles/Reptilia.json
Auto-generated PR to register the new warden Reptilia
=> Register warden Reptilia

_data/handles/Emerie111.json
Auto-generated PR to register the new warden Emerie111
@Emerie111
=> Register warden Emerie111

_data/handles/138qg3.json
Auto-generated PR to register the new warden 138qg3
@138qg3
=> Register warden 138qg3

_data/handles/cdahlheimer.json
Auto-generated PR to register the new warden cdahlheimer
@cdahlheimer
=> Register warden cdahlheimer

_data/handles/neVERGiveUP.json
This auto-generated PR creates the team neVERGiveUP
=> Create team neVERGiveUP

_data/handles/ECunha.json
Auto-generated PR to register the new warden ECunha
@EWCunha
=> Register warden ECunha

_data/handles/Mayor0803.json
Auto-generated PR to register the new warden Mayor0803
=> Register warden Mayor0803

_data/handles/BClabs.json
This auto-generated PR creates the team BClabs
=> Create team BClabs

_data/handles/PwnedNoMore.json
This auto-generated PR modifies the team PwnedNoMore
The request was made by izhuer
=> Edit team PwnedNoMore

_data/handles/0xnilay.json
Auto-generated PR to register the new warden 0xnilay
@Nilay27
=> Register warden 0xnilay

_data/handles/phaze.json
Auto-generated PR to register the new warden phaze
@0xPhaze
=> Register warden phaze

_data/handles/D4YDR34M.json
Auto-generated PR to register the new warden D4YDR34M
=> Register warden D4YDR34M

_data/handles/Randyyy.json
This auto-generated PR updates info for warden Randyyy
=> Update warden Randyyy

_data/handles/TheVanquiser.json
Auto-generated PR to register the new warden TheVanquiser
@@thevanquiser
=> Register warden TheVanquiser

_data/handles/hyh.json
This auto-generated PR updates info for warden hyh
@dmitriia
=> Update warden hyh

_data/handles/bitbopper.json
This auto-generated PR updates info for warden bitbopper
=> Update warden bitbopper

_data/handles/MelG.json
Auto-generated PR to register the new warden MelG
=> Register warden MelG

_data/handles/0xfarhaan.json
Auto-generated PR to register the new warden 0xfarhaan
@0xfarhaan
=> Register warden 0xfarhaan

_data/handles/gss1.json
Auto-generated PR to register the new warden gss1
=> Register warden gss1

_data/handles/gnkz.json
Auto-generated PR to register the new warden gnkz
=> Register warden gnkz

_data/handles/0xDave.json
Auto-generated PR to register the new warden 0xDave
@Juchan-Park
=> Register warden 0xDave

_data/handles/marcusqq.json
Auto-generated PR to register the new warden marcusqq
=> Register warden marcusqq

_data/handles/Lotus.json
Auto-generated PR to register the new warden Lotus
=> Register warden Lotus

_data/handles/omaelk.json
Auto-generated PR to register the new warden omaelk
=> Register warden omaelk

_data/handles/AlexCzm.json
Auto-generated PR to register the new warden AlexCzm
=> Register warden AlexCzm

_data/handles/sam_cunningham.json
Auto-generated PR to register the new warden sam_cunningham
@samcryptoham
=> Register warden sam_cunningham

_data/handles/evmwanderer.json
Auto-generated PR to register the new warden evmwanderer
=> Register warden evmwanderer

_data/handles/toastedsteaksandwich.json
This auto-generated PR updates info for warden toastedsteaksandwich
@AshiqAmien
=> Update warden toastedsteaksandwich

_data/handles/worldwide.json
Auto-generated PR to register the new warden worldwide
@https://github.com/nishitchittora
=> Register warden worldwide

_data/handles/DadeKuma.json
Auto-generated PR to register the new warden DadeKuma
@DadeKuma
=> Register warden DadeKuma

_data/handles/Beirutgiant.json
Auto-generated PR to register the new warden Beirutgiant
=> Register warden Beirutgiant

_data/handles/Gauddel.json
Auto-generated PR to register the new warden Gauddel
@Gauddel
=> Register warden Gauddel

_data/handles/Tricko.json
Auto-generated PR to register the new warden Tricko
@retsoko
=> Register warden Tricko

_data/handles/kb123.json
Auto-generated PR to register the new warden kb123
@https://github.com/kb123-1
=> Register warden kb123

_data/handles/Crypt0pat.json
Auto-generated PR to register the new warden Crypt0pat
=> Register warden Crypt0pat

_data/handles/stillwater.json
Auto-generated PR to register the new warden stillwater
=> Register warden stillwater

_data/handles/WinterWolf.json
Auto-generated PR to register the new warden WinterWolf
=> Register warden WinterWolf

_data/handles/Shizambles.json
Auto-generated PR to register the new warden Shizambles
=> Register warden Shizambles

_data/handles/medvedik-ur.json
Auto-generated PR to register the new warden medvedik-ur
=> Register warden medvedik-ur

_data/handles/lukejohn.json
Auto-generated PR to register the new warden lukejohn
=> Register warden lukejohn

_data/handles/SadBase.json
Auto-generated PR to register the new warden SadBase
=> Register warden SadBase

_data/handles/yamapyblack.json
Auto-generated PR to register the new warden yamapyblack
@yamapyblack
=> Register warden yamapyblack
