_data/handles/Prisoner627.json

Auto-generated PR to register the new warden Prisoner627

Register warden Prisoner627

---

_data/handles/jayjonah8.json

This auto-generated PR updates info for warden jayjonah8
@jayjonah8

Update warden jayjonah8

---

_data/handles/PierrickGT.json

This auto-generated PR updates info for warden PierrickGT
@PierrickGT

Update warden PierrickGT

---

_data/handles/SimplexM.json

Auto-generated PR to register the new warden SimplexM

Register warden SimplexM

---

_data/handles/Olivia.json

Auto-generated PR to register the new warden Olivia

Register warden Olivia

---

_data/handles/giardiasis.json

Auto-generated PR to register the new warden giardiasis

Register warden giardiasis

---

_data/handles/Wawrdog.json

Auto-generated PR to register the new warden Wawrdog

Register warden Wawrdog

---

_data/handles/smperr.json

Auto-generated PR to register the new warden smperr

Register warden smperr

---

_data/handles/gs8nrv.json

This auto-generated PR updates info for warden gs8nrv

Update warden gs8nrv

---

_data/handles/esi0010.json

Auto-generated PR to register the new warden esi0010

Register warden esi0010

---

_data/handles/Badboycrypto.json

Auto-generated PR to register the new warden Badboycrypto

Register warden Badboycrypto

---

_data/handles/kyo.json

Auto-generated PR to register the new warden kyo

Register warden kyo

---

_data/handles/zapaz.json

Auto-generated PR to register the new warden zapaz
@zapaz

Register warden zapaz

---

_data/handles/D4RK7ET.json

Auto-generated PR to register the new warden D4RK7ET
@var77

Register warden D4RK7ET

---

_data/handles/ABDOSSAMAD.json

Auto-generated PR to register the new warden ABDOSSAMAD

Register warden ABDOSSAMAD

---

_data/handles/yiyi.json

Auto-generated PR to register the new warden yiyi

Register warden yiyi

---

_data/handles/Bichou1584.json

Auto-generated PR to register the new warden Bichou1584

Register warden Bichou1584

---

_data/handles/hashTheBlocks.json

Auto-generated PR to register the new warden hashTheBlocks
@https://github.com/sauravs

Register warden hashTheBlocks

---

_data/handles/makss.json

Auto-generated PR to register the new warden makss

Register warden makss

---

_data/handles/Ach_Belk.json

Auto-generated PR to register the new warden Ach_Belk

Register warden Ach_Belk

---

_data/handles/HE1M.json

Auto-generated PR to register the new warden HE1M

Register warden HE1M

---

_data/handles/soulskytr.json

Auto-generated PR to register the new warden soulskytr

Register warden soulskytr

---

_data/handles/miyazakisouls.json

Auto-generated PR to register the new warden miyazakisouls
@davutsaki

Register warden miyazakisouls

---

_data/handles/win.json

This auto-generated PR creates the team win

Create team win

---

_data/handles/zoquen.json

Auto-generated PR to register the new warden zoquen

Register warden zoquen

---

_data/handles/justubong.json

Auto-generated PR to register the new warden justubong
@justubongj

Register warden justubong

---

_data/handles/inden.json

Auto-generated PR to register the new warden inden
@ardislu

Register warden inden

---

_data/handles/ANDY27535127.json

Auto-generated PR to register the new warden ANDY27535127
@ANDY27535127

Register warden ANDY27535127

---

_data/handles/Fuu.json

Auto-generated PR to register the new warden Fuu

Register warden Fuu

---

_data/handles/lfzkoala.json

Auto-generated PR to register the new warden lfzkoala

Register warden lfzkoala

---

_data/handles/degionboyz.json

Auto-generated PR to register the new warden degionboyz

Register warden degionboyz

---

_data/handles/raspberrytea.json

Auto-generated PR to register the new warden raspberrytea
@techbizgurl

Register warden raspberrytea

---

_data/handles/duongkai.json

Auto-generated PR to register the new warden duongkai
@duongkai

Register warden duongkai

---

_data/handles/wait.json

Auto-generated PR to register the new warden wait

Register warden wait

---

_data/handles/hihen.json

Auto-generated PR to register the new warden hihen

Register warden hihen

---

_data/handles/namn_grg.json

Auto-generated PR to register the new warden namn_grg
@naman-ng

Register warden namn_grg

---

_data/handles/0xB1sh0p.json

Auto-generated PR to register the new warden 0xB1sh0p

Register warden 0xB1sh0p

---

_data/handles/thatoneguy.json

Auto-generated PR to register the new warden thatoneguy

Register warden thatoneguy

---

_data/handles/web3tech.json

Auto-generated PR to register the new warden web3tech

Register warden web3tech

---

_data/handles/dellwatson.json

Auto-generated PR to register the new warden dellwatson
@dellwatson

Register warden dellwatson

---

_data/handles/Aboxdani.json

Auto-generated PR to register the new warden Aboxdani
@dani ingin kaya

Register warden Aboxdani

---

_data/handles/0xBorgia.json

Auto-generated PR to register the new warden 0xBorgia

Register warden 0xBorgia

---

_data/handles/xTSxo.json

Auto-generated PR to register the new warden xTSxo
@TSxo

Register warden xTSxo

---

_data/handles/turbowizard.json

Auto-generated PR to register the new warden turbowizard
@turbowizardry

Register warden turbowizard

---

_data/handles/aniketbhat.json

Auto-generated PR to register the new warden aniketbhat
@Aniket-Bhat

Register warden aniketbhat

---

_data/handles/fresh_bagel.json

Auto-generated PR to register the new warden fresh_bagel
@playmonkey

Register warden fresh_bagel

---

_data/handles/ahmadmalik4050.json

Auto-generated PR to register the new warden ahmadmalik4050

Register warden ahmadmalik4050

---

_data/handles/paweenp.json

Auto-generated PR to register the new warden paweenp

Register warden paweenp

---

_data/handles/Vanderzay.json

Auto-generated PR to register the new warden Vanderzay
@@Vanderzay

Register warden Vanderzay

---

_data/handles/0xNorman.json

Auto-generated PR to register the new warden 0xNorman
@https://github.com/EnbangWu

Register warden 0xNorman

---

_data/handles/0xiso1a.json

Auto-generated PR to register the new warden 0xiso1a

Register warden 0xiso1a

---

_data/handles/anon_i.json

Auto-generated PR to register the new warden anon_i

Register warden anon_i

---

_data/handles/xiaolou86.json

Auto-generated PR to register the new warden xiaolou86
@xiaolou86

Register warden xiaolou86

---

_data/handles/0xRav3n.json

Auto-generated PR to register the new warden 0xRav3n

Register warden 0xRav3n

---

_data/handles/juniormp.json

Auto-generated PR to register the new warden juniormp

Register warden juniormp

---

_data/handles/dragotanqueray.json

Auto-generated PR to register the new warden dragotanqueray

Register warden dragotanqueray

---

_data/handles/gz627.json

Auto-generated PR to register the new warden gz627

Register warden gz627

---

_data/handles/Vikadin.json

Auto-generated PR to register the new warden Vikadin

Register warden Vikadin

---

_data/handles/pala_55.json

Auto-generated PR to register the new warden pala_55

Register warden pala_55

---

_data/handles/zaryab2000.json

Auto-generated PR to register the new warden zaryab2000
@https://github.com/zaryab2000

Register warden zaryab2000

---

_data/handles/coincoin.json

Auto-generated PR to register the new warden coincoin

Register warden coincoin

---

_data/handles/codehacker.json

Auto-generated PR to register the new warden codehacker

Register warden codehacker

---

_data/handles/Maryna.json

Auto-generated PR to register the new warden Maryna

Register warden Maryna

---

_data/handles/menox.json

Auto-generated PR to register the new warden menox

Register warden menox

---

_data/handles/Michael.json

Auto-generated PR to register the new warden Michael

Register warden Michael

---

_data/handles/merlin.json

Auto-generated PR to register the new warden merlin

Register warden merlin

---

_data/handles/kalloc.json

Auto-generated PR to register the new warden kalloc
@kalloc

Register warden kalloc

---

_data/handles/parkWeb3hacker.json

Auto-generated PR to register the new warden parkWeb3hacker

Register warden parkWeb3hacker

---

_data/handles/Rudra16.json

Auto-generated PR to register the new warden Rudra16
@Rudra2018

Register warden Rudra16

---

_data/handles/owklama.json

Auto-generated PR to register the new warden owklama
@DeanShaked

Register warden owklama

---

_data/handles/miguelmtzinf.json

This auto-generated PR updates info for warden miguelmtzinf

Update warden miguelmtzinf

---

_data/handles/0xhacksmithh.json

Auto-generated PR to register the new warden 0xhacksmithh

Register warden 0xhacksmithh

---

_data/handles/bananasboys.json

This auto-generated PR creates the team bananasboys

Create team bananasboys

---

_data/handles/danhmaychet.json

Auto-generated PR to register the new warden danhmaychet

Register warden danhmaychet

---

_data/handles/Cryptoid.json

Auto-generated PR to register the new warden Cryptoid
@CryptoidM

Register warden Cryptoid

---

_data/handles/federicosan.json

Auto-generated PR to register the new warden federicosan
@federicosan

Register warden federicosan

---

_data/handles/Vadis.json

Auto-generated PR to register the new warden Vadis

Register warden Vadis

---

_data/handles/mjmoonwalker.json

Auto-generated PR to register the new warden mjmoonwalker

Register warden mjmoonwalker

---

_data/handles/Faith.json

Auto-generated PR to register the new warden Faith
@farazsth98

Register warden Faith

---

_data/handles/web3er.json

Auto-generated PR to register the new warden web3er

Register warden web3er

---

_data/handles/s4kkiapel.json

Auto-generated PR to register the new warden s4kkiapel

Register warden s4kkiapel

---

_data/handles/defdef.json

Auto-generated PR to register the new warden defdef

Register warden defdef

---

_data/handles/qpzm.json

Auto-generated PR to register the new warden qpzm
@qpzm

Register warden qpzm

---

_data/handles/dalgarim.json

This auto-generated PR updates info for warden dalgarim
@dalgarim

Update warden dalgarim

---

_data/handles/Kalaydzhiev.json

Auto-generated PR to register the new warden Kalaydzhiev
@xAleksandar

Register warden Kalaydzhiev

---

_data/handles/oualidpro.json

Auto-generated PR to register the new warden oualidpro

Register warden oualidpro

---

_data/handles/climber2002.json

Auto-generated PR to register the new warden climber2002
@climber2002

Register warden climber2002

---

_data/handles/arnie.json

Auto-generated PR to register the new warden arnie

Register warden arnie

---

_data/handles/baysao.json

Auto-generated PR to register the new warden baysao
@baysao

Register warden baysao

---

_data/handles/simonha.json

Auto-generated PR to register the new warden simonha

Register warden simonha

---

_data/handles/0xfuje.json

Auto-generated PR to register the new warden 0xfuje
@0xfuje

Register warden 0xfuje

---

_data/handles/creed.json

Auto-generated PR to register the new warden creed

Register warden creed

---

_data/handles/rbitbytes.json

Auto-generated PR to register the new warden rbitbytes
@889eef19fa81978e52e97d4ad1727f1402cfac05b2f75202c1a67768f3fe80d2

Register warden rbitbytes

---

_data/handles/Foad97.json

Auto-generated PR to register the new warden Foad97
@foad999

Register warden Foad97

---

_data/handles/akbrhx.json

Auto-generated PR to register the new warden akbrhx

Register warden akbrhx

---

_data/handles/cheekn1221.json

Auto-generated PR to register the new warden cheekn1221

Register warden cheekn1221

---

_data/handles/0xdedega.json

Auto-generated PR to register the new warden 0xdedega
@0xdedega

Register warden 0xdedega

---

_data/handles/te_aut.json

Auto-generated PR to register the new warden te_aut
@ednasawe

Register warden te_aut

---

_data/handles/karkantas.json

Auto-generated PR to register the new warden karkantas
@pkyria14

Register warden karkantas

---

_data/handles/RHaO-sec.json

Auto-generated PR to register the new warden RHaO-sec

Register warden RHaO-sec

---

_data/handles/Tullz.json

Auto-generated PR to register the new warden Tullz
@Tullz

Register warden Tullz

---

_data/handles/Dinddle.json

This auto-generated PR updates info for warden Dinddle

Update warden Dinddle

---

_data/handles/HLD.json

Auto-generated PR to register the new warden HLD

Register warden HLD

---

_data/handles/Eeyore.json

Auto-generated PR to register the new warden Eeyore

Register warden Eeyore

---

_data/handles/CalabashSquash.json

This auto-generated PR updates info for warden CalabashSquash
@CalabashSquash

Update warden CalabashSquash

---

_data/handles/siddhpurakaran.json

Auto-generated PR to register the new warden siddhpurakaran

Register warden siddhpurakaran

---

_data/handles/0xLad.json

Auto-generated PR to register the new warden 0xLad

Register warden 0xLad

---

_data/handles/raymogg.json

Auto-generated PR to register the new warden raymogg
@raymogg

Register warden raymogg

---

_data/handles/filipaze.json

Auto-generated PR to register the new warden filipaze

Register warden filipaze

---

_data/handles/gopalsamyrajendran.json

Auto-generated PR to register the new warden gopalsamyrajendran
@gopalsamyrajendran

Register warden gopalsamyrajendran

---

_data/handles/jadezti.json

Auto-generated PR to register the new warden jadezti

Register warden jadezti

---

_data/handles/contracthaxor.json

Auto-generated PR to register the new warden contracthaxor
@cfkelly18

Register warden contracthaxor

---

_data/handles/filmfong.json

Auto-generated PR to register the new warden filmfong

Register warden FILMFONG

---

_data/handles/Ribretta.json

Auto-generated PR to register the new warden Ribretta

Register warden Ribretta

---

_data/handles/wbt.json

Auto-generated PR to register the new warden wbt

Register warden wbt

---

_data/handles/Rafaelrhk.json

Auto-generated PR to register the new warden Rafaelrhk

Register warden Rafaelrhk

---

_data/handles/rickSanchez.json

Auto-generated PR to register the new warden rickSanchez

Register warden rickSanchez

---

_data/handles/udit.json

Auto-generated PR to register the new warden udit

Register warden udit

---

_data/handles/kicky.json

Auto-generated PR to register the new warden kicky

Register warden kicky

---

_data/handles/HollaDieWaldfee.json

Auto-generated PR to register the new warden HollaDieWaldfee
@eZtM09D2EEHU^gDUYClS

Register warden HollaDieWaldfee

---

_data/handles/sakib.json

Auto-generated PR to register the new warden sakib
@sakibnazmus777

Register warden sakib

---

_data/handles/_cgp.json

Auto-generated PR to register the new warden _cgp
@ColinPlatt

Register warden _cgp

---

_data/handles/PwnYip.json

Auto-generated PR to register the new warden PwnYip

Register warden PwnYip

---

_data/handles/nazmus311.json

Auto-generated PR to register the new warden nazmus311
@nazmus311

Register warden nazmus311

---

_data/handles/nithronium.json

Auto-generated PR to register the new warden nithronium
@nithronium

Register warden nithronium

---

_data/handles/saiyajinn.json

Auto-generated PR to register the new warden saiyajinn
@arjunandra

Register warden saiyajinn

---

_data/handles/james_wu.json

Auto-generated PR to register the new warden james_wu
@brown-qs

Register warden james_wu

---

_data/handles/piyushshukla.json

Auto-generated PR to register the new warden piyushshukla

Register warden piyushshukla

---

_data/handles/Raunak_rana.json

Auto-generated PR to register the new warden Raunak_rana

Register warden Raunak_rana

---

_data/handles/abiih.json

Auto-generated PR to register the new warden abiih

Register warden abiih

---

_data/handles/twines.json

Auto-generated PR to register the new warden twines

Register warden twines

---

_data/handles/cryptoDave.json

Auto-generated PR to register the new warden cryptoDave
@dsudit01

Register warden cryptoDave

---

_data/handles/zklim.json

Auto-generated PR to register the new warden zklim
@zklim

Register warden zklim

---

_data/handles/MIQUINHO.json

Auto-generated PR to register the new warden MIQUINHO

Register warden MIQUINHO

---

_data/handles/MHKK33.json

Auto-generated PR to register the new warden MHKK33

Register warden MHKK33

---

_data/handles/latt1ce.json

Auto-generated PR to register the new warden latt1ce

Register warden latt1ce

---

_data/handles/nobodyfrmspace.json

Auto-generated PR to register the new warden nobodyfrmspace
@esnchez

Register warden nobodyfrmspace

---

_data/handles/SuneelVR.json

Auto-generated PR to register the new warden SuneelVR

Register warden SuneelVR

---

_data/handles/CryptoBanker.json

Auto-generated PR to register the new warden CryptoBanker

Register warden CryptoBanker

---

_data/handles/chenshixiao1994.json

Auto-generated PR to register the new warden chenshixiao1994

Register warden chenshixiao1994

---

_data/handles/Murkk.json

Auto-generated PR to register the new warden Murkk

Register warden Murkk

---

_data/handles/PingT.json

Auto-generated PR to register the new warden PingT

Register warden PingT

---

_data/handles/simpletox.json

Auto-generated PR to register the new warden simpletox
@AntonMatveychuk

Register warden simpletox

---

_data/handles/Chris_.json

Auto-generated PR to register the new warden Chris_

Register warden Chris_

---

_data/handles/blz.json

Auto-generated PR to register the new warden blz
@Nilet

Register warden blz

---

_data/handles/sonicskye.json

Auto-generated PR to register the new warden sonicskye
@sonicskye

Register warden sonicskye

---

_data/handles/akshaan.json

Auto-generated PR to register the new warden akshaan
@akshaan

Register warden akshaan

---

_data/handles/mihaic195.json

Auto-generated PR to register the new warden mihaic195
@mihaic195

Register warden mihaic195

---

_data/handles/yjrwkk.json

Auto-generated PR to register the new warden yjrwkk

Register warden yjrwkk

---

_data/handles/N16H7M4R3.json

Auto-generated PR to register the new warden N16H7M4R3

Register warden N16H7M4R3

---

_data/handles/0xIchigo.json

Auto-generated PR to register the new warden 0xIchigo
@0xIchigo

Register warden 0xIchigo

---

_data/handles/Big0XDev.json

Auto-generated PR to register the new warden Big0XDev

Register warden Big0XDev

---

_data/handles/stealthyz.json

Auto-generated PR to register the new warden stealthyz

Register warden stealthyz

---

_data/handles/evan.json

Auto-generated PR to register the new warden evan

Register warden evan

---

_data/handles/KrisApostolov.json

Auto-generated PR to register the new warden KrisApostolov
@CrisCodesCrap

Register warden KrisApostolov

---

_data/handles/einik.json

Auto-generated PR to register the new warden einik

Register warden einik

---

_data/handles/cucbku.json

Auto-generated PR to register the new warden cucbku
@cucbku

Register warden cucbku

---

_data/handles/skidog.json

Auto-generated PR to register the new warden skidog
@abw2007

Register warden skidog

---

_data/handles/whalegoddess.json

Auto-generated PR to register the new warden whalegoddess
@KenTheWhaleGoddess

Register warden whalegoddess

---

_data/handles/jensen_tran.json

Auto-generated PR to register the new warden jensen_tran

Register warden jensen_tran

---

_data/handles/Stengo.json

Auto-generated PR to register the new warden Stengo
@StengoS

Register warden Stengo

---

_data/handles/ForkEth.json

This auto-generated PR creates the team ForkEth

Create team ForkEth

---

_data/handles/0xTraub.json

Auto-generated PR to register the new warden 0xTraub

Register warden 0xTraub

---

_data/handles/UdarTeam.json

This auto-generated PR creates the team UdarTeam

Create team UdarTeam

---

_data/handles/jobean89.json

Auto-generated PR to register the new warden jobean89

Register warden jobean89

---

_data/handles/greggy.json

Auto-generated PR to register the new warden greggy
@greg-gy

Register warden greggy

---

_data/handles/meriken.json

Auto-generated PR to register the new warden meriken

Register warden meriken

---

_data/handles/yawn.json

Auto-generated PR to register the new warden yawn
@yawn-c111

Register warden yawn

---

_data/handles/mookimgo.json

Auto-generated PR to register the new warden mookimgo

Register warden mookimgo

---

_data/handles/shadows.json

Auto-generated PR to register the new warden shadows

Register warden shadows

---

_data/handles/izhelyazkov.json

Auto-generated PR to register the new warden izhelyazkov

Register warden izhelyazkov

---

_data/handles/marcelomorgado.json

Auto-generated PR to register the new warden marcelomorgado

Register warden marcelomorgado

---

_data/handles/Apocalyptic.json

Auto-generated PR to register the new warden Apocalyptic

Register warden Apocalyptic

---

_data/handles/xrY.json

Auto-generated PR to register the new warden xrY

Register warden xrY

---

_data/handles/BAHOZ.json

Auto-generated PR to register the new warden BAHOZ
@8ahoz

Register warden BAHOZ

---

_data/handles/magrisya.json

Auto-generated PR to register the new warden magrisya

Register warden magrisya

---

_data/handles/Zarf.json

Auto-generated PR to register the new warden Zarf

Register warden Zarf

---

_data/handles/Fon.json

Auto-generated PR to register the new warden Fon

Register warden Fon

---

_data/handles/mvsashi.json

Auto-generated PR to register the new warden mvsashi

Register warden mvsashi

---

_data/handles/d4r3d3v1l.json

Auto-generated PR to register the new warden d4r3d3v1l
@D4r3-D3v1L

Register warden d4r3d3v1l

---

_data/handles/mabuk.json

Auto-generated PR to register the new warden mabuk

Register warden mabuk

---

_data/handles/Apocalypto.json

This auto-generated PR creates the team Apocalypto

Create team Apocalypto

---

_data/handles/deepvalue.json

Auto-generated PR to register the new warden deepvalue

Register warden deepvalue

---

_data/handles/KmanOfficial.json

Auto-generated PR to register the new warden KmanOfficial

Register warden KmanOfficial

---

_data/handles/Apocalypto.json

This auto-generated PR modifies the team Apocalypto
The request was made by cRat1st0s

Edit team Apocalypto

---

_data/reports/2022-11-foundation.md

Foundation report scoping table fix

---

_data/handles/WYCF.json

Auto-generated PR to register the new warden WYCF

Register warden WYCF

---

_data/handles/Breeje.json

Auto-generated PR to register the new warden Breeje

Register warden Breeje

---

_data/handles/alexroan.json

Auto-generated PR to register the new warden alexroan
@alexroan

Register warden alexroan

---

_data/handles/namaskar.json

Auto-generated PR to register the new warden namaskar
@https://github.com/namaskar-1f64f

Register warden namaskar

---

_data/handles/bezdna.json

Auto-generated PR to register the new warden bezdna
@tooBusyNow

Register warden bezdna

---

_data/handles/Chao.json

Auto-generated PR to register the new warden Chao
@ermvrs

Register warden Chao

---

_data/handles/jasonxiale.json

Auto-generated PR to register the new warden jasonxiale
@crazy4linux

Register warden jasonxiale

---

_data/handles/Marzel.json

Auto-generated PR to register the new warden Marzel

Register warden Marzel

---

_data/handles/0xTahiTi.json
_data/handles/0xTahiti.json

Auto-generated PR to register the new warden 0xTahiti
@TahiTi

Register warden 0xTahiTi

---

_data/handles/CHALK.json

Auto-generated PR to register the new warden CHALK

Register warden CHALK

---

_data/handles/r_u_k.json

Auto-generated PR to register the new warden r_u_k
@lemonFlavDaBest

Register warden r_u_k

---

_data/handles/91twentythree.json

Auto-generated PR to register the new warden 91twentythree

Register warden 91twentythree

---

_data/handles/3dgeville.json

Auto-generated PR to register the new warden 3dgeville

Register warden 3dgeville

---

_data/handles/juan.json

Auto-generated PR to register the new warden juan
@sheinix

Register warden juan

---

_data/handles/0xdhruv.json

Auto-generated PR to register the new warden 0xdhruv
@Dhruv-2003

Register warden 0xdhruv

---

_data/handles/yoyoismee.json

Auto-generated PR to register the new warden yoyoismee
@yoyoismee

Register warden yoyoismee

---

_data/handles/piotromashov.json

Auto-generated PR to register the new warden piotromashov
@piotromashov

Register warden piotromashov

---

_data/handles/Elite.json

Auto-generated PR to register the new warden Elite

Register warden Elite

---

_data/handles/lofi.json

Auto-generated PR to register the new warden lofi

Register warden lofi

---

_data/handles/LauriP.json

Auto-generated PR to register the new warden LauriP
@microbecode

Register warden LauriP

---

_data/handles/0xjscrui.json

Auto-generated PR to register the new warden 0xjscrui
@jscrui

Register warden 0xjscrui

---

_data/handles/0xibsen.json

Auto-generated PR to register the new warden 0xibsen

Register warden 0xibsen

---

_data/handles/B4K4K4W411.json

Auto-generated PR to register the new warden B4K4K4W411
@B4K4K4W411

Register warden B4K4K4W411

---

_data/handles/Ferax.json

Auto-generated PR to register the new warden Ferax

Register warden Ferax

---

_data/handles/Mr_Wodinn.json

Auto-generated PR to register the new warden Mr_Wodinn

Register warden Mr_Wodinn

---

_data/handles/multipl3xer.json

Auto-generated PR to register the new warden multipl3xer

Register warden multipl3xer

---

_data/handles/DevTimSch.json

Auto-generated PR to register the new warden DevTimSch
@https://github.com/DevTimSch

Register warden DevTimSch

---

_data/handles/ast3ros.json

Auto-generated PR to register the new warden ast3ros

Register warden ast3ros

---

_data/handles/0xraiyan28.json

Auto-generated PR to register the new warden 0xraiyan28
@raiyanmook27

Register warden 0xraiyan28

---

_data/handles/abhay18e.json

Auto-generated PR to register the new warden abhay18e

Register warden abhay18e

---

_data/handles/dhammu.json

Auto-generated PR to register the new warden dhammu

Register warden dhammu

---

_data/handles/Secret_Maya.json

Auto-generated PR to register the new warden Secret_Maya

Register warden Secret_Maya

---

_data/handles/BPZ.json

This auto-generated PR creates the team BPZ

Create team BPZ

---

_data/handles/pesak02.json

This auto-generated PR modifies the team pesak02
The request was made by pedr02b2

Edit team pesak02

---

_data/handles/Sojourner.json

Auto-generated PR to register the new warden Sojourner
@0xSojourner

Register warden Sojourner

---

_data/handles/0xTinder.json

Auto-generated PR to register the new warden 0xTinder
@ryantinder

Register warden 0xTinder

---

_data/handles/txt_malw.json

Auto-generated PR to register the new warden txt_malw

Register warden txt_malw

---

_data/handles/n33k.json

Auto-generated PR to register the new warden n33k

Register warden n33k

---

_data/handles/ghostrush.json

Auto-generated PR to register the new warden ghostrush
@ghostrush

Register warden ghostrush

---

_data/handles/Lalanda.json

Auto-generated PR to register the new warden Lalanda
@albertolalanda

Register warden Lalanda

---

_data/handles/lol.json

This auto-generated PR creates the team lol

Create team lol

---

_data/handles/lexx.json

Auto-generated PR to register the new warden lexx

Register warden lexx

---

_data/handles/Arizona033.json

Auto-generated PR to register the new warden Arizona033

Register warden Arizona033

---

_data/handles/C4CAs.json

This auto-generated PR creates the team C4CAs

Create team C4CAs

---

_data/handles/AidenPark.json

Auto-generated PR to register the new warden AidenPark
@adnpark

Register warden AidenPark

---

_data/handles/betweenETHlines.json

Auto-generated PR to register the new warden betweenETHlines
@HiCharlesWang

Register warden betweenETHlines

---

_data/handles/Vinathi.json
_data/handles/vinathi.json

Auto-generated PR to register the new warden vinathi
@Vvinathi

Register warden Vinathi

---

_data/handles/Sunitha_Mantri.json

Auto-generated PR to register the new warden Sunitha_Mantri
@SunithaMantri13

Register warden Sunitha_Mantri

---

_data/handles/doctor_naija.json

Auto-generated PR to register the new warden doctor_naija

Register warden doctor_naija

---

_data/handles/dortnumara.json

Auto-generated PR to register the new warden dortnumara
@aliogutcen

Register warden dortnumara

---

_data/handles/Lruquaf.json

Auto-generated PR to register the new warden Lruquaf
@Lruquaf

Register warden Lruquaf

---

_data/handles/atharvasama.json

Auto-generated PR to register the new warden atharvasama
@atharvamitragotri

Register warden atharvasama

---

_data/handles/mmdlens.json

Auto-generated PR to register the new warden mmdlens

Register warden mmdlens

---

_data/handles/Budaghyan.json

Auto-generated PR to register the new warden Budaghyan

Register warden Budaghyan

---

_data/handles/magickenn.json

Auto-generated PR to register the new warden magickenn
@magickenn

Register warden magickenn

---

_data/handles/decental.json

Auto-generated PR to register the new warden decental

Register warden decental

---

_data/handles/7e1e.json

Auto-generated PR to register the new warden 7e1e
@0x7ele

Register warden 7e1e

---

_data/handles/hyigit.json

Auto-generated PR to register the new warden hyigit
@huseyinyigit

Register warden hyigit

---

_data/handles/iankitkapoor1.json

Auto-generated PR to register the new warden iankitkapoor1

Register warden iankitkapoor1

---

_data/handles/big_rocket.json

Auto-generated PR to register the new warden big_rocket

Register warden big_rocket

---

_data/handles/decentBlock.json

Auto-generated PR to register the new warden decentBlock

Register warden decentBlock

---

_data/handles/saurabhdoteth.json

Auto-generated PR to register the new warden saurabhdoteth

Register warden saurabhdoteth

---

_data/handles/enryptiq.json

Auto-generated PR to register the new warden enryptiq
@filipzupancic

Register warden enryptiq

---

_data/handles/0xOsiris.json

Auto-generated PR to register the new warden 0xOsiris
@0xOsiris

Register warden 0xOsiris

---

_data/handles/0xWagmi.json

Auto-generated PR to register the new warden 0xWagmi
@https://github.com/niluk-256

Register warden 0xWagmi

---

_data/handles/qbs.json

Auto-generated PR to register the new warden qbs

Register warden qbs

---

_data/handles/rhman.json

Auto-generated PR to register the new warden rhman
@https://github.com/Aabdullahi015

Register warden rhman

---

_data/handles/sylvnco.json

Auto-generated PR to register the new warden sylvnco
@sylvnco

Register warden sylvnco

---

_data/handles/0xFocus.json

Auto-generated PR to register the new warden 0xFocus

Register warden 0xFocus

---

_data/handles/Turbo.json

Auto-generated PR to register the new warden Turbo

Register warden Turbo

---

_data/handles/synackrst.json

Auto-generated PR to register the new warden synackrst
@taishi8117

Register warden synackrst

---

_data/handles/h5n8514.json

Auto-generated PR to register the new warden h5n8514
@liumuqing

Register warden h5n8514

---

_data/handles/hupixiong.json

Auto-generated PR to register the new warden hupixiong

Register warden hupixiong

---

_data/handles/0xdaydream.json

Auto-generated PR to register the new warden 0xdaydream
@0xd4ydream

Register warden 0xdaydream

---

_data/handles/hlongvu.json

Auto-generated PR to register the new warden hlongvu
@hlongvu

Register warden hlongvu

---

_data/handles/murelel.json

Auto-generated PR to register the new warden murelel
@amurelel

Register warden murelel

---

_data/handles/jibola.json

Auto-generated PR to register the new warden jibola
@jbrit

Register warden jibola

---

_data/handles/Raymond.json

Auto-generated PR to register the new warden Raymond

Register warden Raymond

---

_data/handles/solqunat.json

Auto-generated PR to register the new warden solqunat

Register warden solqunat

---

_data/handles/alexfu.json

Auto-generated PR to register the new warden alexfu
@alexenc

Register warden alexfu

---

_data/handles/Hemang.json

Auto-generated PR to register the new warden Hemang

Register warden Hemang

---

_data/handles/chevy.json

Auto-generated PR to register the new warden chevy
@chevonmdphillip

Register warden chevy

---

_data/handles/testintesttester.json

Auto-generated PR to register the new warden testintesttester

Register warden testintesttester

---

_data/handles/bbodd.json

Auto-generated PR to register the new warden bbodd

Register warden bbodd

---

_data/handles/descharre.json

Auto-generated PR to register the new warden descharre
@stefscharre123

Register warden descharre

---

_data/handles/Gracious.json

Auto-generated PR to register the new warden Gracious
@Greyshaws

Register warden Gracious

---

_data/handles/ihikx.json

Auto-generated PR to register the new warden ihikx
@EslamHiko

Register warden ihikx

---

_data/handles/0xsaiful.json

Auto-generated PR to register the new warden 0xsaiful

Register warden 0xsaiful

---

_data/handles/santipu_.json

Auto-generated PR to register the new warden santipu_
@santipu03

Register warden santipu_

---

_data/handles/photonintrique.json

Auto-generated PR to register the new warden photonintrique

Register warden photonintrique

---

_data/handles/buntr.json

Auto-generated PR to register the new warden buntr
@ktk07

Register warden buntr

---

_data/handles/shaitan.json

Auto-generated PR to register the new warden shaitan

Register warden shaitan

---

_data/handles/peakbolt.json

Auto-generated PR to register the new warden peakbolt

Register warden peakbolt

---

_data/handles/Snoopy.json

Auto-generated PR to register the new warden Snoopy

Register warden Snoopy

---

_data/handles/ret2happy.json

Auto-generated PR to register the new warden ret2happy
@pcy190

Register warden ret2happy

---

_data/handles/merem.json

Auto-generated PR to register the new warden merem
@merembablas

Register warden merem

---

_data/handles/bhvrvt.json

Auto-generated PR to register the new warden bhvrvt
@bhvrvt

Register warden bhvrvt

---

_data/handles/n00biec4.json

Auto-generated PR to register the new warden n00biec4

Register warden n00biec4

---

_data/handles/netgamesekai.json

Auto-generated PR to register the new warden netgamesekai
@netgamesekai

Register warden netgamesekai

---

_data/handles/cosullivan.json

Auto-generated PR to register the new warden cosullivan
@cosullivan

Register warden cosullivan

---

_data/handles/yxng_geoo.json

Auto-generated PR to register the new warden yxng_geoo

Register warden yxng_geoo

---

_data/handles/PowPowPow.json

Auto-generated PR to register the new warden PowPowPow
@https://github.com/count-sum

Register warden PowPowPow

---

_data/handles/0xdevPed.json

Auto-generated PR to register the new warden 0xdevPed

Register warden 0xdevPed

---

_data/handles/0xmonsoon.json

Auto-generated PR to register the new warden 0xmonsoon
@github.com/0xmonsoon

Register warden 0xmonsoon

---

_data/handles/Baki.json

This auto-generated PR creates the team Baki

Create team Baki

---

_data/handles/gaspacho.json

Auto-generated PR to register the new warden gaspacho
@gaspachow

Register warden gaspacho

---

_data/handles/0xPARVD0XSVPR3ME.json

Auto-generated PR to register the new warden 0xPARVD0XSVPR3ME

Register warden 0xPARVD0XSVPR3ME

---

_data/handles/Toshii.json

Auto-generated PR to register the new warden Toshii
@0xtoshii

Register warden Toshii

---

_data/handles/0xMirce.json

Auto-generated PR to register the new warden 0xMirce

Register warden 0xMirce

---

_data/handles/static.json

This auto-generated PR updates info for warden static

Update warden static

---

_data/handles/Proxy.json

Auto-generated PR to register the new warden Proxy
@KirinFilip

Register warden Proxy

---

_data/handles/Abrar.json

Auto-generated PR to register the new warden Abrar

Register warden Abrar

---

_data/handles/luxartvinsec.json

Auto-generated PR to register the new warden luxartvinsec
@luxartvinsec

Register warden luxartvinsec

---

_data/handles/Jaguar2303.json

Auto-generated PR to register the new warden Jaguar2303
@Kunalmishra1999

Register warden Jaguar2303

---

_data/handles/Kayanski.json

Auto-generated PR to register the new warden Kayanski
@Kayanski

Register warden Kayanski

---

_data/handles/Parad0x.json

Auto-generated PR to register the new warden Parad0x

Register warden Parad0x

---

_data/handles/holme.json

Auto-generated PR to register the new warden holme

Register warden holme

---

_data/handles/shadowjynxs.json

Auto-generated PR to register the new warden shadowjynxs
@shadowjynxs

Register warden shadowjynxs

---

_data/handles/vkage.json

Auto-generated PR to register the new warden vkage
@vkage

Register warden vkage

---

_data/handles/arathkone.json

Auto-generated PR to register the new warden arathkone
@0x-arathkone

Register warden arathkone

---

_data/handles/severity.json

This auto-generated PR creates the team severity

Create team severity

---

_data/handles/GoombaTroopa.json

Auto-generated PR to register the new warden GoombaTroopa

Register warden GoombaTroopa

---

_data/handles/sekharlee_43.json

Auto-generated PR to register the new warden sekharlee_43
@sekharlee

Register warden sekharlee_43

---

_data/handles/SleepingBugs.json

This auto-generated PR modifies the team SleepingBugs
The request was made by Deivitto

Edit team SleepingBugs

---

_data/handles/vsaverin.json

Auto-generated PR to register the new warden vsaverin

Register warden vsaverin

---

_data/handles/manuareraa.json

Auto-generated PR to register the new warden manuareraa
@akmanuareraa

Register warden manuareraa

---

_data/handles/sqrtrev.json

Auto-generated PR to register the new warden sqrtrev
@sqrtrev

Register warden sqrtrev

---

_data/handles/hashminer0725.json

Auto-generated PR to register the new warden hashminer0725

Register warden hashminer0725

---

_data/handles/seaona.json

Auto-generated PR to register the new warden seaona
@seaona

Register warden seaona

---

_data/handles/Q5Ca.json

Auto-generated PR to register the new warden Q5Ca

Register warden Q5Ca

---

_data/handles/bytes032.json

Auto-generated PR to register the new warden bytes032
@bytes032

Register warden bytes032

---

_data/handles/Subhiksha_Sudhakar.json

Auto-generated PR to register the new warden Subhiksha_Sudhakar

Register warden Subhiksha_Sudhakar

---

_data/handles/iso.json

Auto-generated PR to register the new warden iso
@isopach

Register warden iso

---

_data/handles/altaa.json

Auto-generated PR to register the new warden altaa
@Ladycodee

Register warden altaa

---

_data/handles/The_i0n.json

Auto-generated PR to register the new warden The_i0n

Register warden The_i0n

---

_data/handles/kodak_rome.json

Auto-generated PR to register the new warden kodak_rome
@Kodakr

Register warden kodak_rome

---

_data/handles/overflow427x.json

Auto-generated PR to register the new warden overflow427x

Register warden overflow427x

---

_data/handles/lordmike007.json

Auto-generated PR to register the new warden lordmike007

Register warden lordmike007

---

_data/handles/faqer.json

Auto-generated PR to register the new warden faqer
@yusufbenliii

Register warden faqer

---

_data/handles/Jameswade.json

Auto-generated PR to register the new warden Jameswade
@JameWade

Register warden Jameswade

---

_data/handles/josephdara.json

Auto-generated PR to register the new warden josephdara
@Josephdara

Register warden josephdara

---

_data/handles/BlasterX24.json

Auto-generated PR to register the new warden BlasterX24
@BlasterX24

Register warden BlasterX24

---

_data/handles/ucalyptus.json

Auto-generated PR to register the new warden ucalyptus
@ucalyptus

Register warden ucalyptus

---

_data/handles/Inuy4sh4_.json

Auto-generated PR to register the new warden Inuy4sh4_

Register warden Inuy4sh4_

---

_data/handles/FarajiOranj.json

Auto-generated PR to register the new warden FarajiOranj

Register warden FarajiOranj

---

_data/handles/Vilenski.json

Auto-generated PR to register the new warden Vilenski

Register warden Vilenski

---

_data/handles/Batiste.json

Auto-generated PR to register the new warden Batiste

Register warden Batiste

---

_data/handles/chirag0410.json

Auto-generated PR to register the new warden chirag0410
@CVM0410

Register warden chirag0410

---

_data/handles/mujee.json

Auto-generated PR to register the new warden mujee
@mujee7

Register warden mujee

---

_data/handles/b00ts.json

Auto-generated PR to register the new warden b00ts
@willspencer805

Register warden b00ts

---

_data/handles/Caraiben.json

Auto-generated PR to register the new warden Caraiben

Register warden Caraiben

---

_data/handles/naama.json

Auto-generated PR to register the new warden naama
@junaama

Register warden naama

---

_data/handles/Falcon.json

Auto-generated PR to register the new warden Falcon

Register warden Falcon

---

_data/handles/h_adnan.json

Auto-generated PR to register the new warden h_adnan
@adnhq

Register warden h_adnan

---

_data/handles/fatihguur.json

Auto-generated PR to register the new warden fatihguur
@fatihguur

Register warden fatihguur

---

_data/handles/DanLei.json

Auto-generated PR to register the new warden DanLei

Register warden DanLei

---

_data/handles/SenudaJay.json

Auto-generated PR to register the new warden SenudaJay

Register warden SenudaJay

---

_data/handles/entangled_qubit.json

Auto-generated PR to register the new warden entangled_qubit
@milapsheth

Register warden entangled_qubit

---

_data/handles/geraltofrivia.json

Auto-generated PR to register the new warden geraltofrivia

Register warden geraltofrivia

---

_data/handles/diki.json

Auto-generated PR to register the new warden diki

Register warden diki

---

_data/handles/H0.json

Auto-generated PR to register the new warden H0

Register warden H0

---

_data/handles/shree.json

Auto-generated PR to register the new warden shree
@shrirajpawar4

Register warden shree

---

_data/handles/Dirac.json

Auto-generated PR to register the new warden Dirac

Register warden Dirac

---

_data/handles/vickey.json

Auto-generated PR to register the new warden vickey

Register warden vickey

---

_data/handles/Fitro.json

Auto-generated PR to register the new warden Fitro
@IvanFitro

Register warden Fitro

---

_data/handles/Inspectah.json

Auto-generated PR to register the new warden Inspectah
@AniDhumal

Register warden Inspectah

---

_data/handles/Grzegorz.json

Auto-generated PR to register the new warden Grzegorz
@grzeznx2

Register warden Grzegorz

---

_data/handles/khanhtq.json

Auto-generated PR to register the new warden khanhtq

Register warden khanhtq

---

_data/handles/pete123.json

Auto-generated PR to register the new warden pete123
@petr-hejda

Register warden pete123

---

_data/handles/deccentric.json

Auto-generated PR to register the new warden deccentric

Register warden deccentric

---

_data/handles/0v3r_w4tch.json

Auto-generated PR to register the new warden 0v3r_w4tch

Register warden 0v3r_w4tch

---

_data/handles/BowTiedHamachi.json

Auto-generated PR to register the new warden BowTiedHamachi
@bthamachi

Register warden BowTiedHamachi

---

_data/handles/developerjordy.json

Auto-generated PR to register the new warden developerjordy

Register warden developerjordy

---

_data/handles/Umut.json

Auto-generated PR to register the new warden Umut
@umutkutlu

Register warden Umut

---

_data/handles/bl0ckcipherdev.json

Auto-generated PR to register the new warden bl0ckcipherdev

Register warden bl0ckcipherdev

---

_data/handles/ddimitrov22.json

Auto-generated PR to register the new warden ddimitrov22

Register warden ddimitrov22

---

_data/handles/maAPPs.json

Auto-generated PR to register the new warden maAPPs
@maAPPsDEV

Register warden maAPPs

---

_data/handles/ethernomad.json

Auto-generated PR to register the new warden ethernomad
@ethernomad

Register warden ethernomad

---

_data/handles/Caue.json

Auto-generated PR to register the new warden Caue
@caueobici

Register warden Caue

---

_data/handles/KIntern_NA.json

This auto-generated PR modifies the team KIntern_NA
The request was made by TrungOre

Edit team KIntern_NA

---

_data/handles/methw.json

Auto-generated PR to register the new warden methw
@methekill

Register warden methw

---

_data/handles/zin.json

Auto-generated PR to register the new warden zin

Register warden zin

---

_data/handles/marriileon.json

Auto-generated PR to register the new warden marriileon

Register warden marriileon

---

_data/handles/sordid.json

Auto-generated PR to register the new warden sordid

Register warden sordid

---

_data/handles/catellatech.json

Auto-generated PR to register the new warden catellatech

Register warden catellatech

---

_data/handles/prajju25.json

Auto-generated PR to register the new warden prajju25
@prajju25

Register warden prajju25

---

_data/handles/j-v-v.json

Auto-generated PR to register the new warden j-v-v
@jhonnyV-V

Register warden j-v-v

---

_data/handles/coffeenbourbon.json

Auto-generated PR to register the new warden coffeenbourbon
@https://github.com/CoffeeNbourbon

Register warden coffeenbourbon

---

_data/handles/erdenebat.json

Auto-generated PR to register the new warden erdenebat

Register warden erdenebat

---

_data/handles/wilang.json

Auto-generated PR to register the new warden wilang

Register warden wilang

---

_data/handles/LucaBaros.json

Auto-generated PR to register the new warden LucaBaros

Register warden LucaBaros

---

_data/handles/flintblocks.json

Auto-generated PR to register the new warden flintblocks
@syahrul12345

Register warden flintblocks

---

_data/handles/abhi512.json

Auto-generated PR to register the new warden abhi512
@AbhiGulati

Register warden abhi512

---

_data/handles/sam_ninja.json

Auto-generated PR to register the new warden sam_ninja
@betrisey

Register warden sam_ninja

---

_data/handles/Hutao.json

Auto-generated PR to register the new warden Hutao

Register warden Hutao

---

_data/handles/sepoy.json

Auto-generated PR to register the new warden sepoy

Register warden sepoy

---

_data/handles/0x41.json

Auto-generated PR to register the new warden 0x41

Register warden 0x41

---

_data/handles/Heba-Elhasan.json

Auto-generated PR to register the new warden Heba-Elhasan
@https://github.com/heba-elhasn

Register warden Heba-Elhasan

---

_data/handles/quietude.json

Auto-generated PR to register the new warden quietude
@quietude0x

Register warden quietude

---

_data/handles/Banditx0x.json

Auto-generated PR to register the new warden Banditx0x
@banditx0x

Register warden Banditx0x

---

_data/handles/Buck.json

Auto-generated PR to register the new warden Buck
@craig-iam-smith

Register warden Buck

---

_data/handles/xfu.json

Auto-generated PR to register the new warden xfu
@0xxfu

Register warden xfu

---

_data/handles/risyam.json

Auto-generated PR to register the new warden risyam
@EvolOfThings

Register warden risyam

---

_data/handles/0xJohnsonville.json

Auto-generated PR to register the new warden 0xJohnsonville

Register warden 0xJohnsonville

---

_data/handles/adityak.json

Auto-generated PR to register the new warden adityak
@adityakaklij

Register warden adityak

---

_data/handles/scout2023.json

Auto-generated PR to register the new warden scout2023

Register warden scout2023

---

_data/handles/untamed101.json

Auto-generated PR to register the new warden untamed101

Register warden untamed101

---

_data/handles/radev2000.json

Auto-generated PR to register the new warden radev2000
@zradev

Register warden radev2000

---

_data/handles/nahoragg.json

Auto-generated PR to register the new warden nahoragg

Register warden nahoragg

---

_data/handles/fbslo.json

Auto-generated PR to register the new warden fbslo
@fbslo

Register warden fbslo

---

_data/handles/charlesjhongc.json

Auto-generated PR to register the new warden charlesjhongc
@charlesjhongc

Register warden charlesjhongc

---

_data/handles/MrPotatoHead.json

Auto-generated PR to register the new warden MrPotatoHead

Register warden MrPotatoHead

---

_data/handles/ReyRoman.json

Auto-generated PR to register the new warden ReyRoman
@https://github.com/DeograciousAggrey

Register warden ReyRoman

---

_data/handles/tallo.json

Auto-generated PR to register the new warden tallo

Register warden tallo

---

_data/handles/unkuseni.json

Auto-generated PR to register the new warden unkuseni
@unkuseni

Register warden unkuseni

---

_data/handles/Khans.json

Auto-generated PR to register the new warden Khans

Register warden Khans

---

_data/handles/ego.json

Auto-generated PR to register the new warden ego
@egorushkin

Register warden ego

---

_data/handles/Sergio-Mazariego.json

Auto-generated PR to register the new warden Sergio-Mazariego
@SergioMazariego

Register warden Sergio-Mazariego

---

_data/handles/pranazzs.json

Auto-generated PR to register the new warden pranazzs
@pranazzs

Register warden pranazzs

---

_data/handles/chainzen.json

Auto-generated PR to register the new warden chainzen
@https://github.com/Chainmaven

Register warden chainzen

---

_data/handles/Hieser.json

Auto-generated PR to register the new warden Hieser
@FHieser

Register warden Hieser

---

_data/handles/0xYamiDancho.json

This auto-generated PR updates info for warden 0xYamiDancho
@saxenism

Update warden 0xYamiDancho

---

_data/handles/xmxanuel.json

Auto-generated PR to register the new warden xmxanuel

Register warden xmxanuel

---

_data/handles/consentsam.json

Auto-generated PR to register the new warden consentsam
@consentsam

Register warden consentsam

---

_data/handles/aspaltumpahdimuka.json

Auto-generated PR to register the new warden aspaltumpahdimuka

Register warden aspaltumpahdimuka

---

_data/handles/DLX_C3R.json

Auto-generated PR to register the new warden DLX_C3R
@https://github.com/DanieLion55

Register warden DLX_C3R

---

_data/handles/coburn.json

Auto-generated PR to register the new warden coburn

Register warden coburn

---

_data/handles/melv1llian.json

Auto-generated PR to register the new warden melv1llian

Register warden melv1llian

---

_data/handles/Shitaosec.json

Auto-generated PR to register the new warden Shitaosec

Register warden Shitaosec

---

_data/handles/adeolu.json

Auto-generated PR to register the new warden adeolu
@adeolu98

Register warden adeolu

---

_data/handles/macca.json

Auto-generated PR to register the new warden macca

Register warden macca

---

_data/handles/salad.json

Auto-generated PR to register the new warden salad
@Pavel-Sushko

Register warden salad

---

_data/handles/kutugu.json

Auto-generated PR to register the new warden kutugu
@kutugu

Register warden kutugu

---

_data/handles/byterocket.json

This auto-generated PR modifies the team byterocket
The request was made by marvinkruse

Edit team byterocket

---

_data/handles/Fatma.json

Auto-generated PR to register the new warden Fatma

Register warden Fatma

---

_data/handles/SOLIMAN.json

Auto-generated PR to register the new warden SOLIMAN

Register warden SOLIMAN

---

_data/handles/gurghis.json

Auto-generated PR to register the new warden gurghis

Register warden gurghis

---

_data/handles/digvjs.json

Auto-generated PR to register the new warden digvjs
@digvjs

Register warden digvjs

---

_data/handles/Recep.json

Auto-generated PR to register the new warden Recep
@recepcankaya

Register warden Recep

---

_data/handles/badman.json

Auto-generated PR to register the new warden badman
@https://github.com/henlo-goodman

Register warden badman

---

_data/handles/zenrasta.json

Auto-generated PR to register the new warden zenrasta

Register warden zenrasta

---

_data/handles/0xQTPie.json

Auto-generated PR to register the new warden 0xQTPie

Register warden 0xQTPie

---

_data/handles/sholto.json

Auto-generated PR to register the new warden sholto
@sholto1337

Register warden sholto

---

_data/handles/AnandK_2024.json

Auto-generated PR to register the new warden AnandK_2024
@AnandK-2024

Register warden AnandK_2024

---

_data/handles/natachi.json

Auto-generated PR to register the new warden natachi
@natachigram

Register warden natachi

---

_data/handles/vino.json

Auto-generated PR to register the new warden vino
@vino333

Register warden vino

---

_data/handles/518e.json

Auto-generated PR to register the new warden 518e

Register warden 518e

---

_data/handles/Shubham_Bansal.json

Auto-generated PR to register the new warden Shubham_Bansal
@@sensationalshubham

Register warden Shubham_Bansal

---

_data/handles/turvy_fuzz.json

Auto-generated PR to register the new warden turvy_fuzz
@turvec

Register warden turvy_fuzz

---

_data/handles/seeques.json

Auto-generated PR to register the new warden seeques
@seeques

Register warden seeques

---

_data/handles/poppunk.json

Auto-generated PR to register the new warden poppunk
@pop-punk

Register warden poppunk

---

_data/handles/amu.json

Auto-generated PR to register the new warden amu

Register warden amu

---

_data/handles/Tuhalf.json

Auto-generated PR to register the new warden Tuhalf
@Tuhalf

Register warden Tuhalf

---

_data/handles/rahulthakkar796.json

Auto-generated PR to register the new warden rahulthakkar796
@rahulthakkar796

Register warden rahulthakkar796

---

_data/handles/hunahau.json

Auto-generated PR to register the new warden hunahau

Register warden hunahau

---

_data/handles/Fragtex.json

Auto-generated PR to register the new warden Fragtex
@fragtex-eth

Register warden Fragtex

---

_data/handles/GT.json

Auto-generated PR to register the new warden GT
@gaurangtorvekar

Register warden GT

---

_data/handles/monrel.json

Auto-generated PR to register the new warden monrel

Register warden monrel

---

_data/handles/GreenRuby.json

Auto-generated PR to register the new warden GreenRuby

Register warden GreenRuby

---

_data/handles/hansan.json

Auto-generated PR to register the new warden hansan

Register warden hansan

---

_data/handles/Bough.json

Auto-generated PR to register the new warden Bough
@Maherboug

Register warden Bough

---

_data/handles/Giorgio.json

Auto-generated PR to register the new warden Giorgio
@GiorgioDalla

Register warden Giorgio

---

_data/handles/ulqiorra.json

Auto-generated PR to register the new warden ulqiorra

Register warden ulqiorra

---

_data/handles/CallMeAgent.json

Auto-generated PR to register the new warden CallMeAgent

Register warden CallMeAgent

---

_data/handles/myusuf.json

Auto-generated PR to register the new warden myusuf

Register warden myusuf

---

_data/handles/stepheljobs.json

Auto-generated PR to register the new warden stepheljobs

Register warden stepheljobs

---

_data/handles/Prof_Xazus.json

Auto-generated PR to register the new warden Prof_Xazus

Register warden Prof_Xazus

---

_data/handles/0xBeirao.json

Auto-generated PR to register the new warden 0xBeirao
@Beirao

Register warden 0xBeirao

---

_data/handles/slowfi.json

Auto-generated PR to register the new warden slowfi

Register warden slowfi

---

_data/handles/0xChinedu.json

Auto-generated PR to register the new warden 0xChinedu
@mayorval

Register warden 0xChinedu

---

_data/handles/0xWeivy.json

Auto-generated PR to register the new warden 0xWeivy
@shanedunne

Register warden 0xWeivy

---

_data/handles/MisterBiter.json

Auto-generated PR to register the new warden MisterBiter

Register warden MisterBiter

---

_data/handles/gabriel.json

Auto-generated PR to register the new warden gabriel
@gabrielmanhaes

Register warden gabriel

---

_data/handles/Jasper.json

Auto-generated PR to register the new warden Jasper
@j-vp

Register warden Jasper

---

_data/handles/hello_jd.json

Auto-generated PR to register the new warden hello_jd

Register warden hello_jd

---

_data/handles/puddinnd.json

Auto-generated PR to register the new warden puddinnd
@Puddinnd

Register warden puddinnd

---

_data/handles/ethmag.json

Auto-generated PR to register the new warden ethmag
@altyni86

Register warden ethmag

---

_data/handles/sinh3ck.json

Auto-generated PR to register the new warden sinh3ck
@sinh3ck

Register warden sinh3ck

---

_data/handles/HUDAIBIA.json
_data/handles/Hudaibia.json

Auto-generated PR to register the new warden HUDAIBIA

Register warden Hudaibia

---

_data/handles/Malik_dev.json
_data/handles/malik672.json

Auto-generated PR to register the new warden malik672
@malik672

Register warden Malik_dev

---

_data/handles/king_warden_123.json

Auto-generated PR to register the new warden king_warden_123

Register warden king_warden_123

---

_data/handles/D111GENT.json

Auto-generated PR to register the new warden D111GENT
@D111GENT

Register warden D111GENT

---

_data/handles/0xGuts.json

Auto-generated PR to register the new warden 0xGuts

Register warden 0xGuts

---

_data/handles/newfolder.json

Auto-generated PR to register the new warden newfolder

Register warden newfolder

---

_data/handles/emmac002.json

Auto-generated PR to register the new warden emmac002
@ EmmaChanhy

Register warden emmac002

---

_data/handles/Guild_4.json

This auto-generated PR modifies the team Guild_4
The request was made by David_

Edit team Guild_4

---

_data/handles/DmitryN.json

Auto-generated PR to register the new warden DmitryN

Register warden DmitryN

---

_data/handles/Noahcrou.json

Reverts code-423n4/code423n4.com#7313

Revert "Register warden Noahcrou"

---

_data/handles/hacking_this.json

Auto-generated PR to register the new warden hacking_this

Register warden hacking_this

---

_data/handles/ADM.json

Auto-generated PR to register the new warden ADM

Register warden ADM

---

_data/handles/ubinatus.json

Auto-generated PR to register the new warden ubinatus
@ubinatus

Register warden ubinatus

---

_data/handles/sollee.json

Auto-generated PR to register the new warden sollee
@solleedev

Register warden sollee

---

_data/handles/siddharthkhurana160.json

Auto-generated PR to register the new warden siddharthkhurana160

Register warden siddharthkhurana160

---

_data/handles/Atheter.json

Auto-generated PR to register the new warden Atheter

Register warden Atheter

---

_data/handles/vampyre.json

Auto-generated PR to register the new warden vampyre
@Poudel0

Register warden vampyre

---

_data/handles/emerald7017.json

Auto-generated PR to register the new warden emerald7017

Register warden emerald7017

---

_data/handles/solenya.json

Auto-generated PR to register the new warden solenya

Register warden solenya

---

_data/handles/Datura.json

Auto-generated PR to register the new warden Datura

Register warden Datura

---

_data/handles/Bhourgs.json

Auto-generated PR to register the new warden Bhourgs

Register warden Bhourgs

---

_data/handles/schpiel.json

Auto-generated PR to register the new warden schpiel

Register warden schpiel

---

_data/handles/zizi.json

Auto-generated PR to register the new warden zizi

Register warden zizi

---

_data/handles/developera.json

Auto-generated PR to register the new warden developera
@https://github.com/develo-pera

Register warden developera

---

_data/handles/doctor.json

Auto-generated PR to register the new warden doctor
@https://github.com/bgxdoc

Register warden doctor

---

_data/handles/kasimonagasaki.json

Auto-generated PR to register the new warden kasimonagasaki

Register warden kasimonagasaki

---

_data/handles/eccentricexit.json

This auto-generated PR updates info for warden eccentricexit
@eccentricexit

Update warden eccentricexit

---

_data/handles/ozoooneth.json

Auto-generated PR to register the new warden ozoooneth

Register warden ozoooneth

---

_data/handles/okolicodes.json

Auto-generated PR to register the new warden okolicodes
@okolicodes7

Register warden okolicodes

---

_data/handles/fivil.json

Auto-generated PR to register the new warden fivil
@fivil

Register warden fivil

---

_data/handles/Emmanuel.json

Auto-generated PR to register the new warden Emmanuel
@Emedudu

Register warden Emmanuel

---

_data/handles/jsnelson_.json

Auto-generated PR to register the new warden jsnelson_
@https://github.com/jaysnel

Register warden jsnelson_

---

_data/handles/illiquidata.json

Auto-generated PR to register the new warden illiquidata
@illiquidata

Register warden illiquidata

---

_data/handles/Sulpiride.json

Auto-generated PR to register the new warden Sulpiride
@marie-fourier

Register warden Sulpiride

---

_data/handles/an0n_auditor.json

Auto-generated PR to register the new warden an0n_auditor
@dhruvmalik007

Register warden an0n_auditor

---

_data/handles/SuperRayss.json

Auto-generated PR to register the new warden SuperRayss
@SuperRayss

Register warden SuperRayss

---

_data/handles/0xharold.json

Auto-generated PR to register the new warden 0xharold

Register warden 0xharold

---

_data/handles/taknev83.json

Auto-generated PR to register the new warden taknev83
@taknev83

Register warden taknev83

---

_data/handles/MostV.json

Auto-generated PR to register the new warden MostV
@shacharniv

Register warden MostV

---

_data/handles/robg.json

Auto-generated PR to register the new warden robg

Register warden robg

---

_data/handles/foxb868.json

Auto-generated PR to register the new warden foxb868

Register warden foxb868

---

_data/handles/dutra.json

Auto-generated PR to register the new warden dutra
@dutragustavo

Register warden dutra

---

_data/handles/jon11.json

Auto-generated PR to register the new warden jon11

Register warden jon11

---

_data/handles/0x141414.json

Auto-generated PR to register the new warden 0x141414
@jacobdcastro

Register warden 0x141414

---

_data/handles/HarishGunjalli.json

Auto-generated PR to register the new warden HarishGunjalli
@iHarishKumar

Register warden HarishGunjalli

---

_data/handles/molehZey.json

Auto-generated PR to register the new warden molehZey
@moleh13

Register warden molehZey

---

_data/handles/i18nchain.json

Auto-generated PR to register the new warden i18nchain

Register warden i18nchain

---

_data/handles/xiaohuo.json

Auto-generated PR to register the new warden xiaohuo
@renlulu

Register warden xiaohuo

---

_data/handles/GoWBlockChain.json

Auto-generated PR to register the new warden GoWBlockChain

Register warden GoWBlockChain

---

_data/handles/1shut.json

Auto-generated PR to register the new warden 1shut
@0mMadnani

Register warden 1shut

---

_data/handles/dibbydoda.json

Auto-generated PR to register the new warden dibbydoda
@dibbydoda

Register warden dibbydoda

---

_data/handles/Josh4324.json

Auto-generated PR to register the new warden Josh4324
@Josh4324

Register warden Josh4324

---

_data/handles/Jammyaa.json

Auto-generated PR to register the new warden Jammyaa
@Jammyaa

Register warden Jammyaa

---

_data/handles/tunabaka.json

Auto-generated PR to register the new warden tunabaka

Register warden tunabaka

---

_data/handles/prcdev.json

Auto-generated PR to register the new warden prcdev

Register warden prcdev

---

_data/handles/0xnoob.json

Auto-generated PR to register the new warden 0xnoob

Register warden 0xnoob

---

_data/handles/0xkazim.json

Auto-generated PR to register the new warden 0xkazim
@kazimwale

Register warden 0xkazim

---

_data/handles/Remaerd369.json

Auto-generated PR to register the new warden Remaerd369

Register warden Remaerd369

---

_data/handles/alejandrocovrr.json

Auto-generated PR to register the new warden alejandrocovrr
@alejandrocova

Register warden alejandrocovrr

---

_data/handles/bombardier.json

Auto-generated PR to register the new warden bombardier
@raulmonge

Register warden bombardier

---

_data/handles/virajkokane.json

Auto-generated PR to register the new warden virajkokane
@viraj-kokane

Register warden virajkokane

---

_data/handles/dontonka.json

Auto-generated PR to register the new warden dontonka

Register warden dontonka

---

_data/handles/0xAlexandre.json

Auto-generated PR to register the new warden 0xAlexandre

Register warden 0xAlexandre

---

_data/handles/felipegscandiffio.json

Auto-generated PR to register the new warden felipegscandiffio

Register warden felipegscandiffio

---

_data/handles/shafu.json

Auto-generated PR to register the new warden shafu
@https://github.com/SharifElfouly

Register warden shafu

---

_data/handles/Rafal.json

Auto-generated PR to register the new warden Rafal
@RafalZgoda

Register warden Rafal

---

_data/handles/anshss.json

Auto-generated PR to register the new warden anshss
@anshss

Register warden anshss

---

_data/handles/rareblocks.json

Auto-generated PR to register the new warden rareblocks
@johnpaulcas

Register warden rareblocks

---

_data/handles/DeFiHackLabs.json

This auto-generated PR modifies the team DeFiHackLabs
The request was made by SunSec

Edit team DeFiHackLabs

---

_data/handles/vtemian.json

Auto-generated PR to register the new warden vtemian
@vtemian

Register warden vtemian

---

_data/handles/0xSteve.json

Auto-generated PR to register the new warden 0xSteve

Register warden 0xSteve

---

_data/handles/ApurbaPokharel.json

Auto-generated PR to register the new warden ApurbaPokharel

Register warden ApurbaPokharel

---

_data/handles/shuklaayush.json

Auto-generated PR to register the new warden shuklaayush
@shuklaayush

Register warden shuklaayush

---

_data/handles/atrixs6.json

Auto-generated PR to register the new warden atrixs6

Register warden atrixs6

---

_data/handles/TheChef.json

Auto-generated PR to register the new warden TheChef

Register warden TheChef

---

_data/handles/aswinraj94.json

Auto-generated PR to register the new warden aswinraj94
@https://github.com/aswinraj94

Register warden aswinraj94

---

_data/handles/hridyansh.json

Auto-generated PR to register the new warden hridyansh

Register warden hridyansh

---

_data/handles/a_kalout.json

Auto-generated PR to register the new warden a_kalout

Register warden a_kalout

---

_data/handles/Decentralars.json
_data/handles/decentralars.json

Auto-generated PR to register the new warden Decentralars

Register warden decentralars

---

_data/handles/0xMeWeng.json

Auto-generated PR to register the new warden 0xMeWeng
@https://github.com/melissawengbr

Register warden 0xMeWeng

---

_data/handles/Jorgect.json

Auto-generated PR to register the new warden Jorgect

Register warden Jorgect

---

_data/handles/vrajdesai78.json

Auto-generated PR to register the new warden vrajdesai78

Register warden vrajdesai78

---

_data/handles/0xbankless.json

Auto-generated PR to register the new warden 0xbankless

Register warden 0xbankless

---

_data/handles/currenthandle.json

Auto-generated PR to register the new warden currenthandle
@currenthandle

Register warden currenthandle

---

_data/handles/TheMoonCookie.json

Auto-generated PR to register the new warden TheMoonCookie
@TheMoonCookie

Register warden TheMoonCookie

---

_data/handles/aramas.json

Auto-generated PR to register the new warden aramas

Register warden aramas

---

_data/handles/bigtone.json

Auto-generated PR to register the new warden bigtone

Register warden bigtone

---

_data/handles/Antoine.json

Auto-generated PR to register the new warden Antoine
@0xKarasu

Register warden Antoine

---

_data/handles/0xmaximus.json

Auto-generated PR to register the new warden 0xmaximus

Register warden 0xmaximus

---

_data/handles/Explorers.json

This auto-generated PR creates the team Explorers

Create team Explorers

---

_data/handles/joss.json

Auto-generated PR to register the new warden joss
@jossduff

Register warden joss

---

_data/handles/Surfer_05.json

Auto-generated PR to register the new warden Surfer_05
@surfer05

Register warden Surfer_05

---

_data/handles/inmarelibero.json

Auto-generated PR to register the new warden inmarelibero
@inmarelibero

Register warden inmarelibero

---

_data/handles/macus13.json

Auto-generated PR to register the new warden macus13

Register warden macus13

---

_data/handles/Nova_FoxLeDev.json

Auto-generated PR to register the new warden Nova_FoxLeDev
@https://github.com/FoxDev12

Register warden Nova_FoxLeDev

---

_data/handles/ferdek77.json

Auto-generated PR to register the new warden ferdek77

Register warden ferdek77

---

_data/handles/Fuma.json

Auto-generated PR to register the new warden Fuma

Register warden Fuma

---

_data/handles/serial.json

Auto-generated PR to register the new warden serial
@dancankimutai

Register warden serial

---

_data/handles/nasri136.json

Auto-generated PR to register the new warden nasri136
@nasri136

Register warden nasri136

---

_data/handles/Luck.json

Auto-generated PR to register the new warden Luck

Register warden Luck

---

_data/handles/VeSKO.json

Auto-generated PR to register the new warden VeSKO
@veselin-angelov

Register warden VeSKO

---

_data/handles/0xanis.json

Auto-generated PR to register the new warden 0xanis

Register warden 0xanis

---

_data/handles/Morpheus.json

Auto-generated PR to register the new warden Morpheus

Register warden Morpheus

---

_data/handles/kriss.json

Auto-generated PR to register the new warden kriss
@krisdimitrov

Register warden kriss

---

_data/handles/sevenisalie.json

Auto-generated PR to register the new warden sevenisalie
@sevenisalie

Register warden sevenisalie

---

_data/handles/I_I_I_I.json

Auto-generated PR to register the new warden I_I_I_I

Register warden I_I_I_I

---

_data/handles/0xvj.json

Auto-generated PR to register the new warden 0xvj
@https://github.com/0xvj

Register warden 0xvj

---

_data/handles/nobody_9x.json

Auto-generated PR to register the new warden nobody_9x

Register warden nobody_9x

---

_data/handles/bshramin.json

Auto-generated PR to register the new warden bshramin
@bshramin

Register warden bshramin

---

_data/handles/P-384.json

Auto-generated PR to register the new warden P-384

Register warden P-384

---

_data/handles/c0pperscr3w3r.json

Auto-generated PR to register the new warden c0pperscr3w3r

Register warden c0pperscr3w3r

---

_data/handles/vinicius.json

Auto-generated PR to register the new warden vinicius

Register warden vinicius

---

_data/handles/CodeFoxInc.json

This auto-generated PR modifies the team CodeFoxInc
The request was made by thurendous

Edit team CodeFoxInc

---

_data/handles/0xYator.json

Auto-generated PR to register the new warden 0xYator
@JaysonYator

Register warden 0xYator

---

_data/handles/xorsec.json

Auto-generated PR to register the new warden xorsec

Register warden xorsec

---

_data/handles/Suppa.json

Auto-generated PR to register the new warden Suppa
@willschneider15

Register warden Suppa

---

_data/handles/pfedprog.json

Auto-generated PR to register the new warden pfedprog
@pfed-prog

Register warden pfedprog

---

_data/handles/vittdav.json

Auto-generated PR to register the new warden vittdav
@https://github.com/VittoriDavide

Register warden vittdav

---

_data/handles/Kangreto.json

Auto-generated PR to register the new warden Kangreto

Register warden Kangreto

---

_data/handles/Kek.json

Auto-generated PR to register the new warden Kek

Register warden Kek

---

_data/handles/vaibhavarora.json

Auto-generated PR to register the new warden vaibhavarora
@VaibhavArora19

Register warden vaibhavarora

---

_data/handles/Forest.json

Auto-generated PR to register the new warden Forest
@josiahlin119

Register warden Forest

---

_data/handles/0xsissN.json

Auto-generated PR to register the new warden 0xsissN
@0xsissN

Register warden 0xsissN

---

_data/handles/shivansh.json

Auto-generated PR to register the new warden shivansh
@shivanshxyz

Register warden shivansh

---

_data/handles/Yologarch.json

Auto-generated PR to register the new warden Yologarch

Register warden Yologarch

---

_data/handles/mojito_auditor.json

Auto-generated PR to register the new warden mojito_auditor
@mojito-auditor

Register warden mojito_auditor

---

_data/handles/shealtielanz.json

Auto-generated PR to register the new warden shealtielanz
@shealtielanz

Register warden shealtielanz

---

_data/handles/0xkippa14.json

Auto-generated PR to register the new warden 0xkippa14
@marenga14

Register warden 0xkippa14

---

_data/handles/rohitscode.json

Auto-generated PR to register the new warden rohitscode
@rohitverse

Register warden rohitscode

---

_data/handles/punpom.json

Auto-generated PR to register the new warden punpom

Register warden punpom

---

_data/handles/whoismatthewmc1.json

Auto-generated PR to register the new warden whoismatthewmc1

Register warden whoismatthewmc1

---

_data/handles/c0pp3rscr3w3r.json

Auto-generated PR to register the new warden c0pp3rscr3w3r

Register warden c0pp3rscr3w3r

---

_data/handles/makumba.json

Auto-generated PR to register the new warden makumba

Register warden makumba

---

_data/handles/0xeix.json

Auto-generated PR to register the new warden 0xeix

Register warden 0xeix

---

_data/handles/0xHillbilly.json

Auto-generated PR to register the new warden 0xHillbilly

Register warden 0xHillbilly

---

_data/handles/young.json

Auto-generated PR to register the new warden young
@yang94j

Register warden young
