code-423n4/code423n4.com

_data/handles/deadrxsezzz.json

Auto-generated PR to register the new warden deadrxsezzz
@iamjakethehuman

Register warden deadrxsezzz

---

_data/handles/Saviour.json

Auto-generated PR to register the new warden Saviour

Register warden Saviour

---

_data/handles/corbo.json

Auto-generated PR to register the new warden corbo
@corbo369

Register warden corbo

---

_data/handles/mmatila.json

Auto-generated PR to register the new warden mmatila
@mmatila

Register warden mmatila

---

_data/handles/beesh.json

Auto-generated PR to register the new warden beesh
@beeshalrizal

Register warden beesh

---

_data/handles/koka.json

Auto-generated PR to register the new warden koka
@muzafar91221

Register warden koka

---

_data/handles/0xrhsmt.json

Auto-generated PR to register the new warden 0xrhsmt
@0xrhsmt

Register warden 0xrhsmt

---

_data/handles/TLS.json

Auto-generated PR to register the new warden TLS
@topji

Register warden TLS

---

_data/handles/jascd.json

Auto-generated PR to register the new warden jascd

Register warden jascd

---

_data/handles/rootofeight.json

Auto-generated PR to register the new warden rootofeight
@asutosh05

Register warden rootofeight

---

_data/handles/Mrbean.json

Auto-generated PR to register the new warden Mrbean

Register warden Mrbean

---

_data/handles/TGM.json

Auto-generated PR to register the new warden TGM

Register warden TGM

---

_data/handles/DanielTan.json

Auto-generated PR to register the new warden DanielTan
@tanliwei

Register warden DanielTan

---

_data/handles/karthik06.json

Auto-generated PR to register the new warden karthik06

Register warden karthik06

---

_data/handles/Explorers.json

This auto-generated PR modifies the team Explorers
The request was made by N16H7M4R3

Edit team Explorers

---

_data/handles/tonyke.json

Auto-generated PR to register the new warden tonyke
@thagki9

Register warden tonyke

---

_data/handles/gr8h.json

Auto-generated PR to register the new warden gr8h
@gr8h

Register warden gr8h

---

_data/handles/scsrye.json

Auto-generated PR to register the new warden scsrye

Register warden scsrye

---

_data/handles/z1c0.json

Auto-generated PR to register the new warden z1c0

Register warden z1c0

---

_data/handles/Mouradif.json

Auto-generated PR to register the new warden Mouradif
@Mouradif

Register warden Mouradif

---

_data/handles/gaoxiaodiao.json

Auto-generated PR to register the new warden gaoxiaodiao
@gaoxiaodiao

Register warden gaoxiaodiao

---

_data/handles/guzus.json

Auto-generated PR to register the new warden guzus

Register warden guzus

---

_data/handles/iglyx.json

Auto-generated PR to register the new warden iglyx

Register warden iglyx

---

_data/handles/blankf1sh.json

Auto-generated PR to register the new warden blankf1sh
@blankf1sh

Register warden blankf1sh

---

_data/handles/0x6020c0.json

Auto-generated PR to register the new warden 0x6020c0

Register warden 0x6020c0

---

_data/handles/Icarium.json

Auto-generated PR to register the new warden Icarium
@0xicarium

Register warden Icarium

---

_data/handles/Brenzee.json

Auto-generated PR to register the new warden Brenzee
@Brenzee

Register warden Brenzee

---

_data/handles/MadhuVarunChimmani.json

Auto-generated PR to register the new warden MadhuVarunChimmani

Register warden MadhuVarunChimmani

---

_data/handles/geluso.json

Auto-generated PR to register the new warden geluso
@geluso

Register warden geluso

---

_data/handles/cryptox.json

Auto-generated PR to register the new warden cryptox

Register warden cryptox

---

_data/handles/p0wd3r.json

Auto-generated PR to register the new warden p0wd3r

Register warden p0wd3r

---

_data/handles/stoxophone.json

Auto-generated PR to register the new warden stoxophone

Register warden stoxophone

---

_data/handles/PawelK.json

Auto-generated PR to register the new warden PawelK
@KedziaPawel

Register warden PawelK

---

_data/handles/al_sirang.json

Auto-generated PR to register the new warden al_sirang

Register warden al_sirang

---

_data/handles/cryptoweb3.json

Auto-generated PR to register the new warden cryptoweb3

Register warden cryptoweb3

---

_data/handles/rebirthIsNear.json

Auto-generated PR to register the new warden rebirthIsNear

Register warden rebirthIsNear

---

_data/handles/shapeshifter.json

Auto-generated PR to register the new warden shapeshifter

Register warden shapeshifter

---

_data/handles/exp_table.json

Auto-generated PR to register the new warden exp_table
@exp.table#9120

Register warden exp_table

---

_data/handles/manizzle.json

Auto-generated PR to register the new warden manizzle

Register warden manizzle

---

_data/handles/wonjun.json

Auto-generated PR to register the new warden wonjun
@wonjun27

Register warden wonjun

---

_data/handles/8545-J.json

Auto-generated PR to register the new warden 8545-J
@8545-J

Register warden 8545-J

---

_data/handles/halhackman.json

Auto-generated PR to register the new warden halhackman

Register warden halhackman

---

_data/handles/fatal.json

Auto-generated PR to register the new warden fatal

Register warden fatal

---

_data/handles/ontheway.json

Auto-generated PR to register the new warden ontheway

Register warden ontheway

---

_data/handles/imdeadpool.json

Auto-generated PR to register the new warden imdeadpool
@chaitanyasjoshi

Register warden imdeadpool

---

_data/handles/PacificaCrypto.json

Auto-generated PR to register the new warden PacificaCrypto
@PacificaCrypto

Register warden PacificaCrypto

---

_data/handles/SailorRoyal.json

Auto-generated PR to register the new warden SailorRoyal
@finknj

Register warden SailorRoyal

---

_data/handles/ni8mare.json

Auto-generated PR to register the new warden ni8mare
@NishithPat

Register warden ni8mare

---

_data/handles/rokso.json

Auto-generated PR to register the new warden rokso

Register warden rokso

---

_data/handles/yudan.json

Auto-generated PR to register the new warden yudan

Register warden yudan

---

_data/handles/BilalZulfiqar.json

Auto-generated PR to register the new warden BilalZulfiqar
@BilalXulfiqar

Register warden BilalZulfiqar

---

_data/handles/bugradar.json

Auto-generated PR to register the new warden bugradar

Register warden bugradar

---

_data/handles/m4ttm.json

Auto-generated PR to register the new warden m4ttm
@m4ttm

Register warden m4ttm

---

_data/handles/BlockBuster.json

Auto-generated PR to register the new warden BlockBuster
@Humbleblocks

Register warden BlockBuster

---

_data/handles/20urc3.json

Auto-generated PR to register the new warden 20urc3

Register warden 20urc3

---

_data/handles/0x8e88.json

Auto-generated PR to register the new warden 0x8e88
@igroomgrim

Register warden 0x8e88

---

_data/handles/Siege.json

Auto-generated PR to register the new warden Siege
@siegedetect

Register warden Siege

---

_data/handles/dskweb3.json

Auto-generated PR to register the new warden dskweb3

Register warden dskweb3

---

_data/handles/Patr.json

Auto-generated PR to register the new warden Patr

Register warden Patr

---

_data/handles/0xffee.json

Auto-generated PR to register the new warden 0xffee

Register warden 0xffee

---

_data/handles/LFY.json

Auto-generated PR to register the new warden LFY

Register warden LFY

---

_data/handles/0xGDSR.json

Auto-generated PR to register the new warden 0xGDSR
@0xGDSR

Register warden 0xGDSR

---

_data/handles/ReckTie.json

Auto-generated PR to register the new warden ReckTie
@ReckTie

Register warden ReckTie

---

_data/handles/tnquanghuy0512.json

Auto-generated PR to register the new warden tnquanghuy0512

Register warden tnquanghuy0512

---

_data/handles/sz14th.json

Auto-generated PR to register the new warden sz14th
@sz41th

Register warden sz14th

---

_data/handles/pangea.json

Auto-generated PR to register the new warden pangea
@ctian1

Register warden pangea

---

_data/handles/jabher.json

Auto-generated PR to register the new warden jabher
@jabher

Register warden jabher

---

_data/handles/blockxx.json

Auto-generated PR to register the new warden blockxx

Register warden blockxx

---

_data/handles/pkit.json

Auto-generated PR to register the new warden pkit

Register warden pkit

---

_data/handles/Serhat.json

Auto-generated PR to register the new warden Serhat
@SerhatCelikk

Register warden Serhat

---

_data/handles/_Deleted.json

Auto-generated PR to register the new warden _Deleted

Register warden _Deleted

---

_data/handles/kji304.json

Auto-generated PR to register the new warden kji304
@kji304

Register warden kji304

---

_data/handles/0xKRN.json

Auto-generated PR to register the new warden 0xKRN
@0xKRN

Register warden 0xKRN

---

_data/handles/cryptonoob2k.json

Auto-generated PR to register the new warden cryptonoob2k
@cryptonoob2k

Register warden cryptonoob2k

---

_data/handles/OxfordStreet.json

Auto-generated PR to register the new warden OxfordStreet

Register warden OxfordStreet

---

_data/handles/Bauchibred.json

Auto-generated PR to register the new warden Bauchibred
@Bauchibred

Register warden Bauchibred

---

_data/handles/prapandey031.json

Auto-generated PR to register the new warden prapandey031
@Ys-Prakash

Register warden prapandey031

---

_data/handles/Anirruth.json

Auto-generated PR to register the new warden Anirruth

Register warden Anirruth

---

_data/handles/tataky.json

Auto-generated PR to register the new warden tataky

Register warden tataky

---

_data/handles/axiom.json

Auto-generated PR to register the new warden axiom

Register warden axiom

---

_data/handles/osgood.json

Auto-generated PR to register the new warden osgood

Register warden osgood

---

_data/handles/Rainmaker.json

Auto-generated PR to register the new warden Rainmaker
@RainmakerSec

Register warden Rainmaker

---

_data/handles/Emc2.json

Auto-generated PR to register the new warden Emc2

Register warden Emc2

---

_data/handles/mandaloriansecurity.json

Auto-generated PR to register the new warden mandaloriansecurity

Register warden mandaloriansecurity

---

_data/handles/Godfather.json

Auto-generated PR to register the new warden Godfather

Register warden Godfather

---

_data/handles/Ant.json

Auto-generated PR to register the new warden Ant
@Ant

Register warden Ant

---

_data/handles/ms888.json

Auto-generated PR to register the new warden ms888

Register warden ms888

---

_data/handles/sajib5219.json

Auto-generated PR to register the new warden sajib5219

Register warden sajib5219

---

_data/handles/sunshinevendetta.json

Auto-generated PR to register the new warden sunshinevendetta
@sunshinevendetta

Register warden sunshinevendetta

---

_data/handles/mhmmtgms.json

Auto-generated PR to register the new warden mhmmtgms

Register warden mhmmtgms

---

_data/handles/ravel.json

Auto-generated PR to register the new warden ravel
@0xRavel

Register warden ravel

---

_data/handles/xAlismx.json

Auto-generated PR to register the new warden xAlismx

Register warden xAlismx

---

_data/handles/ronakgupta11.json

Auto-generated PR to register the new warden ronakgupta11
@ronakgupta11

Register warden ronakgupta11

---

_data/handles/bart1e.json

Auto-generated PR to register the new warden bart1e

Register warden bart1e

---

_data/handles/Arnaldo.json

Auto-generated PR to register the new warden Arnaldo

Register warden Arnaldo

---

_data/handles/JerryKwan.json

Auto-generated PR to register the new warden JerryKwan

Register warden JerryKwan

---

_data/handles/twicek.json

Auto-generated PR to register the new warden twicek

Register warden twicek

---

_data/handles/Resistor.json

Auto-generated PR to register the new warden Resistor

Register warden Resistor

---

_data/handles/aitor.json

Auto-generated PR to register the new warden aitor
@https://github.com/aitorzaldua

Register warden aitor

---

_data/handles/0xGordita.json

Auto-generated PR to register the new warden 0xGordita

Register warden 0xGordita

---

_data/handles/Punisher.json

Auto-generated PR to register the new warden Punisher

Register warden Punisher

---

_data/handles/xthezealot.json

Auto-generated PR to register the new warden xthezealot

Register warden xthezealot

---

_data/handles/BlueAlder.json

Auto-generated PR to register the new warden BlueAlder
@BlueAlder

Register warden BlueAlder

---

_data/handles/pxgnome.json

Auto-generated PR to register the new warden pxgnome
@pxgnome

Register warden pxgnome

---

_data/handles/Hassan.json

Auto-generated PR to register the new warden Hassan
@Hassan19

Register warden Hassan

---

_data/handles/Angry_Mustache_Man.json

Auto-generated PR to register the new warden Angry_Mustache_Man

Register warden Angry_Mustache_Man

---

_data/handles/0x_Scar.json

Auto-generated PR to register the new warden 0x_Scar

Register warden 0x_Scar

---

_data/handles/lst4r.json

Auto-generated PR to register the new warden lst4r
@l5t4r

Register warden lst4r

---

_data/handles/Omarsultan.json

Auto-generated PR to register the new warden Omarsultan

Register warden Omarsultan

---

_data/handles/Wander.json

This auto-generated PR creates the team Wander

Create team Wander

---

_data/handles/sh3rcrypt0.json

Auto-generated PR to register the new warden sh3rcrypt0

Register warden sh3rcrypt0

---

_data/handles/JcFichtner.json

Auto-generated PR to register the new warden JcFichtner

Register warden JcFichtner

---

_data/handles/llamatest.json

Auto-generated PR to register the new warden llamatest

Register warden llamatest

---

_data/handles/elstrak.json

Auto-generated PR to register the new warden elstrak
@elstrak

Register warden elstrak

---

_data/handles/0xsomegirl.json

Auto-generated PR to register the new warden 0xsomegirl
@0xaxxi

Register warden 0xsomegirl

---

_data/handles/mitsulino.json

Auto-generated PR to register the new warden mitsulino

Register warden mitsulino

---

_data/handles/baihu.json

Auto-generated PR to register the new warden baihu

Register warden baihu

---

_data/handles/pistomat_eth.json

Auto-generated PR to register the new warden pistomat_eth
@pistomat

Register warden pistomat_eth

---

_data/handles/porcelainthrone.json

Auto-generated PR to register the new warden porcelainthrone

Register warden porcelainthrone

---

_data/handles/sahil_k.json

Auto-generated PR to register the new warden sahil_k
@meanMonk

Register warden sahil_k

---

_data/handles/ihtishamsudo.json

Auto-generated PR to register the new warden ihtishamsudo
@ihtisham-sudo

Register warden ihtishamsudo

---

_data/handles/Akshata.json

Auto-generated PR to register the new warden Akshata

Register warden Akshata

---

_data/handles/todorc.json

Auto-generated PR to register the new warden todorc
@https://github.com/todorchomakov

Register warden todorc

---

_data/handles/mastafis.json

Auto-generated PR to register the new warden mastafis
@Mastafis

Register warden mastafis

---

_data/handles/bizhaohui.json

Auto-generated PR to register the new warden bizhaohui

Register warden bizhaohui

---

_data/handles/Sabit.json

Auto-generated PR to register the new warden Sabit

Register warden Sabit

---

_data/handles/hasmama.json

Auto-generated PR to register the new warden hasmama
@hasmama

Register warden hasmama

---

_data/handles/oreztker.json

Auto-generated PR to register the new warden oreztker

Register warden oreztker

---

_data/handles/gpsfly.json

Auto-generated PR to register the new warden gpsfly

Register warden gpsfly

---

_data/handles/moonman.json

Auto-generated PR to register the new warden moonman
@vv1nn

Register warden moonman

---

_data/handles/40pt.json

Auto-generated PR to register the new warden 40pt
@40p7

Register warden 40pt

---

_data/handles/waanwan.json

Auto-generated PR to register the new warden waanwan

Register warden waanwan

---

_data/handles/mehran5683.json

Auto-generated PR to register the new warden mehran5683

Register warden mehran5683

---

_data/handles/rfigueiredo.json

Auto-generated PR to register the new warden rfigueiredo
@rutefig

Register warden rfigueiredo

---

_data/handles/Arabadzhiev.json

Auto-generated PR to register the new warden Arabadzhiev
@Arabadzhiew

Register warden Arabadzhiev

---

_data/handles/rapha92.json

Auto-generated PR to register the new warden rapha92

Register warden rapha92

---

_data/handles/awararesearcher.json

Auto-generated PR to register the new warden awararesearcher

Register warden awararesearcher

---

_data/handles/Naresh.json

Auto-generated PR to register the new warden Naresh

Register warden Naresh

---

_data/handles/polarf0x.json

Auto-generated PR to register the new warden polarf0x
@BinaryKhaos

Register warden polarf0x

---

_data/handles/minashiro.json

Auto-generated PR to register the new warden minashiro

Register warden minashiro

---

_data/handles/jmcph4.json

Auto-generated PR to register the new warden jmcph4
@jmcph4

Register warden jmcph4

---

_data/handles/noizman.json

Auto-generated PR to register the new warden noizman
@aa-wong

Register warden noizman

---

_data/handles/Stormreckson.json

Auto-generated PR to register the new warden Stormreckson

Register warden Stormreckson

---

_data/handles/PetarTolev.json

Auto-generated PR to register the new warden PetarTolev

Register warden PetarTolev

---

_data/handles/berlin-101.json

Auto-generated PR to register the new warden berlin-101
@snietert

Register warden berlin-101

---

_data/handles/oppenheimer.json

Auto-generated PR to register the new warden oppenheimer

Register warden oppenheimer

---

_data/handles/chriszhou.json

Auto-generated PR to register the new warden chriszhou

Register warden chriszhou

---

_data/handles/0xMosh.json

Auto-generated PR to register the new warden 0xMosh

Register warden 0xMosh

---

_data/handles/0x1om.json

Auto-generated PR to register the new warden 0x1om

Register warden 0x1om

---

_data/handles/gztttt.json

Auto-generated PR to register the new warden gztttt

Register warden gztttt

---

_data/handles/0xSwahili.json

Auto-generated PR to register the new warden 0xSwahili

Register warden 0xSwahili

---

_data/handles/wandeoki.json

Auto-generated PR to register the new warden wandeoki
@dayo-adewuyi

Register warden wandeoki

---

_data/handles/rivalq.json

Auto-generated PR to register the new warden rivalq
@rivalq

Register warden rivalq

---

_data/handles/kevweb3dev.json

Auto-generated PR to register the new warden kevweb3dev

Register warden kevweb3dev

---

_data/handles/0xLook.json

Auto-generated PR to register the new warden 0xLook

Register warden 0xLook

---

_data/handles/ks__xxxxx.json

Auto-generated PR to register the new warden ks__xxxxx

Register warden ks__xxxxx

---

_data/handles/Smile.json

Auto-generated PR to register the new warden Smile

Register warden Smile

---

_data/handles/chainlight.json

Auto-generated PR to register the new warden chainlight
@this-is-chainlight

Register warden chainlight

---

_data/handles/wiredhikari.json

Auto-generated PR to register the new warden wiredhikari
@wiredhikari

Register warden wiredhikari

---

_data/handles/roelio.json

Auto-generated PR to register the new warden roelio

Register warden roelio

---

_data/handles/pep7siup.json

Auto-generated PR to register the new warden pep7siup
@https://github.com/hungdoo

Register warden pep7siup

---

_data/handles/WGMIApe.json

Auto-generated PR to register the new warden WGMIApe
@darian-ae

Register warden WGMIApe

---

_data/handles/cr0.json

Auto-generated PR to register the new warden cr0
@arbitrary_cr0

Register warden cr0

---

_data/handles/th13vn.json

Auto-generated PR to register the new warden th13vn
@th13vn

Register warden th13vn

---

_data/handles/0xAnto.json

Auto-generated PR to register the new warden 0xAnto
@0xAnto

Register warden 0xAnto

---

_data/handles/Cryptoflop.json

Auto-generated PR to register the new warden Cryptoflop
@maxdavidwow

Register warden Cryptoflop

---

_data/handles/0xbluehack.json

Auto-generated PR to register the new warden 0xbluehack

Register warden 0xbluehack

---

_data/handles/clayj.json

Auto-generated PR to register the new warden clayj

Register warden clayj

---

_data/handles/0xl51.json

Auto-generated PR to register the new warden 0xl51

Register warden 0xl51

---

_data/handles/Inspex.json

This auto-generated PR modifies the team Inspex
The request was made by DeStinE21

Edit team Inspex

---

_data/handles/Voyvoda.json

This auto-generated PR creates the team Voyvoda

Create team Voyvoda

---

_data/handles/yac.json

This auto-generated PR modifies the team yac
The request was made by usmannk

Edit team yac

---

_data/handles/luniacllama.json

Auto-generated PR to register the new warden luniacllama
@issa-me-sush

Register warden luniacllama

---

_data/handles/Jaymoney.json

Auto-generated PR to register the new warden Jaymoney

Register warden Jaymoney

---

_data/handles/parsekon.json

Auto-generated PR to register the new warden parsekon
@parsekon

Register warden parsekon

---

_data/handles/Straccio.json

Auto-generated PR to register the new warden Straccio
@FJ-Riveros

Register warden Straccio

---

_data/handles/ArbitraryExecution.json

This auto-generated PR modifies the team ArbitraryExecution
The request was made by cr0

Edit team ArbitraryExecution

---

_data/handles/PrintfJoby.json

Auto-generated PR to register the new warden PrintfJoby
@https://github.com/printfjoby

Register warden PrintfJoby

---

_data/handles/nirlin.json

Auto-generated PR to register the new warden nirlin
@ahmaddecoded

Register warden nirlin

---

_data/handles/dongfangbai258.json

Auto-generated PR to register the new warden dongfangbai258

Register warden dongfangbai258

---

_data/handles/Justus.json

Auto-generated PR to register the new warden Justus

Register warden Justus

---

_data/handles/svalk.json

Auto-generated PR to register the new warden svalk
@stanislavyv

Register warden svalk

---

_data/handles/shakti.json

Auto-generated PR to register the new warden shakti

Register warden shakti

---

_data/handles/emf99.json

Auto-generated PR to register the new warden emf99

Register warden emf99

---

_data/handles/ovcharov.json

Auto-generated PR to register the new warden ovcharov
@SortedIvan

Register warden ovcharov

---

_data/handles/NikolayKostadinov.json

Auto-generated PR to register the new warden NikolayKostadinov

Register warden NikolayKostadinov

---

_data/handles/rch.json

Auto-generated PR to register the new warden rch

Register warden rch

---

_data/handles/bulaimaslo.json

Auto-generated PR to register the new warden bulaimaslo
@bulaimaslo

Register warden bulaimaslo

---

_data/handles/akrikan.json

Auto-generated PR to register the new warden akrikan

Register warden akrikan

---

_data/handles/amixra.json

Auto-generated PR to register the new warden amixra

Register warden amixra

---

_data/handles/Elysio.json

Auto-generated PR to register the new warden Elysio

Register warden Elysio

---

_data/handles/BenRai.json

Auto-generated PR to register the new warden BenRai

Register warden BenRai

---

_data/handles/adidiborg.json

Auto-generated PR to register the new warden adidiborg
@adidiborg

Register warden adidiborg

---

_data/handles/ChaseTheLight.json

Auto-generated PR to register the new warden ChaseTheLight

Register warden ChaseTheLight

---

_data/handles/Pingger.json

Auto-generated PR to register the new warden Pingger

Register warden Pingger

---

_data/handles/Noro.json

Auto-generated PR to register the new warden Noro
@NoroMeb

Register warden Noro

---

_data/handles/Amarjeet.json

Auto-generated PR to register the new warden Amarjeet
@https://github.com/cse-amarjeet

Register warden Amarjeet

---

_data/handles/4erik.json

Auto-generated PR to register the new warden 4erik

Register warden 4erik

---

_data/handles/abidin.json

Auto-generated PR to register the new warden abidin
@abidinco

Register warden abidin

---

_data/handles/DishWasher.json

Auto-generated PR to register the new warden DishWasher
@JohannesSchulz97

Register warden DishWasher

---

_data/handles/RodolfoCastellani.json

Auto-generated PR to register the new warden RodolfoCastellani
@rodolfocastellani

Register warden RodolfoCastellani

---

_data/handles/0xx_Ninja.json

Auto-generated PR to register the new warden 0xx_Ninja

Register warden 0xx_Ninja

---

_data/handles/leo.json

Auto-generated PR to register the new warden leo

Register warden leo

---

_data/handles/LosPollosHermanos.json

This auto-generated PR modifies the team LosPollosHermanos
The request was made by scaraven

Edit team LosPollosHermanos

---

_data/handles/Xenesthis.json

Auto-generated PR to register the new warden Xenesthis

Register warden Xenesthis

---

_data/handles/Voyvoda.json

This auto-generated PR modifies the team Voyvoda
The request was made by gogo

Edit team Voyvoda

---

_data/handles/Koustre.json

This auto-generated PR updates info for warden Koustre

Update warden Koustre

---

_data/handles/0x4db5362c.json

Auto-generated PR to register the new warden 0x4db5362c

Register warden 0x4db5362c

---

_data/handles/Z3R0.json

Auto-generated PR to register the new warden Z3R0
@https://github.com/th3outcast

Register warden Z3R0

---

_data/handles/sohrubh.json

Auto-generated PR to register the new warden sohrubh
@sohrubh

Register warden sohrubh

---

_data/handles/0x9k.json

Auto-generated PR to register the new warden 0x9k

Register warden 0x9k

---

_data/handles/ChrisTina.json

Auto-generated PR to register the new warden ChrisTina

Register warden ChrisTina

---

_data/handles/onyigerald630.json

Auto-generated PR to register the new warden onyigerald630

Register warden onyigerald630

---

_data/handles/0xRay.json

Auto-generated PR to register the new warden 0xRay
@RayA44

Register warden 0xRay

---

_data/handles/habive.json

Auto-generated PR to register the new warden habive

Register warden habive

---

_data/handles/0xmoca.json

Auto-generated PR to register the new warden 0xmoca
@0xmoca

Register warden 0xmoca

---

_data/handles/rensr.json

Auto-generated PR to register the new warden rensr

Register warden rensr

---

_data/handles/Freestyle.json

Auto-generated PR to register the new warden Freestyle

Register warden Freestyle

---

_data/handles/beaverx00.json

Auto-generated PR to register the new warden beaverx00
@beaverx00

Register warden beaverx00

---

_data/handles/light.json

Auto-generated PR to register the new warden light

Register warden light

---

_data/handles/SleepingShell.json

Auto-generated PR to register the new warden SleepingShell
@SleepingShell

Register warden SleepingShell

---

_data/handles/GT_Blockchain.json

This auto-generated PR creates the team GT_Blockchain

Create team GT_Blockchain

---

_data/handles/frenchkebab.json

Auto-generated PR to register the new warden frenchkebab

Register warden frenchkebab

---

_data/handles/petrichor.json

Auto-generated PR to register the new warden petrichor

Register warden petrichor

---

_data/handles/negin.json

Auto-generated PR to register the new warden negin
@https://github.com/Negin-Az

Register warden negin

---

_data/handles/smaul0.json

This auto-generated PR creates the team smaul0

Create team smaul0

---

_data/handles/MrBhaer.json

Auto-generated PR to register the new warden MrBhaer

Register warden MrBhaer

---

_data/handles/0xbfcadd6e.json

Auto-generated PR to register the new warden 0xbfcadd6e
@https://github.com/0xbfcadd6e

Register warden 0xbfcadd6e

---

_data/handles/0xRan4212.json

Auto-generated PR to register the new warden 0xRan4212

Register warden 0xRan4212

---

_data/handles/0xfelipe.json

Auto-generated PR to register the new warden 0xfelipe
@kamikazebr

Register warden 0xfelipe

---

_data/handles/Unstacked.json

Auto-generated PR to register the new warden Unstacked
@akerbabber

Register warden Unstacked

---

_data/handles/Plasmablocks.json

This auto-generated PR creates the team Plasmablocks

Create team Plasmablocks

---

_data/handles/BGSecurity.json

This auto-generated PR creates the team BGSecurity

Create team BGSecurity

---

_data/handles/Rowan.json

Auto-generated PR to register the new warden Rowan

Register warden Rowan

---

_data/handles/GhK3Ndf.json

Auto-generated PR to register the new warden GhK3Ndf
@hGq2Wnl

Register warden GhK3Ndf

---

_data/handles/xliiauo.json

Auto-generated PR to register the new warden xliiauo
@xliiauo

Register warden xliiauo

---

_data/handles/CryptoCraze.json

This auto-generated PR modifies the team CryptoCraze
The request was made by jekapi

Edit team CryptoCraze

---

_data/handles/donutcakes.json

Auto-generated PR to register the new warden donutcakes

Register warden donutcakes

---

_data/handles/parlayan_yildizlar_takimi.json

This auto-generated PR creates the team parlayan_yildizlar_takimi

Create team parlayan_yildizlar_takimi

---

_data/handles/bruno75.json

Auto-generated PR to register the new warden bruno75

Register warden bruno75

---

_data/handles/MIM.json

Auto-generated PR to register the new warden MIM

Register warden MIM

---

_data/handles/Tama.json

Auto-generated PR to register the new warden Tama

Register warden Tama

---

_data/handles/fluzzy_puzzy.json

Auto-generated PR to register the new warden fluzzy_puzzy

Register warden fluzzy_puzzy

---

_data/handles/0xNewtScamander.json

Auto-generated PR to register the new warden 0xNewtScamander

Register warden 0xNewtScamander

---

gatsby-node.esm.js
netlify/functions/manage-findings.ts
package.json

Distribute GitHub API calls among tokens

---

_data/handles/bch15.json

Auto-generated PR to register the new warden bch15

Register warden bch15

---

_data/handles/a0xb.json

Auto-generated PR to register the new warden a0xb

Register warden a0xb

---

_data/handles/SmartGooofy.json

Auto-generated PR to register the new warden SmartGooofy

Register warden SmartGooofy

---

_data/handles/Aizensosouke.json

Auto-generated PR to register the new warden Aizensosouke
@tazar

Register warden Aizensosouke

---

_data/handles/Ellena.json

Auto-generated PR to register the new warden Ellena

Register warden Ellena

---

_data/handles/Aurora.json

Auto-generated PR to register the new warden Aurora

Register warden Aurora

---

_data/handles/Dyear.json

Auto-generated PR to register the new warden Dyear
@guh123

Register warden Dyear

---

_data/handles/0xdastar.json

Auto-generated PR to register the new warden 0xdastar

Register warden 0xdastar

---

_data/handles/xynk.json

Auto-generated PR to register the new warden xynk

Register warden xynk

---

_data/handles/Krieger.json

Auto-generated PR to register the new warden Krieger
@startup-dreamer

Register warden Krieger

---

_data/handles/BuckWang.json

Auto-generated PR to register the new warden BuckWang
@BuckWang0509

Register warden BuckWang

---

_data/handles/Azaryan.json

Auto-generated PR to register the new warden Azaryan

Register warden Azaryan

---

_data/handles/Mingx.json

Auto-generated PR to register the new warden Mingx

Register warden Mingx

---

_data/handles/Zoer.json

Auto-generated PR to register the new warden Zoer

Register warden Zoer

---

_data/handles/Stephd.json

Auto-generated PR to register the new warden Stephd

Register warden Stephd

---

_data/handles/Stunner.json

Auto-generated PR to register the new warden Stunner

Register warden Stunner

---

_data/handles/hals.json

Auto-generated PR to register the new warden hals
@HalaNHasan

Register warden hals

---

_data/handles/circlelooper.json

Auto-generated PR to register the new warden circlelooper

Register warden circlelooper

---

_data/handles/junan.json

Auto-generated PR to register the new warden junan

Register warden junan

---

_data/handles/hyeon.json

Auto-generated PR to register the new warden hyeon

Register warden hyeon

---

_data/handles/ChainHunters.json

This auto-generated PR creates the team ChainHunters

Create team ChainHunters

---

_data/handles/mov.json

Auto-generated PR to register the new warden mov

Register warden mov

---

_data/handles/Sage.json

Auto-generated PR to register the new warden Sage

Register warden Sage

---

_data/handles/0x2e.json

Auto-generated PR to register the new warden 0x2e

Register warden 0x2e

---

_data/handles/lil_eth.json

Auto-generated PR to register the new warden lil_eth
@nasri136

Register warden lil_eth

---

_data/handles/Joyious.json

Auto-generated PR to register the new warden Joyious

Register warden Joyious

---

_data/handles/Next_Wh4le6.json

Auto-generated PR to register the new warden Next_Wh4le6

Register warden Next_Wh4le6

---

_data/handles/boldrack.json

Auto-generated PR to register the new warden boldrack
@boldrack

Register warden boldrack

---

_data/handles/khramov.json

Auto-generated PR to register the new warden khramov

Register warden khramov

---

_data/handles/smatthewenglish.json

Auto-generated PR to register the new warden smatthewenglish
@smatthewenglish

Register warden smatthewenglish

---

_data/handles/xaini.json

Auto-generated PR to register the new warden xaini

Register warden xaini

---

_data/handles/js.json

Auto-generated PR to register the new warden js
@juansolana

Register warden js

---

_data/handles/hscgavin.json

Auto-generated PR to register the new warden hscgavin

Register warden hscgavin

---

_data/handles/thetechnofeak.json

Auto-generated PR to register the new warden thetechnofeak

Register warden thetechnofeak

---

_data/handles/7dee.json

Auto-generated PR to register the new warden 7dee
@tden123

Register warden 7dee

---

netlify/util/getFindingsData.js

Depends on https://github.com/code-423n4/api.code4rena.com/pull/613 changes deployed first!

Fetch findings data via two split requests

---

_data/handles/binobi.json

Auto-generated PR to register the new warden binobi
@artem-solidity

Register warden binobi

---

_data/handles/0xPAFF.json

Auto-generated PR to register the new warden 0xPAFF

Register warden 0xPAFF

---

_data/handles/windhustler.json

This auto-generated PR updates info for warden windhustler
@https://github.com/josipkoncurat

Update warden windhustler

---

_data/handles/0xEVM1.json

Auto-generated PR to register the new warden 0xEVM1
@0xEVM1

Register warden 0xEVM1

---

_data/handles/Daloe.json

Auto-generated PR to register the new warden Daloe

Register warden Daloe

---

_data/handles/gladiator.json

Auto-generated PR to register the new warden gladiator

Register warden gladiator

---

_data/handles/cachemeifucan.json

Auto-generated PR to register the new warden cachemeifucan

Register warden cachemeifucan

---

_data/handles/BBge.json

Auto-generated PR to register the new warden BBge
@BBge

Register warden BBge

---

_data/handles/nikita-go.json

Auto-generated PR to register the new warden nikita-go
@nikita-go

Register warden nikita-go

---

_data/handles/0x232323.json

Auto-generated PR to register the new warden 0x232323

Register warden 0x232323

---

_data/handles/J0xseph.json

Auto-generated PR to register the new warden J0xseph

Register warden J0xseph

---

_data/handles/honuonhval.json

Auto-generated PR to register the new warden honuonhval
@honuonhval

Register warden honuonhval

---

_data/handles/valentin_s2304.json

Auto-generated PR to register the new warden valentin_s2304

Register warden valentin_s2304

---

_data/handles/0xSiddharth.json

Auto-generated PR to register the new warden 0xSiddharth
@0xSiddharth

Register warden 0xSiddharth

---

_data/handles/0xddts.json

Auto-generated PR to register the new warden 0xddts

Register warden 0xddts

---

_data/handles/ValentineOrga.json

Auto-generated PR to register the new warden ValentineOrga
@ValentineCodes

Register warden ValentineOrga

---

_data/handles/mladenov.json

Auto-generated PR to register the new warden mladenov

Register warden mladenov

---

_data/handles/Krabs.json

Auto-generated PR to register the new warden Krabs
@YassineSMARA

Register warden Krabs

---

_data/handles/alexlee.json

Auto-generated PR to register the new warden alexlee

Register warden alexlee

---

_data/handles/pridegsu.json

Auto-generated PR to register the new warden pridegsu
@mattiascaricato

Register warden pridegsu

---

_data/handles/akasimo.json

Auto-generated PR to register the new warden akasimo
@akasimo

Register warden akasimo

---

_data/handles/WoolCentaur.json

Auto-generated PR to register the new warden WoolCentaur

Register warden WoolCentaur

---

_data/handles/Cyfrin.json

This auto-generated PR modifies the team Cyfrin
The request was made by alexroan

Edit team Cyfrin

---

_data/handles/Cujo.json

Auto-generated PR to register the new warden Cujo

Register warden Cujo

---

_data/handles/alliums8510.json

Auto-generated PR to register the new warden alliums8510
@alliums-p

Register warden alliums8510

---

_data/handles/REACH.json

This auto-generated PR modifies the team REACH
The request was made by infosec_us_team

Edit team REACH

---

_data/handles/ajayaswal.json

Auto-generated PR to register the new warden ajayaswal

Register warden ajayaswal

---

_data/handles/virusbug.json

Auto-generated PR to register the new warden virusbug

Register warden virusbug

---

_data/handles/0xAtharv.json

Auto-generated PR to register the new warden 0xAtharv
@0xAtharva

Register warden 0xAtharv

---

_data/handles/0xBFace.json

Auto-generated PR to register the new warden 0xBFace

Register warden 0xBFace

---

_data/handles/ChainGuardian.json

Auto-generated PR to register the new warden ChainGuardian
@kevin-fruitful

Register warden ChainGuardian

---

_data/handles/juicy.json

This auto-generated PR updates info for warden juicy
@roinevirta

Update warden juicy

---

_data/handles/royalcoder.json

Auto-generated PR to register the new warden royalcoder

Register warden royalcoder

---

_data/handles/blakewh.json

Auto-generated PR to register the new warden blakewh
@blakehatch

Register warden blakewh

---

_data/handles/crypto586.json

Auto-generated PR to register the new warden crypto586

Register warden crypto586

---

_data/handles/dbs99.json

Auto-generated PR to register the new warden dbs99
@dabos

Register warden dbs99

---

_data/handles/AzC05.json

Auto-generated PR to register the new warden AzC05

Register warden AzC05

---

_data/handles/shamsulhaq123.json

Auto-generated PR to register the new warden shamsulhaq123

Register warden shamsulhaq123

---

_data/handles/sussy_hacka.json

Auto-generated PR to register the new warden sussy_hacka

Register warden sussy_hacka

---

_data/handles/binaryogi.json

Auto-generated PR to register the new warden binaryogi

Register warden binaryogi

---

_data/handles/TermoHash.json

Auto-generated PR to register the new warden TermoHash
@ArnaudVolle

Register warden TermoHash

---

_data/handles/Shalanov.json

Auto-generated PR to register the new warden Shalanov
@ShaDi777

Register warden Shalanov

---

_data/handles/xuwinnie.json

Auto-generated PR to register the new warden xuwinnie

Register warden xuwinnie

---

_data/handles/CrypticShepherd.json

Auto-generated PR to register the new warden CrypticShepherd
@CrypticShepherd

Register warden CrypticShepherd

---

_data/handles/patitonar.json

This auto-generated PR updates info for warden patitonar
@patitonar

Update warden patitonar

---

_data/handles/0xlyov.json

Auto-generated PR to register the new warden 0xlyov

Register warden 0xlyov

---

_data/handles/Audit_Avengers.json

This auto-generated PR modifies the team Audit_Avengers
The request was made by JP_Courses

Edit team Audit_Avengers

---

_data/handles/eazyg.json

Auto-generated PR to register the new warden eazyg
@ginogf

Register warden eazyg

---

_data/handles/misfitD00M.json

Auto-generated PR to register the new warden misfitD00M

Register warden misfitD00M

---

_data/handles/twcctop.json

Auto-generated PR to register the new warden twcctop

Register warden twcctop

---

_data/handles/hanz0x07.json

Auto-generated PR to register the new warden hanz0x07

Register warden hanz0x07

---

_data/handles/MrPotatoMagic.json

Auto-generated PR to register the new warden MrPotatoMagic
@mcgrathcoutinho

Register warden MrPotatoMagic

---

_data/handles/mustythefirst.json

Auto-generated PR to register the new warden mustythefirst
@mustythefirst

Register warden mustythefirst

---

_data/handles/saif_atom.json

Auto-generated PR to register the new warden saif_atom
@SaifAtom

Register warden saif_atom

---

_data/handles/Pithoriya.json

Auto-generated PR to register the new warden Pithoriya
@https://github.com/Pithoriya

Register warden Pithoriya

---

_data/handles/securenetizen123.json

Auto-generated PR to register the new warden securenetizen123
@securenetizen123

Register warden securenetizen123

---

_data/handles/0xAce.json

This auto-generated PR creates the team 0xAce

Create team 0xAce

---

_data/handles/pb.json

Auto-generated PR to register the new warden pb

Register warden pb

---

_data/handles/spoofasa.json

Auto-generated PR to register the new warden spoofasa

Register warden spoofasa

---

_data/handles/n0ct3m.json

Auto-generated PR to register the new warden n0ct3m
@NoctemLeges

Register warden n0ct3m

---

_data/handles/Audit_Avengers_2.json

This auto-generated PR modifies the team Audit_Avengers_2
The request was made by JP_Courses

Edit team Audit_Avengers_2

---

_data/handles/kademlia.json

Auto-generated PR to register the new warden kademlia
@WilfredTA

Register warden kademlia

---

_data/handles/zynner.json

Auto-generated PR to register the new warden zynner

Register warden zynner

---

_data/handles/rapha.json

Auto-generated PR to register the new warden rapha
@RaphaelNdonga

Register warden rapha

---

_data/handles/Cayo.json

Auto-generated PR to register the new warden Cayo

Register warden Cayo

---

_data/handles/phillmenezes.json

Auto-generated PR to register the new warden phillmenezes
@menezesphill

Register warden phillmenezes

---

_data/handles/semangatmenguli.json

Auto-generated PR to register the new warden semangatmenguli

Register warden semangatmenguli

---

_data/handles/DEDSEC.json

This auto-generated PR modifies the team DEDSEC
The request was made by naveendilsara

Edit team DEDSEC

---

_data/handles/Canyon.json

Auto-generated PR to register the new warden Canyon

Register warden Canyon

---

_data/handles/Krusher.json

Auto-generated PR to register the new warden Krusher

Register warden Krusher

---

_data/handles/JimmyK.json

Auto-generated PR to register the new warden JimmyK

Register warden JimmyK

---

_data/handles/Thebest4fun.json

Auto-generated PR to register the new warden Thebest4fun

Register warden Thebest4fun

---

_data/handles/cholakov.json

Auto-generated PR to register the new warden cholakov
@https://github.com/cholakovsimeon

Register warden cholakov

---

_data/handles/BugBusters.json

This auto-generated PR creates the team BugBusters

Create team BugBusters

---

_data/handles/0xdd.json

This auto-generated PR modifies the team 0xdd
The request was made by a3yip6

Edit team 0xdd

---

_data/handles/0xweb3boy.json

Auto-generated PR to register the new warden 0xweb3boy
@0xweb3boy

Register warden 0xweb3boy

---

_data/handles/hun-web3.json

Auto-generated PR to register the new warden hun-web3

Register warden hun-web3

---

_data/handles/statrixlabs.json

Auto-generated PR to register the new warden statrixlabs

Register warden statrixlabs

---

_data/handles/av4x.json

Auto-generated PR to register the new warden av4x

Register warden av4x

---

_data/handles/Yardi256.json

Auto-generated PR to register the new warden Yardi256

Register warden Yardi256

---

_data/handles/0xUndefined.json

Auto-generated PR to register the new warden 0xUndefined

Register warden 0xUndefined

---

_data/handles/kalashnikov66p.json

Auto-generated PR to register the new warden kalashnikov66p
@kalashnikov66p

Register warden kalashnikov66p

---

_data/handles/Rorschachdev.json

Auto-generated PR to register the new warden Rorschachdev
@eduardonicoleit

Register warden Rorschachdev

---

_data/handles/Bugi.json

Auto-generated PR to register the new warden Bugi

Register warden Bugi

---

_data/handles/0xElvisC0stell0.json

Auto-generated PR to register the new warden 0xElvisC0stell0

Register warden 0xElvisC0stell0

---

_data/handles/jacobheun.json

Auto-generated PR to register the new warden jacobheun
@jacobheun

Register warden jacobheun

---

_data/handles/Gaonuk.json

Auto-generated PR to register the new warden Gaonuk
@Gaonuk

Register warden Gaonuk

---

_data/handles/abe23.json

Auto-generated PR to register the new warden abe23
@avrohomdu@gmail.com

Register warden abe23

---

_data/handles/SecretZoo.json

Auto-generated PR to register the new warden SecretZoo

Register warden SecretZoo

---

_data/handles/nighthawk-test.json

Auto-generated PR to register the new warden nighthawk-test

Register warden nighthawk-test

---

_data/handles/RotiTelur.json

Auto-generated PR to register the new warden RotiTelur
@roti-c137

Register warden RotiTelur

---

_data/handles/akriosss477.json

Auto-generated PR to register the new warden akriosss477

Register warden akriosss477

---

_data/handles/RUBY-BEAR-REACH.json

This auto-generated PR modifies the team RUBY-BEAR-REACH
The request was made by Mis4nthr0pic

Edit team RUBY-BEAR-REACH

---

_data/handles/wolficy.json

Auto-generated PR to register the new warden wolficy
@https://github.com/bautista1405

Register warden wolficy

---

_data/handles/aidenpearce369.json

Auto-generated PR to register the new warden aidenpearce369

Register warden aidenpearce369

---

_data/handles/BLUE-FOX-REACH.json

This auto-generated PR creates the team BLUE-FOX-REACH

Create team BLUE-FOX-REACH

---

_data/handles/GREY-GORILLA-REACH.json

This auto-generated PR creates the team GREY-GORILLA-REACH

Create team GREY-GORILLA-REACH

---

_data/handles/DARK-CLAW-REACH.json

This auto-generated PR creates the team DARK-CLAW-REACH

Create team DARK-CLAW-REACH

---

_data/handles/honey-k12.json

Auto-generated PR to register the new warden honey-k12

Register warden honey-k12

---

_data/handles/mkaya13.json

Auto-generated PR to register the new warden mkaya13
@mkaya13

Register warden mkaya13

---

_data/handles/Dimagu.json

This auto-generated PR modifies the team Dimagu
The request was made by marcKn

Edit team Dimagu

---

_data/handles/unblvr.json

Auto-generated PR to register the new warden unblvr
@myrdyr

Register warden unblvr

---

_data/handles/0x70C9.json

Auto-generated PR to register the new warden 0x70C9

Register warden 0x70C9

---

_data/handles/dgnnn.json

Auto-generated PR to register the new warden dgnnn

Register warden dgnnn

---

_data/handles/jansel92.json

Auto-generated PR to register the new warden jansel92

Register warden jansel92

---

_data/handles/dlabs.json

This auto-generated PR creates the team dlabs

Create team dlabs

---

_data/handles/0xGodess.json

Auto-generated PR to register the new warden 0xGodess

Register warden 0xGodess

---

_data/handles/purrrrrrrrrrrrrrrrrrrr.json

Auto-generated PR to register the new warden purrrrrrrrrrrrrrrrrrrr
@purrrrrrrrrrrrrrrrrrrr

Register warden purrrrrrrrrrrrrrrrrrrr

---

_data/handles/IamZKdevETH.json

Auto-generated PR to register the new warden IamZKdevETH
@IamZKdevETH

Register warden IamZKdevETH

---

_data/handles/shield0x.json

Auto-generated PR to register the new warden shield0x

Register warden shield0x

---

_data/handles/VictoryGod.json

Auto-generated PR to register the new warden VictoryGod

Register warden VictoryGod

---

_data/handles/krishichawda.json

Auto-generated PR to register the new warden krishichawda
@krishichawda

Register warden krishichawda

---

_data/handles/AlphaPlant.json

Auto-generated PR to register the new warden AlphaPlant
@AlphaPlant

Register warden AlphaPlant

---

_data/handles/gautambnsl.json

Auto-generated PR to register the new warden gautambnsl
@gautambnsl

Register warden gautambnsl

---

_data/handles/floop.json

Auto-generated PR to register the new warden floop
@0xfloop

Register warden floop

---

_data/handles/JimmYz.json

Auto-generated PR to register the new warden JimmYz

Register warden JimmYz

---

_data/handles/tiendat715.json

Auto-generated PR to register the new warden tiendat715

Register warden tiendat715

---

_data/handles/johan-nahoj.json

Auto-generated PR to register the new warden johan-nahoj

Register warden johan-nahoj

---

_data/handles/pmort.json

Auto-generated PR to register the new warden pmort
@pmort

Register warden pmort

---

_data/handles/fcids.json

Auto-generated PR to register the new warden fcids

Register warden fcids

---

_data/handles/sherazali.json

Auto-generated PR to register the new warden sherazali

Register warden sherazali

---

_data/handles/CecilNg.json

Auto-generated PR to register the new warden CecilNg

Register warden CecilNg

---

_data/handles/NeverGivemeup.json

Auto-generated PR to register the new warden NeverGivemeup

Register warden NeverGivemeup

---

_data/handles/XDZIBEC.json

Auto-generated PR to register the new warden XDZIBEC

Register warden XDZIBEC

---

_data/handles/zambody.json

Auto-generated PR to register the new warden zambody
@Pokesi

Register warden zambody

---

_data/handles/datadanne.json

Auto-generated PR to register the new warden datadanne
@datadanne

Register warden datadanne

---

_data/handles/wangxx2026.json

Auto-generated PR to register the new warden wangxx2026
@wangxx2026

Register warden wangxx2026

---

_data/handles/Blackhawk.json

Auto-generated PR to register the new warden Blackhawk

Register warden Blackhawk

---

_data/handles/spacesailor.json

Auto-generated PR to register the new warden spacesailor
@spacesailor24

Register warden spacesailor

---

_data/handles/DanielWang888.json

Auto-generated PR to register the new warden DanielWang888

Register warden DanielWang888

---

_data/handles/anuragsoin.json

Auto-generated PR to register the new warden anuragsoin

Register warden anuragsoin

---

_data/handles/zach.json

Auto-generated PR to register the new warden zach
@zach030

Register warden zach

---

_data/handles/nicx.json

Auto-generated PR to register the new warden nicx
@nicolasraus

Register warden nicx

---

_data/handles/clash.json

Auto-generated PR to register the new warden clash

Register warden clash

---

_data/handles/davidbyte32.json

Auto-generated PR to register the new warden davidbyte32

Register warden davidbyte32

---

_data/handles/balaunique.json

Auto-generated PR to register the new warden balaunique

Register warden balaunique

---

_data/handles/Injoker.json

Auto-generated PR to register the new warden Injoker

Register warden Injoker

---

_data/handles/sharonphiliplima.json

Auto-generated PR to register the new warden sharonphiliplima
@sharonphiliplima

Register warden sharonphiliplima

---

_data/handles/shaiho.json

Auto-generated PR to register the new warden shaiho
@aju100

Register warden shaiho

---

_data/handles/Iron_Sen.json

Auto-generated PR to register the new warden Iron_Sen

Register warden Iron_Sen

---

_data/handles/robzh.json

Auto-generated PR to register the new warden robzh

Register warden robzh

---

_data/handles/Verichains.json

This auto-generated PR creates the team Verichains

Create team Verichains

---

_data/handles/0x11singh99.json

Auto-generated PR to register the new warden 0x11singh99
@thenua3bhai

Register warden 0x11singh99

---

_data/handles/nxyera.json

Auto-generated PR to register the new warden nxyera

Register warden nxyera

---

_data/handles/gandu7357.json

Auto-generated PR to register the new warden gandu7357

Register warden gandu7357

---

_data/handles/degrigis.json

Auto-generated PR to register the new warden degrigis
@degrigis

Register warden degrigis

---

_data/handles/0xTiwa.json

Auto-generated PR to register the new warden 0xTiwa
@0xTiwa

Register warden 0xTiwa

---

_data/handles/Yuki.json

Auto-generated PR to register the new warden Yuki
@SilentYuki

Register warden Yuki

---

_data/handles/donkicha.json

Auto-generated PR to register the new warden donkicha

Register warden donkicha

---

_data/handles/404Notfound.json

Auto-generated PR to register the new warden 404Notfound
@october-one

Register warden 404Notfound

---

_data/handles/asimsharf.json

Auto-generated PR to register the new warden asimsharf
@asimsharf

Register warden asimsharf

---

_data/handles/0xhashiman.json

Auto-generated PR to register the new warden 0xhashiman

Register warden 0xhashiman

---

_data/handles/clublynx.json

Auto-generated PR to register the new warden clublynx

Register warden clublynx

---

_data/handles/NayNay_Dev3.json

Auto-generated PR to register the new warden NayNay_Dev3

Register warden NayNay_Dev3

---

_data/handles/Thomas_Xu.json

Auto-generated PR to register the new warden Thomas_Xu
@ThomasXu-blockchain

Register warden Thomas_Xu

---

_data/handles/alexweb3.json

Auto-generated PR to register the new warden alexweb3
@alexweb310

Register warden alexweb3

---

_data/handles/Purplefortress.json

Auto-generated PR to register the new warden Purplefortress

Register warden Purplefortress

---

_data/handles/elaleman.json

Auto-generated PR to register the new warden elaleman
@elalemanx

Register warden elaleman

---

_data/handles/ariel5.json

Auto-generated PR to register the new warden ariel5
@arielsoft

Register warden ariel5

---

_data/handles/Tresury.json

Auto-generated PR to register the new warden Tresury

Register warden Tresury

---

_data/handles/Atree.json

Auto-generated PR to register the new warden Atree

Register warden Atree

---

_data/handles/BLOS.json

Auto-generated PR to register the new warden BLOS

Register warden BLOS

---

_data/handles/FLiao.json

Auto-generated PR to register the new warden FLiao

Register warden FLiao

---

_data/handles/RAHA.json

Auto-generated PR to register the new warden RAHA

Register warden RAHA

---

_data/handles/HunterGuy102.json

Auto-generated PR to register the new warden HunterGuy102
@DuyVo96

Register warden HunterGuy102

---

_data/handles/ghost.json

Auto-generated PR to register the new warden ghost

Register warden ghost

---

_data/handles/Ethan48.json
_data/handles/ethanol.json

Auto-generated PR to register the new warden Ethan48
@Ethanol48

Register warden ethanol

---

_data/handles/hazakzy.json

Auto-generated PR to register the new warden hazakzy
@hazakzy

Register warden hazakzy

---

_data/handles/Sinasoheily.json

Auto-generated PR to register the new warden Sinasoheily

Register warden Sinasoheily

---

_data/handles/em_mutable.json

Auto-generated PR to register the new warden em_mutable
@https://github.com/Mouzayan

Register warden em_mutable

---

_data/handles/IvanAtanasov.json

Auto-generated PR to register the new warden IvanAtanasov
@IvanAtanasov7

Register warden IvanAtanasov

---

_data/handles/Artm.json

Auto-generated PR to register the new warden Artm
@0xArtm

Register warden Artm

---

_data/handles/RED-LOTUS-REACH.json

This auto-generated PR modifies the team RED-LOTUS-REACH
The request was made by Mis4nthr0pic

Edit team RED-LOTUS-REACH

---

_data/handles/SCARLET-HAWK-REACH.json

This auto-generated PR modifies the team SCARLET-HAWK-REACH
The request was made by Mis4nthr0pic

Edit team SCARLET-HAWK-REACH

---

_data/handles/apollon.json

Auto-generated PR to register the new warden apollon

Register warden apollon

---

_data/handles/Remscar.json

Auto-generated PR to register the new warden Remscar
@Remscar

Register warden Remscar

---

_data/handles/homayon1369.json

Auto-generated PR to register the new warden homayon1369

Register warden homayon1369

---

_data/handles/ZiZoOoOo.json

Auto-generated PR to register the new warden ZiZoOoOo

Register warden ZiZoOoOo

---

_data/handles/davidvip2006.json

Auto-generated PR to register the new warden davidvip2006

Register warden davidvip2006

---

_data/handles/telampos.json

Auto-generated PR to register the new warden telampos

Register warden telampos

---

_data/handles/LaScaloneta.json

This auto-generated PR modifies the team LaScaloneta
The request was made by juancito

Edit team LaScaloneta

---

_data/handles/BadMaths.json

This auto-generated PR modifies the team BadMaths
The request was made by nicobevi

Edit team BadMaths

---

_data/handles/Dzakfest.json

Auto-generated PR to register the new warden Dzakfest

Register warden Dzakfest

---

_data/handles/0x76.json

Auto-generated PR to register the new warden 0x76

Register warden 0x76

---

_data/handles/chanoong.json

Auto-generated PR to register the new warden chanoong

Register warden chanoong

---

_data/handles/ulexam.json

Auto-generated PR to register the new warden ulexam

Register warden ulexam

---

_data/handles/hatientrang.json

Auto-generated PR to register the new warden hatientrang

Register warden hatientrang

---

_data/handles/redalert3838.json

Auto-generated PR to register the new warden redalert3838

Register warden redalert3838

---

_data/handles/nick199910.json

Auto-generated PR to register the new warden nick199910
@nick199910

Register warden nick199910

---

_data/handles/Outlaw63.json

Auto-generated PR to register the new warden Outlaw63

Register warden Outlaw63

---

_data/handles/nonAnon.json

Auto-generated PR to register the new warden nonAnon
@VestedJosh

Register warden nonAnon

---

_data/handles/maloleg.json

Auto-generated PR to register the new warden maloleg

Register warden maloleg

---

_data/handles/koo.json

Auto-generated PR to register the new warden koo
@koocola

Register warden koo

---

_data/handles/Turbo_Kirby.json

Auto-generated PR to register the new warden Turbo_Kirby

Register warden Turbo_Kirby

---

_data/handles/Homeostasis.json

Auto-generated PR to register the new warden Homeostasis
@manishgotame

Register warden Homeostasis

---

_data/handles/LAM_S_C.json

Auto-generated PR to register the new warden LAM_S_C

Register warden LAM_S_C

---

_data/handles/VaporKane.json

Auto-generated PR to register the new warden VaporKane
@VaporKane

Register warden VaporKane

---

_data/handles/IlijasDev.json

Auto-generated PR to register the new warden IlijasDev
@ilijasdev

Register warden IlijasDev

---

_data/handles/zinc42.json

Auto-generated PR to register the new warden zinc42
@zinc43

Register warden zinc42

---

_data/handles/0xdaorren.json

Auto-generated PR to register the new warden 0xdaorren

Register warden 0xdaorren

---

_data/handles/rado.json

Auto-generated PR to register the new warden rado
@RadoslavDimchev

Register warden rado

---

_data/handles/lsaudit.json

Auto-generated PR to register the new warden lsaudit

Register warden lsaudit

---

_data/handles/BPZ.json

This auto-generated PR modifies the team BPZ
The request was made by zinc42

Edit team BPZ

---

_data/handles/0xn006e7.json

Auto-generated PR to register the new warden 0xn006e7

Register warden 0xn006e7

---

_data/handles/ri_dev.json

Auto-generated PR to register the new warden ri_dev
@ri-dev-git

Register warden ri_dev

---

_data/handles/generalist.json

Auto-generated PR to register the new warden generalist

Register warden generalist

---

_data/handles/cocodrilette.json

Auto-generated PR to register the new warden cocodrilette
@cocodrilette

Register warden cocodrilette

---

_data/handles/ayo_dev.json

Auto-generated PR to register the new warden ayo_dev
@malik672

Register warden ayo_dev

---

_data/handles/3kus-iosiro.json

Auto-generated PR to register the new warden 3kus-iosiro

Register warden 3kus-iosiro

---

_data/handles/GarethLarkan.json

Auto-generated PR to register the new warden GarethLarkan

Register warden GarethLarkan

---

_data/handles/ongainz.json

Auto-generated PR to register the new warden ongainz
@osogogo

Register warden ongainz

---

_data/handles/mikd0.json

Auto-generated PR to register the new warden mikd0

Register warden mikd0

---

_data/handles/Sthitpragnya.json

Auto-generated PR to register the new warden Sthitpragnya
@sthitpragnya

Register warden Sthitpragnya

---

_data/handles/Verichains.json

This auto-generated PR modifies the team Verichains
The request was made by lifebow

Edit team Verichains

---

_data/handles/deth.json

Auto-generated PR to register the new warden deth
@0xdeth

Register warden deth

---

_data/handles/Brian_Lloyd.json

Auto-generated PR to register the new warden Brian_Lloyd
@blachua

Register warden Brian_Lloyd

---

_data/handles/sangeen.json

Auto-generated PR to register the new warden sangeen

Register warden sangeen

---

_data/handles/DeliChainSec.json
_data/handles/YoungWolves.json

Adding back teams from https://github.com/code-423n4/code423n4.com/pull/10906 to trigger the old webhooks.

chore: readd teams from #1096

---

_data/handles/0xEmmalien.json

Auto-generated PR to register the new warden 0xEmmalien
@eofafrica4lyf

Register warden 0xEmmalien

---

_data/handles/unexployed.json

Auto-generated PR to register the new warden unexployed

Register warden unexployed

---

_data/handles/sunbreather.json

Auto-generated PR to register the new warden sunbreather

Register warden sunbreather

---

_data/handles/castle_chain.json

Auto-generated PR to register the new warden castle_chain

Register warden castle_chain

---

_data/handles/stimpy.json

Auto-generated PR to register the new warden stimpy
@st7mpy

Register warden stimpy

---

_data/handles/T4k4.json

Auto-generated PR to register the new warden T4k4

Register warden T4k4

---

_data/handles/dove.json

Auto-generated PR to register the new warden dove

Register warden dove

---

_data/handles/Jeamz.json

Auto-generated PR to register the new warden Jeamz
@obande-code

Register warden Jeamz

---

_data/handles/buggg.json

Auto-generated PR to register the new warden buggg

Register warden buggg

---

_data/handles/0xPublicGoods.json

Auto-generated PR to register the new warden 0xPublicGoods
@0xPublicGoods

Register warden 0xPublicGoods

---

_data/handles/3docSec.json

Auto-generated PR to register the new warden 3docSec

Register warden 3docSec

---

_data/handles/thedude.json

Auto-generated PR to register the new warden thedude

Register warden thedude

---

_data/handles/herrejas000.json

Auto-generated PR to register the new warden herrejas000

Register warden herrejas000

---

_data/handles/TheNinja27.json

Auto-generated PR to register the new warden TheNinja27

Register warden TheNinja27

---

_data/handles/Amartinmalmi.json

Auto-generated PR to register the new warden Amartinmalmi

Register warden Amartinmalmi

---

_data/handles/carin99.json

Auto-generated PR to register the new warden carin99

Register warden carin99

---

_data/handles/iBlastert1.json

Auto-generated PR to register the new warden iBlastert1

Register warden iBlastert1

---

_data/handles/random1233.json

Auto-generated PR to register the new warden random1233

Register warden random1233

---

_data/handles/mislikli4ko.json

Auto-generated PR to register the new warden mislikli4ko

Register warden mislikli4ko

---

_data/handles/xygzy.json

Auto-generated PR to register the new warden xygzy

Register warden xygzy

---

_data/handles/EvilPacket.json

Auto-generated PR to register the new warden EvilPacket
@ep-c4

Register warden EvilPacket

---

_data/handles/0xNightRaven.json

Auto-generated PR to register the new warden 0xNightRaven

Register warden 0xNightRaven

---

_data/handles/maanas.json

Auto-generated PR to register the new warden maanas

Register warden maanas

---

_data/handles/Akxai.json

Auto-generated PR to register the new warden Akxai
@Akxai

Register warden Akxai

---

_data/handles/0xAnah.json

Auto-generated PR to register the new warden 0xAnah
@0xAnah

Register warden 0xAnah

---

_data/handles/akashvana.json

Auto-generated PR to register the new warden akashvana
@akashvana

Register warden akashvana

---

_data/handles/ilkatel.json

Auto-generated PR to register the new warden ilkatel
@ilkatel

Register warden ilkatel

---

_data/handles/vallahor.json

Auto-generated PR to register the new warden vallahor
@vallahor

Register warden vallahor

---

_data/handles/Lynxlyx.json

Auto-generated PR to register the new warden Lynxlyx

Register warden Lynxlyx

---

_data/handles/Acestyles.json

Auto-generated PR to register the new warden Acestyles
@Acestyles

Register warden Acestyles

---

_data/handles/bstn.json

Auto-generated PR to register the new warden bstn

Register warden bstn

---

_data/handles/0x19.json

Auto-generated PR to register the new warden 0x19

Register warden 0x19

---

_data/handles/0xBugBuster.json

Auto-generated PR to register the new warden 0xBugBuster

Register warden 0xBugBuster

---

_data/handles/zhaojie.json

Auto-generated PR to register the new warden zhaojie

Register warden zhaojie

---

_data/handles/0x_yasshhh_.json

Auto-generated PR to register the new warden 0x_yasshhh_
@yash251

Register warden 0x_yasshhh_

---

_data/handles/RomanKoziorov.json

Auto-generated PR to register the new warden RomanKoziorov

Register warden RomanKoziorov

---

_data/handles/multichainmagus.json

Auto-generated PR to register the new warden multichainmagus
@multichainmagus

Register warden multichainmagus

---

_data/handles/mahyar.json

Auto-generated PR to register the new warden mahyar
@notmhyr

Register warden mahyar

---

_data/handles/nexxo84.json

Auto-generated PR to register the new warden nexxo84
@Raúl

Register warden nexxo84

---

_data/handles/sheriff.json

Auto-generated PR to register the new warden sheriff

Register warden sheriff

---

_data/handles/yisu.json
_data/handles/yisumari.json

Auto-generated PR to register the new warden yisumari

Register warden yisu

---

_data/handles/alexursol.json

Auto-generated PR to register the new warden alexursol

Register warden alexursol

---

_data/handles/S5.json

This auto-generated PR creates the team S5

Create team S5

---

_data/handles/Shezzar.json

Auto-generated PR to register the new warden Shezzar
@jakub-heba

Register warden Shezzar

---

_data/handles/manner27.json

Auto-generated PR to register the new warden manner27
@manner27

Register warden manner27

---

_data/handles/Lemonino.json

Auto-generated PR to register the new warden Lemonino

Register warden Lemonino

---

_data/handles/cryptoken1.json

Auto-generated PR to register the new warden cryptoken1
@kennethsoftware

Register warden cryptoken1

---

_data/handles/vampireAb.json

Auto-generated PR to register the new warden vampireAb
@vampire-ab

Register warden vampireAb

---

_data/handles/tload.json

Auto-generated PR to register the new warden tload

Register warden tload

---

_data/handles/MHXW.json

Auto-generated PR to register the new warden MHXW

Register warden MHXW

---

_data/handles/oakcobalt.json

Auto-generated PR to register the new warden oakcobalt
@flowercrimson

Register warden oakcobalt

---

_data/README-community_resources.md

Hoping this will help people find stuff back, if they missed the Discord announcements at the time.

Add rough documentation about where website `_data` has gone

---

_data/handles/Alain.json

Auto-generated PR to register the new warden Alain
@@web3hackinglabs

Register warden Alain

---

_data/handles/0xCiphky.json

Auto-generated PR to register the new warden 0xCiphky
@areezladhani

Register warden 0xCiphky

---

_data/handles/0xDemuth.json

Auto-generated PR to register the new warden 0xDemuth
@Rohit-2602

Register warden 0xDemuth

---

_data/handles/radcet.json

Auto-generated PR to register the new warden radcet

Register warden radcet

---

_data/handles/deb007.json

Auto-generated PR to register the new warden deb007
@deb0192

Register warden deb007

---

_data/handles/d4emonset.json

Auto-generated PR to register the new warden d4emonset

Register warden d4emonset

---

_data/handles/balsy.json

Auto-generated PR to register the new warden balsy

Register warden balsy

---

_data/handles/mthita.json

Auto-generated PR to register the new warden mthita

Register warden mthita

---

_data/handles/AISec.json

Auto-generated PR to register the new warden AISec

Register warden AISec

---

_data/handles/blutorque.json

Auto-generated PR to register the new warden blutorque

Register warden blutorque

---

_data/handles/Ryonen.json

Auto-generated PR to register the new warden Ryonen
@Drennann

Register warden Ryonen

---

_data/handles/furiousity.json

Auto-generated PR to register the new warden furiousity
@connorjchen

Register warden furiousity

---

_data/handles/Mahi_Vasisth.json

Auto-generated PR to register the new warden Mahi_Vasisth
@MohiniVasisth

Register warden Mahi_Vasisth

---

_data/handles/Darwin.json

Auto-generated PR to register the new warden Darwin

Register warden Darwin

---

_data/handles/sobhan.json

Auto-generated PR to register the new warden sobhan
@xdevman

Register warden sobhan

---

_data/handles/ljj.json

Auto-generated PR to register the new warden ljj
@utkuerkin

Register warden ljj

---

_data/handles/zaz.json

Auto-generated PR to register the new warden zaz
@zaqk

Register warden zaz

---

_data/handles/Abec4299.json

Auto-generated PR to register the new warden Abec4299

Register warden Abec4299

---

_data/handles/0x04bytes.json

Auto-generated PR to register the new warden 0x04bytes
@0x04bytes

Register warden 0x04bytes

---

_data/handles/M0ngi.json

Auto-generated PR to register the new warden M0ngi
@M0ngi

Register warden M0ngi

---

_data/handles/seraviz.json

Auto-generated PR to register the new warden seraviz
@drrav31

Register warden seraviz

---

_data/handles/memegodzleague.json

Auto-generated PR to register the new warden memegodzleague

Register warden memegodzleague

---

_data/handles/engineercuzofdad.json

Auto-generated PR to register the new warden engineercuzofdad
@engineercuzfdad

Register warden engineercuzofdad

---

_data/handles/Lonser.json

Auto-generated PR to register the new warden Lonser

Register warden Lonser

---

_data/handles/drujolt.json

Auto-generated PR to register the new warden drujolt

Register warden drujolt

---

_data/handles/hamedidanial.json

Auto-generated PR to register the new warden hamedidanial

Register warden hamedidanial

---

_data/handles/rakesh0x7.json

Auto-generated PR to register the new warden rakesh0x7
@rakesh0x7

Register warden rakesh0x7

---

_data/handles/vesta_0x.json

Auto-generated PR to register the new warden vesta_0x

Register warden vesta_0x

---

_data/handles/Blckhv.json

Update Blckhv.json Update twitter link

---

_data/handles/suryansh.json

Auto-generated PR to register the new warden suryansh
@ileakalpha

Register warden suryansh

---

_data/handles/pipidu83.json

Auto-generated PR to register the new warden pipidu83

Register warden pipidu83

---

_data/handles/0x_Marc.json

Auto-generated PR to register the new warden 0x_Marc
@Marklin2289

Register warden 0x_Marc

---

_data/handles/procfs.json

Auto-generated PR to register the new warden procfs
@pr0cf5

Register warden procfs

---

_data/handles/Auditwolf.json

Auto-generated PR to register the new warden Auditwolf
@htstarz

Register warden Auditwolf

---

_data/handles/Prestige.json

Auto-generated PR to register the new warden Prestige

Register warden Prestige

---

_data/handles/0x180db.json

Auto-generated PR to register the new warden 0x180db
@0x180db

Register warden 0x180db

---

_data/handles/Mirror.json

Auto-generated PR to register the new warden Mirror

Register warden Mirror

---

_data/handles/ElCid.json

Auto-generated PR to register the new warden ElCid

Register warden ElCid

---

_data/handles/Sentry0x.json

Auto-generated PR to register the new warden Sentry0x

Register warden Sentry0x

---

_data/handles/marcobesier.json

Auto-generated PR to register the new warden marcobesier
@marcobesier

Register warden marcobesier

---

_data/handles/ac0llins.json

Auto-generated PR to register the new warden ac0llins

Register warden ac0llins

---

_data/handles/owadez.json

Auto-generated PR to register the new warden owadez

Register warden owadez

---

_data/handles/roy.json

Auto-generated PR to register the new warden roy

Register warden roy

---

_data/handles/Avi17.json

Auto-generated PR to register the new warden Avi17
@Avik17

Register warden Avi17

---

_data/handles/Mikel-777.json

Auto-generated PR to register the new warden Mikel-777

Register warden Mikel-777

---

_data/handles/sixbullets.json

Auto-generated PR to register the new warden sixbullets

Register warden sixbullets

---

_data/handles/heisenberg.json

Auto-generated PR to register the new warden heisenberg
@akamaitrue

Register warden heisenberg

---

_data/handles/p37m.json

Auto-generated PR to register the new warden p37m

Register warden p37m

---

_data/handles/underethsea.json

Auto-generated PR to register the new warden underethsea

Register warden underethsea
